
function wofFindPuzzles($parentDiv,wordList)
{
	
	let regEx = createRegExFromCharMap($parentDiv.find("input.charMap").first());
	
	if (regEx==null) return;
	
	let results = wordList.match(regEx);
	
	let matchMessage = "";
	let freqMessage = ""
	if (results == null)
	{
		message = "No matches";
		freqMessage="";
	}
	else
	{
		message = results.join("\n");
		let freqMap = results2CharFreqMap(results);
		freqMessage = charFreqMap2Message(freqMap);
	}

	$parentDiv.find("textarea.results").first().val(message);
	$parentDiv.find("textarea.freq").first().val(freqMessage);
}

function results2CharFreqMap(resultsArr)
{
	let result="", letter="", i=0;
	let map = new Map();
	let charCounts = {}
	
	//for (result in resultsArr)
	//{
	resultsArr.forEach(result => {
		
		for (i=0; i<result.length; i++)
		{
			letter = result.charAt(i);
			//addOneToMap(map,letter);
			if (letter > 'Z' || letter < 'A') continue;
			
		    charCounts[letter] = ++charCounts[letter] || 1;
		}
	});
	
	return charCounts;
}

function addOneToMap(map,letter)
{
	let curCount = map.get(letter);
	if (curCount < 0) curCount=1;
	
	curCount += 1;
	
	map.set(letter,curCount);
}

function charFreqMap2Message(freqMap)
{
	//let mapCounts = new Map();
	let mapCounts= {};
	let letter="";
	
	//first organize letter counts into groupings based on count
	for (letter of Object.keys(freqMap))
	{
		let letterCount = freqMap[letter];
		let charList = mapCounts[letterCount];
		
		if (!charList || charList.length == 0)
		{
			charList = "";
		}
		
		charList += letter;
		
		mapCounts[letterCount]=charList;
	}
	
	//now iterate the counts and show letters for each count (decreasing)
	let message = "";
	let keyArray = Object.keys(mapCounts).map(value => parseInt(value));
	keyArray.sort((a,b)=>b-a);
	//for (var count in keyArray)
	keyArray.forEach(count => {
		let currentLine=""
		currentLine += (""+count).padStart(3) + ": "
		let letters = mapCounts[count];
		for (letter of letters)
		{
			currentLine += letter + " ";
		}
		message += currentLine + "\n";
	});
	
	return message;
}

function createRegExFromCharMap($inputElem)
{
	let charMap = $inputElem.val();
	if (charMap.length == 0 ) return;
	
	let charCounts = charMap.split(" ");
	let pattern = "";
	
	for (let i=0; i<charCounts.length; i++)
	{
		let charCount = charCounts[i];
		if (charCount.length == 0) continue;
		if (isNaN(charCount)) continue;
		if (pattern.length > 0)
		{
			pattern += ' ';
		}
		
		pattern += '[\\w\'-]{' + charCount + '}';
	}
	
	if (pattern.length > 0)
	{
		pattern = '^' + pattern + '[ ]?$';
		return new RegExp(pattern,'gm');
	}
	
	return null;
}


let wofAnswers=
`
KINGSTON JAMAICA
PEKING CHINA
PLANETARIUM
NOME ALASKA
YELLOWSTONE NATIONAL PARK
LEXINGTON KENTUCKY
OVAL OFFICE
LA GUARDIA AIRPORT
SAN LUIS OBISPO
SALEM OREGON
FORT KNOX
TIMES SQUARE
MOBILE ALABAMA
THE EVERGLADES
THE FAR CORNERS OF THE EARTH
STATE CAPITOL
ALCATRAZ
LOUISVILLE KENTUCKY
MIDDLE ATLANTIC STATES
WARSAW POLAND
THE CUMBERLAND PASS
THE VATICAN
LAKE PLACID
CINCINNATI
SANTIAGO CHILE
CARLSBAD CAVERNS
FISHERMAN'S WHARF
CHINATOWN
MONTICELLO
TUCSON ARIZONA
EXECUTIVE WASHROOM
ALBANY NEW YORK
NEW ZEALAND
LOST AND FOUND COUNTER
DOWN UNDER
PLAYGROUND
SACRAMENTO
TOP OF THE HEAP
NOTTINGHAM ENGLAND
HELSINKI FINLAND
FRONT ROW CENTER
ATLANTIC CITY
THE PENTAGON
ALEXANDRIA VIRGINIA
OUTER SPACE
PORTLAND MAINE
UPPER RIGHTHAND CORNER
SYDNEY AUSTRALIA
CENTER STAGE
HANNIBAL MISSOURI
CORNER DRUGSTORE
PENTHOUSE SUITE
BURBANK CALIFORNIA
THE PAINTED DESERT
COMBAT ZONE
BOOT HILL
SANTA ANITA RACETRACK
ANDOVER MARYLAND
ANAHEIM STADIUM
OUT OF THE WAY
MUNICH GERMANY
MINE SHAFT
ORLANDO FLORIDA
THE HOLY LAND
SAUDI ARABIA
THE BACKWOODS
ELLIS ISLAND
SAN JUAN PUERTO RICO
IRELAND
WESTERN HEMISPHERE
FROZEN FOOD SECTION
MONTEGO BAY
DENTIST'S OFFICE
GREENWICH VILLAGE
BARNYARD
MANHATTAN ISLAND
THE GROUND FLOOR
UNIVERSAL STUDIOS
THE LOUVRE
MADRID SPAIN
UNDER THE CHRISTMAS TREE
HONOLULU
DETROIT MICHIGAN
DOWN BY THE OLD MILL STREAM
MIDDLE OF THE ROAD
EAST PAKISTAN
IN THE ATTIC
FLORENCE ITALY
CENTER COURT
O'HARE AIRPORT
IN THE MIDDLE OF THE RING
CARACAS VENEZUELA
CITY HALL
BERN SWITZERLAND
HOMETOWN
NEWPORT BEACH
CONTINENTAL DIVIDE
HIDDEN COMPARTMENT
SMOKY MOUNTAINS
THE EQUATOR
NEXT TO LAST
ATHENS GEORGIA
PIZZA PARLOR
HIROSHIMA
BOWLING ALLEY
MILWAUKEE
THE BALCONY
UPPER ATMOSPHERE
THE BOTTOM RUNG
RADIO CITY MUSIC HALL
VIENNA AUSTRIA
ACAPULCO
AUSTIN TEXAS
ON THE PERIMETER
UP THE ROAD APIECE
ANNAPOLIS
STUTTGART GERMANY
GRAND CENTRAL STATION
ON THE HIGH SEAS
TIMES SQUARE
ZIMBABWE AFRICA
HAWAIIAN ISLANDS
CAPE COD
SEASIDE
BANGKOK THAILAND
THE BACK ROW
PAWNSHOP
CAIRO EGYPT
SCHOOL ROOM
CARIBBEAN
SEOUL KOREA
GOVERNOR'S MANSION
VIENNA AUSTRIA
AROUND THE BEND
UNITED STATES NAVAL ACADEMY
FAIRFAX NOVA SCOTIA
ON THE OUTSIDE LOOKING IN
NEW DELHI INDIA
HONG KONG
HOUSTON ASTRODOME
LOWER MANHATTAN
WALL STREET
DURHAM NORTH CAROLINA
SUPERMARKET
ANCHORAGE
ASIA MINOR
STILLWATER OKLAHOMA
THEATER BALCONY
ETHIOPIA
OUTER MONGOLIA
SPRINGFIELD ILLINOIS
LAUNDROMAT
TIJUANA MEXICO
MISSISSIPPI
KATMANDU
BROOKLYN
HARVARD MEDICAL SCHOOL
HIMALAYAN MOUNTAINS
SAN DIEGO
RHODE ISLAND
BROOM CLOSET
DISNEYLAND
COLUMBIA
ROME ITALY
BASEBALL DIAMOND
BASKETBALL COURT
COPERNICUS
THURGOOD MARSHALL
CHAMBERMAID
WOODY ALLEN
SHOESHINE BOY
GEORGE WASHINGTON CARVER
SIGMUND FREUD
LYNDON BAINES JOHNSON
TELEPHONE OPERATOR
GAS STATION ATTENDANT
BERT PARKS
SHORT- ORDER COOK
COMPANY CLERK
HEAD FOOTBALL COACH
ELEANOR ROOSEVELT
THOMAS PAINE
MEDICAL DOCTOR
ENGINEER
MILLARD FILLMORE
DIESEL MECHANIC
CHURCH USHER
TOP BANANA
GARBAGE COLLECTOR
NATHAN HALE
REGIONAL DIRECTOR
COAL MINER
ORTHOPEDIC SURGEON
ANGIE DICKINSON
CHESS CHAMPION
APPLIANCE REPAIRMAN
ROBERT KENNEDY
ASSISTANT DIRECTOR
PHYSICAL THERAPIST
BABE RUTH
BABY SITTER
BALLET DANCER
SECRET AGENT
COMPUTER PROGRAMMER
HUMAN BEING
ARCHBISHOP OF CANTERBURY
SALES CLERK
MICHAEL CAINE
THE PARISH PRIEST
LAW STUDENT
CHANCELLOR
ISAAC NEWTON
BOOKER T WASHINGTON
INDIRA GANDHI
BEN FRANKLIN
MARTIN LUTHER KING
NAPOLEON BONAPARTE
CARL SANDBURG
EDGAR ALLEN POE
THOMAS JEFFERSON
CAKE DECORATOR
DEFENSIVE TACKLE
UNINVITED GUEST
ANGLO- SAXON
UNDERWRITER
WINSTON CHURCHILL
DIRECTOR OF MARKETING
CARRIE NATION
ENGLISH TEACHER
NIGHT WATCHMAN
ALEXANDER GRAHAM BELL
CONVENTION DELEGATE
NEXT DOOR NEIGHBOR
LADYBIRD JOHNSON
MEDICAL STUDENT
VINCE LOMBARDI
TALENT SCOUT
NIKITA KRUSCHEV
JIMMY CONNERS
WILLIAM THE CONQUEROR
NEWSPAPER COLUMNIST
PUBLISHED AUTHOR
JULIUS CAESAR
SMOOTH TALKER
HAIR STYLIST
THEODORE ROOSEVELT
CIVILIAN
THE SHAH OF IRAN
SERGEANT YORK
REAL ESTATE BROKER
TOMMY DORSEY
CAMP COUNSELOR
SALVADOR DALI
ELIGIBLE BACHELOR
JILTED SUITOR
BILLIE JEAN KING
SYSTEMS ANALYST
POCAHONTAS
INNOCENT BYSTANDER
THOMAS EDISON
CLASS CLOWN
RALPH WALDO EMERSON
MATA HARI
HIGH SCHOOL DROPOUT
ADJUTANT GENERAL
ELEVATOR OPERATOR
FRANK LLOYD WRIGHT
EXPECTANT MOTHER
JOHN GLENN
ALBERT SCHWEITZER
JACK-OF- ALL-TRADES
MORTICIAN
ALEXANDER HAMILTON
CONSTANT COMPANION
ARISTOTLE ONASSIS
ESCAPED CONVICT
ANN LANDERS
RIGHT-HAND MAN
AARON BURR
MARIE ANTOINETTE
ANTIQUE COLLECTOR
ANIMAL TAMER
ARNOLD PALMER
HEAD UMPIRE
THE LAST MAN ON EARTH
DANIEL BOONE
BARRY GOLDWATER
APPRENTICE
ICE-CREAM VENDOR
JOHNNY COME LATELY
FERDINAND MAGELLAN
TICKET TAKER
BRUCE SPRINGSTEEN
JACKIE COOPER
UNDERMINER
PAPERHANGER
BLACKSMITH
MARQUIS DE SADE
MECHANICAL ENGINEER
CESAR CHAVEZ
HEAD WAITER
EUROPEAN IMMIGRANT
MENACHEM BEGIN
SEVENTH-DAY ADVENTIST
NAILBITER
ANDREW JACKSON
DISK JOCKEY
KEEPER OF THE FLAME
EVANGELIST
DALE CARNEGIE
WILLIAM SHAKESPEARE
GIFTED CHILD
SAM HOUSTON
GROVER CLEVELAND
JASON ROBARDS
PHILANDERER
CAMERAMAN
WILLIAM RANDOLPH HEARST
SNAKE CHARMER
MEREDITH BAXTER BIRNEY
CERTIFIED PUBLIC ACCOUNTANT
BUS DRIVER
LEONARD BERNSTEIN
NAVIGATOR
MAO TSE- TUNG
CZAR NICHOLAS
PERSONNEL DIRECTOR
CONFUCIUS
KAREEM ABDUL- JABBAR
ANDY WARHOL
HIRED HAND
WILT CHAMBERLAIN
ELECTED OFFICIAL
CLASSMATE
STATE SENATOR
MINNESOTA FATS
PUPPETEER
JAMES MADISON
OBJECTIVE OBSERVER
WYATT EARP
EUCLID
DANNY THOMAS
REMBRANDT
POLITICAL POLLSTER
SAINT FRANCIS OF ASSISI
LAWRENCE OLIVIER
JESSE JAMES
HARRY TRUMAN
TAX COLLECTOR
MUHAMMAD ALI
COMMITTEE CHAIRMAN
DWIGHT DAVID EISENHOWER
NOVELIST
SIR WALTER RALEIGH
CITY PLANNER
GALILEO
CLAIMS ADJUSTER
GOLD KEYCHAIN
PORKPIE HAT
CRANBERRY SAUCE
PLUTONIUM
BOTTLED WATER
TURNTABLE
BEAMED CEILING
HANGNAIL
STUDHORSE
HAIRPIN
PIGGY BANK
CANTALOUPE
JUMPING JACK
BAKING SODA
NEW ENGLAND CLAM CHOWDER
LIQUOR CABINET
APPLE CIDER
PUNCTUATION MARK
DANDELION
PHONOGRAPH RECORD
ORGANIC COMPOUND
SPLIT PEA SOUP
BIRD FEEDER
CHOCOLATE CHIP COOKIE
MOSQUITO
BUTTERCUP
WEDDING RING
POLLING BOOTH
ENGLISH MUFFIN
SOUP LADLE
INCLEMENT WEATHER
BLACK OLIVE
VEGETABLE OIL
CONTRACTION
TIMEPIECE
COCONUT
HEDGE CLIPPER
HORSESHOE
CHRISTMAS TREE
HOMEMADE BREAD
ROLLER SKATE
INTEGRATED CIRCUIT
PATCHWORK
SKYSCRAPER
THERMOMETER
TOMATO SAUCE
MUSICAL NOTE
POTATO SKIN
SALAMANDER
FISHING LURE
PRINTING PRESS
MEAT CLEAVER
TELEVISION ANTENNA
LOUNGE CHAIR
GREEN PEPPER
DUMBWAITER
SNOWMOBILE
WINDSHIELD WIPER
MIGRAINE HEADACHE
HANDMADE QUILT
SALT SHAKER
TOOTHACHE
BROKEN SPOKE
ACHILLES HEEL
DEPLETION ALLOWANCE
CORKSCREW
PACK ANIMAL
CHINESE FOOD
SAUSAGE PATTY
REVOLVING DOOR
CASHIER'S CHECK
CAN OPENER
JACKET POCKET
HAIRPIN
BLOCK AND TACKLE
BAKED POTATO
PENCIL SHARPENER
CALCULATOR
AFFIDAVIT
EXTENDED WARRANTY
HORS D'OEUVRE
UNSALTED PEANUT
WINDMILL
SHOOTING STAR
MICROWAVE OVEN
TUXEDO
COMMON SENSE
LONG DISTANCE PHONE CALL
VIOLIN CASE
LEAST COMMON DENOMINATOR
HARVEY WALLBANGER
HANG GLIDER
ESCALATOR
CORN ON THE COB
MONOCLE
RUBBER BAND
INGROWN TOENAIL
LACERATED CONTUSION
HUMMINGBIRD
LULLABY
FUEL INJECTOR
AIRCRAFT CARRIER
SHOE POLISH
MERRY-GO- ROUND
UNSOLICITED RESPONSE
CHESTNUT
SOUP OF THE DAY
SAUERKRAUT
ELECTRIC BLANKET
WATERMELON
HUMPBACK WHALE
CHURCH STEEPLE
INCOME TAX RETURN
CUBIC METER
TORN LIGAMENT
SUGAR CUBE
BACK INVENTORY
SUBMARINE
SMOKED OYSTER
THUMBTACK
MORNING NEWSPAPER
GRASSHOPPER
AREA CODE
TOOTHPICK
CORN POPPER
DRIVER'S LICENSE
MANNEQUIN
WASHING MACHINE
PEN AND PENCIL SET
HARPSICHORD
PLASTER CAST
CHINESE ALGEBRA
KITCHEN TABLE
CUMMERBUND
CIGARETTE LIGHTER
RADIO TRANSMITTER
CRUDE OIL
SOUR NOTE
MEATBALL
FISHING POLE
DOLLAR BILL
ALLIGATOR
HANDLEBAR MOUSTACHE
WINDOW PANE
SCRATCH PAD
BABY CARRIAGE
LIBRARY CARD
EIGHTEEN WHEELER
ENCHILADA
BAROMETER
PORTRAIT
OBITUARY
WALKING CANE
FRIED RICE
COLLECTOR'S ITEM
CORRUGATED ALUMINUM
SUNDAY FUNNIES
SILVER DOLLAR
THE GRAND CANYON
MADISON SQUARE GARDEN
THE LONDON BRIDGE
EMPIRE STATE BUILDING
THE EIFFEL TOWER
GREAT WALL OF CHINA
THE ALAMO
THE LIBERTY BELL
LINCOLN MEMORIAL
THE BERLIN WALL
HOOVER DAM
GOLDEN GATE BRIDGE
THE TAJ MAHAL
THE SWISS ALPS
GRANT'S TOMB
PIKE'S PEAK
THE OK CORRAL
THE GRAND OLE OPRY
THE PETRIFIED FOREST
NOTRE DAME CATHEDRAL
CAPE CANAVERAL
DON'T ROCK THE BOAT
ON THE UP AND UP
THE DEVIL MADE ME DO IT
THERE'S PLENTY FOR EVERYBODY
DON'T FORGET TO READ THE FINE PRINT
IT'S THE NEXT BEST THING TO BEING THERE
DON'T BE A BACK SEAT DRIVER
TIME IS MONEY
TOO MANY COOKS SPOIL THE BROTH
MANY ARE CALLED BUT FEW ARE CHOSEN
PRIDE GOETH BEFORE THE FALL
IT COMES AND GOES
IT'S ONLY THE TIP OF THE ICEBERG
FOR THE MAN WHO HAS EVERYTHING
THERE'S NO SUCH THING AS A FREE LUNCH
IT'S FOR A GOOD CAUSE
DON'T START SOMETHING YOU CAN'T FINISH
IT'S THE LAW OF THE LAND
LET SLEEPING DOGS LIE
TAKING IT EASY
DON'T BITE THE HAND THAT FEEDS YOU
LOOK BOTH WAYS BEFORE CROSSING
DON'T SPEND IT ALL IN ONE PLACE
OUT TO LUNCH
TAKE TWO ASPIRIN AND CALL ME IN THE MORNING
PERISH THE THOUGHT
YOU CAN'T SAY I DIDN'T WARN YOU
GOOD TABLE MANNERS
EVERY LITTLE BIT COUNTS
MAKING A MOUNTAIN OUT OF A MOLEHILL
THE PROOF IS IN THE PUDDING
SOME GUYS HAVE ALL THE LUCK
DON'T JUMP THE GUN
THE MEANING IS LOST IN THE TRANSLATION
IT'S JUST WATER UNDER THE BRIDGE
NOW THAT THE SHOE IS ON THE OTHER FOOT
OVERLY EXCITED
CLOSED FOR REMODELING
RIPE FOR THE PICKING
JUST WHEN YOU THOUGHT YOU'D HEARD EVERYTHING
FROM THE CRADLE TO THE GRAVE
PLAYING FOR KEEPS
MY BACK'S AGAINST THE WALL
TURN THE OTHER CHEEK
HITTING BELOW THE BELT
I'M HOLDING MY OWN
UNDER THE WEATHER
NOT ON YOUR LIFE
THERE'S SOMETHING FOR EVERYBODY
NEVER SAY NEVER
SAVE IT FOR A RAINY DAY
WITHIN A BLINK OF AN EYE
DON'T LOOK BACK
THERE'S A SUCKER BORN EVERY MINUTE
NEVER AT A LOSS FOR WORDS
LET THE GOOD TIMES ROLL
ON COMMON GROUND
TOO LITTLE TOO LATE
THIRD RATE ROMANCE
TAKEN FOR GRANTED
NOT TOO BAD UNDER THE CONDITIONS
HOPE TO SEE YOU SOON
EARN WHILE YOU LEARN
HELPFUL HINT
WINNER AND STILL CHAMPION
NOTHING BUT THE FACTS
ALL OR NOTHING
EVERY MAN FOR HIMSELF
SOMETHING FOR NOTHING
LOVE IT OR LEAVE IT
A DIAMOND IN THE ROUGH
BLOWING HOT AND COLD
OPENING UP A CAN OF WORMS
TWIDDLING YOUR THUMBS
HONESTY IS THE BEST POLICY
BURSTING AT THE SEAMS
SIGN ON THE DOTTED LINE
FLICK OF THE WRIST
A NEW BROOM SWEEPS CLEAN
WISH YOU WERE HERE
GETTING DOWN TO BRASS TACKS
NEAT AS A PIN
HIGH JINKS
THE SOONER THE BETTER
EVERYTHING BUT THE KITCHEN SINK
TAKE THE BULL BY THE HORNS
DOUBLE OR NOTHING
CHARITY BEGINS AT HOME
TAKE A BREAK
TAKE IT AS IT COMES
TOO MUCH TOO SOON
SEEING IS BELIEVING
SOMETHING HAS TO BE DONE ABOUT IT
BLOOD IS THICKER THAN WATER
BELIEVE IT OR NOT
EVERY DOG HAS ITS DAY
SEVEN COME ELEVEN
SOME THINGS ARE BETTER LEFT UNSAID
MAKE ME AN OFFER
CLOSE COVER BEFORE STRIKING
KEEP YOUR GUARD UP
NO LAUGHING MATTER
SOME PEOPLE NEVER LEARN
IT JUST DOESN'T ADD UP
BEHIND THE EIGHT BALL
DON'T COUNT ON IT
BY THE GRACE OF GOD
LEAVE IT BE
ON CLOUD NINE
UNDER THE TABLE
DON'T TAKE IT FOR GRANTED
MAYBE SO AND MAYBE NOT
AT THE CROSSROADS
TAKE IT TO THE LIMIT
OVER-THE- COUNTER
IN THE DOGHOUSE
MY TWO CENTS WORTH
OVER THE HILL
BRINGING UP THE REAR
THE STRAW THAT BROKE THE CAMEL'S BACK
COMING OF AGE
THE MORE THE MERRIER
THE LAST PLACE YOU'D THINK OF
HAPPY DAYS ARE HERE AGAIN
THE WHOLE NINE YARDS
GO TO THE HEAD OF THE CLASS
IN THE TWINKLING OF AN EYE
RETURN TO SENDER
I'VE HAD IT UP TO HERE
THE LONG AND SHORT OF IT
THE BOTTOM OF THE BARREL
HOLD THE PHONE
ON THE RAZOR'S EDGE
LET THE CHIPS FALL WHERE THEY MAY
THE WRONG SIDE OF THE TRACKS
STOP THE PRESSES
THE WORM HAS TURNED
NO USE CRYING OVER SPILLED MILK
CASH AND CARRY
CRIME DOESN'T PAY
BOY MEETS GIRL
NOTHING BUT THE BEST
THE GOLDEN RULE
ONE GOOD TURN DESERVES ANOTHER
KEEP A STIFF UPPER LIP
HE WHO LAUGHS LAST
ON THE RIGHT TRACK
SECOND TO NONE
IN THE RIGHT FRAME OF MIND
DON'T TAKE ANY WOODEN NICKELS
SO BE IT
LET'S MAKE A DAY OF IT
LOOK IT UP
THE BEST AND THE BRIGHTEST
IT'S OPEN FOR DISCUSSION
THE JOKE'S ON YOU
THE BUCK STOPS HERE
STANDING ROOM ONLY
RIGHT BETWEEN THE EYES
GONE BUT NOT FORGOTTEN
THE TIME IS NOW
THE CREAM ALWAYS RISES TO THE TOP
MY CUP RUNNETH OVER
THERE'S NO DOUBT ABOUT IT
YOU CAN BANK ON IT
OVER AND OUT
YOU CAN TAKE MY WORD ON IT
LIFE IS FOR THE LIVING
LEND ME AN EAR
LONG LIVE THE KING
THERE'S NOTHING TO IT
I CAN'T GET NO RELIEF
THE AGONY AND THE ECSTASY
PAUL REVERE'S RIDE
MAKE THE MOST OF IT
TALK IS CHEAP
SQUEAKY CLEAN
THERE'S NO EXCUSE FOR IT
ON THE BUTTON
DON'T LEAVE WITHOUT SAYING GOODBYE
YOU GO YOUR WAY AND I'LL GO MINE
ONE HAND WASHES THE OTHER
IT'S BIGGER THAN THE BOTH OF US
I'LL MEET YOU HALFWAY
DON'T CALL US WE'LL CALL YOU
DON'T BITE OFF MORE THAN YOU CAN CHEW
LOOK ME IN THE EYE AND SAY THAT
GOING FOR BROKE
BANANA SPLITS
CEILING FANS
BLUEPRINTS
TENNIS SHOES
CLING PEACHES
FINGERNAIL CLIPPERS
CHAPPED LIPS
HORSE AND BUGGY
PAIRS OF SHOES
BACON AND EGGS
MACARONI AND CHEESE
BREAD AND BUTTER
BEER AND PRETZELS
APPLES AND ORANGES
NEEDLES AND PINS
ANIMAL VEGETABLE OR MINERAL
CAT AND MOUSE
CHICKEN AND DUMPLINGS
BOWS AND ARROWS
CHEESE AND CRACKERS
HASH BROWN POTATOES
HAMMER AND NAIL
STARS AND STRIPES
PEACHES AND CREAM
CLOAK AND DAGGER
ARM AND HAMMER
PORK AND BEANS
THE EXODUS
WHITE CHRISTMAS
LIEUTENANT COLONEL
EXECUTIVE VICE- PRESIDENT
SECRETARY OF DEFENSE
SPEAKER OF THE HOUSE
BRIGADIER GENERAL
CHIEF-OF- POLICE
NATIONAL VELVET
COMMANDER- IN-CHIEF
SURGEON GENERAL
SECRETARY OF THE INTERIOR
POSTMASTER GENERAL
SERGEANT- AT-ARMS
UNCHAINED MELODY
SENATE MAJORITY WHIP
GONE WITH THE WIND
DISTRICT ATTORNEY
PRIME MINISTER
THE DAYS OF WINE AND ROSES
LOVE LETTERS IN THE SAND
NONE BUT THE BRAVE
RETURN OF THE JEDI
THE GOOD THE BAD AND THE UGLY
MOON RIVER
SOMEWHERE OVER THE RAINBOW
HEAVYWEIGHT CHAMPION
DUCHESS OF WINDSOR
WHERE EAGLES DARE
THE AFRICAN QUEEN
DIAL M FOR MURDER
THE EMPIRE STRIKES BACK
THE NAKED AND THE DEAD
BEETHOVEN'S NINTH
INSPECTOR GENERAL
THE DIRTY DOZEN
THE STING
A CLOCKWORK ORANGE
MISSION IMPOSSIBLE
THE GHOST AND MRS MUIR
MAN OF LA MANCHA
APOCALYPSE NOW
BRIDGE ON THE RIVER KWAI
THE SANDS OF IWO JIMA
THE HIGH AND THE MIGHTY
SEND IN THE CLOWNS
I DID IT MY WAY
LOVE STORY
BREAKFAST AT TIFFANY'S
THE LEGEND OF SLEEPY HOLLOW
TWINKLE TWINKLE LITTLE STAR
IF I WERE A RICH MAN
PSYCHO
A NIGHT AT THE OPERA
ATTORNEY GENERAL
BEN HUR
THE GUNS OF NAVARONE
BEAUTY AND THE BEAST
THE OLD MAN AND THE SEA
SESAME STREET
NEVER ON SUNDAY
THE GREAT GATSBY
THE SUN ALSO RISES
THE BLACKBOARD JUNGLE
OF MICE AND MEN
JINGLE BELLS
THE RISE AND FALL OF THE ROMAN EMPIRE
TOOTSIE
THE LAST DAYS OF POMPEII
MAJOR GENERAL
GENTLEMEN PREFER BLONDES
THE POSTMAN ALWAYS RINGS TWICE
THE FRENCH CONNECTION
IN COLD BLOOD
WAR AND PEACE
ANNIE HALL
THE THREE LITTLE PIGS
THE GRAPES OF WRATH
THE RED PONY
DOCTOR ZHIVAGO
THE THREE FACES OF EVE
PRIDE AND PREJUDICE
SPARTACUS
MARY POPPINS
I WANT TO HOLD YOUR HAND
FANTASIA
SNOW WHITE
SATURDAY NIGHT LIVE
CRIME AND PUNISHMENT
BONNIE AND CLYDE
PLEASE DON'T EAT THE DAISIES
HEARTBREAK HOTEL
THE LAST OF THE MOHICANS
PORGY AND BESS
THE FRONT PAGE
LOVE ME TENDER
WIDE WORLD OF SPORTS
GOODBYE MISTER CHIPS
THE ELEPHANT MAN
THE ILIAD
THE CALL OF THE WILD
SATURDAY NIGHT FEVER
FIDDLER ON THE ROOF
TENNESSEE WALTZ
PLANET OF THE APES
BLUE CROSS AND BLUE SHIELD
LION'S CLUB
COMMUNIST PARTY
UNITED NATIONS
BOY SCOUTS OF AMERICA
LITTLE LEAGUE BASEBALL
THE WRITER'S GUILD
DAUGHTERS OF THE AMERICAN REVOLUTION
UNIFIED SCHOOL DISTRICT
CIVIL LIBERTIES UNION
SCREEN ACTOR'S GUILD
NATIONAL FOOTBALL LEAGUE
THE ELK'S CLUB
AMERICAN AUTOMOBILE ASSOCIATION
RED CROSS
COMMON CAUSE
CHURCH CHOIR
GREEN BAY PACKERS
PRESIDENT'S CABINET
CHURCH OF LATTER-DAY SAINTS
NATIONAL SECURITY COUNCIL
FIRE DEPARTMENT
NATIONAL HOCKEY LEAGUE
DEMOCRATIC PARTY
PITTSBURGH PIRATES
TEXTILE WORKERS' UNION
DAIRYMEN'S ASSOCIATION
SECURITIES EXCHANGE COMMISSION
FRATERNAL ORDER OF POLICE
BETTER BUSINESS BUREAU
CONTINENTAL CONGRESS
CANADIAN MOUNTED POLICE
TEXAS RANGERS
KIWANIS CLUB
BIG BROTHERS OF AMERICA
MUSCULAR DYSTROPHY ASSOCIATION
AMERICAN LEGION
WEIGHT WATCHERS
YOUNG MEN'S CHRISTIAN ASSOCIATION
AMERICAN AIRLINES
KNIGHTS OF COLUMBUS
REPUBLICAN NATIONAL COMMITTEE
THREE DAY WEEKEND
ROSE BOWL PARADE
KENTUCKY DERBY
DINNER AT THE WHITE HOUSE
THE WORLD SERIES
GRADUATION DAY
LODGE MEETING
ELECTION DAY
STANLEY CUP PLAYOFFS
CORONATION
GROUND HOG'S DAY
THE IRISH SWEEPSTAKES
RETIREMENT PARTY
POLICEMAN'S BALL
HOMECOMING
MARDI GRAS
NEW YEAR'S EVE PARTY
TULIP FESTIVAL
ANTIQUE SHOW
INDIAN POW-WOW
SPRING VACATION
WEDDING DAY
MORTGAGE BURNING PARTY
CORPORATE MERGER
BIRTHDAY
THE OLYMPIC GAMES
COMING OUT PARTY
CAMPAIGN FUND DRIVE
LINCOLN'S BIRTHDAY
BEAUTY PAGEANT
SENIOR PROM
WIMBLEDON TENNIS TOURNAMENT
GRAND OPENING
TWO-FOR-ONE SALE
SHIP LAUNCHING
SILVER ANNIVERSARY
TOTAL ECLIPSE OF THE SUN
FIRST DATE
STATE OF THE UNION ADDRESS
MOVIE PREMIERE
BABY SHOWER
EASTER SUNDAY
THE SUPERBOWL
FIRST COMMUNION
SUNDAY SERVICES
BOSTON TEA PARTY
GOING OUT OF BUSINESS SALE
HOLLOWEEN
FAMILY REUNION
LINCOLN AND DOUGLAS DEBATE
STATE FAIR
KENTUCKY DERBY
THE CIVIL WAR
FIRST SNOWFALL
ACADEMY AWARDS
PAYDAY
THE SEASON OPENER
HANUKKAH
THE FIRST DAY OF SCHOOL
CHRISTMAS EVE
THE FIRST DAY OF SPRING
SURRENDER AT APPOMATAX
SERMON ON THE MOUNT
BABY'S FIRST TOOTH
HIGH SCHOOL REUNION
THE FRENCH REVOLUTION
FOURTH OF JULY PICNIC
THE LAST SUPPER
THE RETURN OF HALLEY'S COMET
FRATERNITY RUSH PARTY
VALENTINE'S DAY
YOM KIPPUR
THE PEACE CORPS
CHRISTENING
NORMANDY INVASION
MOON LANDING
BARN RAISING
BASTILLE DAY
WOODSTOCK
BOSTON MARATHON
CAR AUCTION
MILITARY DISCHARGE
BACHELOR PARTY
MISS UNIVERSE PAGEANT
RELIGIOUS RETREAT
SPANISH INQUISITION
PASSOVER
WATERGATE
INDIAN RAIN DANCE
WORLD CUP SOCCER MATCH
HAWAIIAN LUAU
LOUISIANA PURCHASE
THE AMERICA'S CUP RACE
VERSAILLES TREATY
FRENCH AND INDIAN WAR
TURN OF THE CENTURY
SPANISH- AMERICAN WAR
ARMED FORCES DAY
ARMISTICE DAY
MEMORIAL DAY
CHINESE NEW YEAR
REPORT CARD DAY
FIRST DAY ON THE JOB
`;


let wofFamilyAnswers=
`
ALLIGATOR ALLEY 
AMAZON JUNGLE 
ANTIOCH 
APPLE ORCHARD 
ART GALLERY 
AUTO BODY SHOP 
BADEN BADEN WEST GERMANY 
BATON ROUGE LOUISIANA 
CARTHAGE 
CENTRAL PARK 
CHERNOBYL 
CHESAPEAKE BAY 
CHILD CARE CENTER 
CLUB MED 
COLLEGE CAMPUS 
DAIRY FARM 
DEAD SEA 
DEATH VALLEY 
DES MOINES IOWA 
DRESSING ROOM 
DUBROVNIK YUGOSLAVIA 
DUDE RANCH 
EUREKA CALIFORNIA 
FARMERS MARKET 
FIJI ISLANDS 
FRANKFURT GERMANY 
FRATERNITY HOUSE 
FRONT PORCH 
FUNERAL HOME 
GOBI DESERT 
GRAND FORKS NORTH DAKOTA 
GRAND TETON NATIONAL PARK 
GREENWICH CONNECTICUT 
GUAYAQUIL ECUADOR 
HEATHROW AIRPORT 
HOME TEAM DUGOUT 
HOSPITAL RECOVERY ROOM 
INFANT NURSERY 
JEFFERSON CITY MISSOURI 
JERUSALEM 
JOHNSON SPACE CENTER 
KALAMAZOO MICHIGAN 
KOWLOON 
KUALA LUMPUR 
LA BREA TAR PITS 
LIBRARY OF CONGRESS 
LIBRARY REFERENCE ROOM 
LINCOLN MEMORIAL 
LONG ISLAND SOUND 
MAPLE LEAF GARDEN 
MATERNITY WARD 
MAUI HAWAII 
MECCA 
MEDICAL SCHOOL 
MINIATURE GOLF COURSE 
MINNEAPOLIS MINNESOTA 
MOBILE HOME PARK 
MONTERREY MEXICO 
MOUNT FUJI 
MOUNT RAINIER NATIONAL PARK 
MOVIE STUDIO BACK LOT 
MYKONOS 
NON-SMOKING SECTION 
NOTRE DAME CATHEDRAL 
NURSING HOME 
OCALA NATIONAL FOREST 
OPERATING ROOM 
ORCHESTRA PIT 
PAN- AMERICAN HIGHWAY 
PARADISE ISLAND 
PEOPLE'S REPUBLIC OF CHINA 
RACKETBALL COURT 
RALEIGH NORTH CAROLINA 
RED SQUARE 
REFRESHMENT STAND 
SAINT ANDREWS GOLF COURSE 
SAINT AUGUSTINE FLORIDA 
SAN JOSE COSTA RICA 
SANTA FE TRAIL 
SAN DIEGO ZOO 
SCHENECTADY NEW YORK 
SCHOOL CAFETERIA 
SCHOOL GYMNASIUM 
SHEA STADIUM 
SHOPPING CENTER PARKING LOT 
SIOUX FALLS SOUTH DAKOTA 
SPORTS COMPLEX 
STADIUM BLEACHERS 
STADIUM PRESSBOX 
STRAIT OF BOSPORUS 
STRATFORD ON AVON 
SUBWAY STATION 
SWEETWATER TEXAS 
SYRIA 
TEXARKANA 
THE FORBIDDEN CITY 
THE GALAPAGOS ISLANDS 
TIEN AN MEN SQUARE 
TOY DEPARTMENT 
VANCOUVER BRITISH COLUMBIA 
VENICE ITALY 
WALLA WALLA WASHINGTON 
WILMINGTON DELAWARE 
WINNIPEG MANITOBA CANADA 
YANGTZE RIVER 
YUKON NORTHWEST TERRITORY 
AEROBICS INSTRUCTOR 
ALEXANDER DUMAS 
ALEXANDER HAIG 
AN EQUAL- OPPORTUNITY EMPLOYER 
ANDREW JOHNSON 
ANDRE AGASSI 
ANIMAL TRAINER 
ARISTOCRAT 
ARMCHAIR QUARTERBACK 
ARMY BRAT 
ARSENIO HALL 
ASTRONOMER 
BENJAMIN HARRISON 
BLUES SINGER 
BOXING REFEREE 
BROOKS ROBINSON 
CAPTAIN JAMES COOK 
CARL YASTRZEMSKI 
CATHERINE DE MEDICI 
CATTLE RANCHER 
CHARLEMAGNE 
CHRISTOPHER COLUMBUS 
CONGRESSMAN 
CORBIN BERNSEN 
CRUSADER 
DANIEL WEBSTER 
DAVID GLASGOW FARRAGUT 
DEER HUNTER 
DENTAL SURGEON 
DIAN FOSSEY 
DONALD TRUMP 
DRESSMAKER 
DRUG COUNSELOR 
DR RUTH WESTHEIMER 
EGYPTIAN PHARAOH 
ELIAS HOWE 
ELIZABETH DOLE 
EL GRECO 
EMPEROR CLAUDIUS 
ERIC THE RED 
EURIPIDES 
EXPLORER 
FIRE INSPECTOR 
FRANKLIN DELANO ROOSEVELT 
GARRISON KEILLOR 
GENGHIS KHAN 
GEORGE HERMAN BABE RUTH 
GEORGE WASHINGTON 
GIAN CARLO MENOTTI 
GOSSIP COLUMNIST 
GREG LOUGANIS 
GROVER CLEVELAND ALEXANDER 
GUITAR PLAYER 
HANNIBAL 
HARRIET BEECHER STOWE 
HELEN OF TROY 
HENNY YOUNGMAN 
HENRY DAVID THOREAU 
HERSCHEL WALKER 
HIGH SCHOOL CHEERLEADER 
HISTORIAN 
HISTORY TEACHER 
HOME PLATE UMPIRE 
HOME RUN HITTER 
HONUS WAGNER 
HOTEL BUSBOY 
HUMORIST 
HYPNOTIST 
IVAN THE GREAT 
IVAN THE TERRIBLE 
JACQUES COUSTEAU 
JAMES A GARFIELD 
JAMES BUCHANAN 
JAMES WHISTLER 
JAZZ MUSICIAN 
JET SKIER 
JOAN OF ARC 
JOCKEY 
JOHN ADAMS 
JOHN PAUL JONES 
JOHN TYLER 
JON BON JOVI 
KONRAD ADENAUER 
KUBLAI KHAN 
LEONARDO DA VINCI 
LIGHTHOUSE KEEPER 
LUMBERJACK 
MAJOR LEAGUE BASEBALL PLAYER 
MANAGING EDITOR 
MANUEL NORIEGA 
MARATHON RUNNER 
MARIA VON TRAPP 
MARINE DRILL SERGEANT 
MARINE SERGEANT 
MARIO ANDRETTI 
MARTIN LUTHER 
MARY QUEEN OF SCOTS 
MARY TODD LINCOLN 
MATH TUTOR 
MATS WILANDER 
MAX VON SYDOW 
MAYNARD FERGUSON 
MEADOWLARK LEMON 
MERCHANT 
MERIWETHER LEWIS 
MISSISSIPPI RIVERBOAT GAMBLER 
MOISHE DAYAN 
MONDAY MORNING QUARTERBACK 
MOTORCYCLE COP 
MUSIC COMPOSER 
NATHANIEL HAWTHORNE 
NAVAL OFFICER 
NAVY ADMIRAL 
NEWS ANCHORMAN 
OFFENSIVE LINEMAN 
OLIVER CROMWELL 
ONCOLOGIST 
OPTICIAN 
OPTOMETRIST 
ORGAN DONOR 
PIANO PLAYER 
PIERRE SALINGER 
PIONEER 
PITCHING COACH 
PLAY BY PLAY ANNOUNCER 
PLUMBER'S APPRENTICE 
PRIVATE DETECTIVE 
PROFESSOR OF PHILOSOPHY 
PTOLEMY 
PULITZER PRIZE WINNER 
PYTHAGORAS 
QUEEN ISABELLA OF SPAIN 
QUEEN OF THE NILE 
RADIOLOGIST 
RALPH LAUREN 
ROBERTO CLEMENTE 
ROBIN GIVENS 
ROCK AND ROLL SINGER 
ROGER BACON 
ROGERS HORNSBY 
ROGER WILLIAMS 
ROYAL CANADIAN MOUNTIE 
ROY CAMPANELLA 
RUPERT MURDOCH 
RUTHERFORD B HAYES 
SACAJAWEA 
SALMAN RUSHDIE 
SAMUEL F B MORSE 
SANDY KOUFAX 
SANITATION WORKER 
SAXOPHONE PLAYER 
SCULPTOR 
SECRETARY OF STATE 
SENATE PAGE 
SHOE SALESMAN 
SPORTS COMMENTATOR 
STEPHEN DOUGLAS 
STEPHEN FOSTER 
STOOL PIGEON 
SUNDAY DRIVER 
TATTLETALE 
TED KOPPEL 
THE ARCHBISHOP OF CANTERBURY 
THIRD BASE COACH 
TREE SURGEON 
TUGBOAT CAPTAIN 
UNDERCOVER POLICEMAN 
VASCO DA GAMA 
WALT WHITMAN 
WASHINGTON IRVING 
WASHING MACHINE REPAIRMAN 
WEST POINT CADET 
WHISTLER'S MOTHER 
WILBUR WRIGHT 
WILLIAM CULLEN BRYANT 
WILLIAM MCKINLEY 
WILLIAM TECUMSEH SHERMAN 
WOLFMAN JACK 
WYNTON MARSALIS 
YASIR ARAFAT 
ADRENALIN 
ALCOHOLIC BEVERAGE 
ALKALINE BATTERY 
ANALOG QUARTZ WATCH 
APPLE CORE 
APPLE ORCHARD 
ARABIAN STALLION 
AREA RUG 
ASSEMBLY LINE 
ATTACHE CASE 
A SIX-MONTH C D 
A SWORN AFFIDAVIT 
BABY POWDER 
BATHROOM SINK 
BAYONET 
BIORHYTHM 
BIRTHDAY PRESENT 
BIRTH CERTIFICATE 
CARROT CAKE 
CHARLEY HORSE 
COLUMBIAN COFFEE 
COMPACT CAR 
CONDENSED MILK 
COPPERHEAD SNAKE 
CORDUROY JACKET 
CORMORANT 
CORNUCOPIA 
CORRECTED COPY 
COUNTERFEIT COIN 
CRABAPPLE TREE 
CRIMINAL LAW 
CRITICAL THINKING 
CROCKPOT 
CROQUET SET 
CROWBAR 
CUBAN CIGAR 
CUBIC ZIRCONIA EARRINGS 
CY YOUNG AWARD 
DESKTOP COPIER 
DIAPER SERVICE 
DOCTOR'S SCALE 
DRAWER ORGANIZER 
ELECTRONIC KEYBOARD 
ELECTRONIC SCOREBOARD 
EMPEROR MOTH 
FACSIMILE MACHINE 
FACTORY WARRANTY 
FEATURE LENGTH FILM 
FISH CROQUETTE 
FOLDING STEP STOOL 
FOLDING UMBRELLA 
FOOL'S GOLD 
FROZEN YOGURT 
FUNGO BAT 
GARBAGE DUMPSTER 
GAZEBO 
GLAZED DONUT 
GOLF CART 
GOOSE FEATHER PILLOW 
GRANNY SMITH APPLE 
HAND GRENADE 
HEARING DISORDER 
HOME ADDRESS 
HOME MORTGAGE 
HUMIDIFIER 
HURRICANE 
HYDROGEN PEROXIDE 
HYGROMETER 
ICEBERG 
ICEBOX 
ICHTHYOLOGY 
JEWELRY BOX 
KEY LIME PIE 
LASER BEAM SURGERY 
LAWN SPRINKLER 
LIBERTY BELL 
LIFE INSURANCE POLICY 
MATERNITY DRESS 
MEDIUM- RANGE MISSILE 
MILK CONTAINER 
MURIATIC ACID 
NOBEL PEACE PRIZE 
NUCLEAR REACTOR 
OPOSSUM 
OPTICAL ILLUSION 
ORANGE JUICE 
ORDINAL NUMBER 
ORGAN BANK 
PERSIAN RUG 
PHOTO ALBUM 
WATER PITCHER 
POCKET KNIFE 
POISONOUS SNAKE 
POLKA- DOT BIKINI 
POPCORN POPPER 
PRAIRIE DOG 
PSEUDONYM 
PULSE RATE 
QUARTZ ALARM CLOCK 
QUICKSAND 
RADAR DETECTOR 
REFERENCE BOOK 
ROAST PORK FRIED RICE 
ROSETTA STONE 
RUBBING ALCOHOL 
RUM FACTORY 
SAMOVAR 
SANDY BEACH 
SAPPHIRE BRACELET 
SATELLITE DISH 
SATYR 
SAUNA BATH 
SAVINGS ACCOUNT 
SAWDUST 
SAWHORSE 
SAXOPHONE 
SHOESTRING CATCH 
SLEEPING BAG 
SOLAR- POWERED CALCULATOR 
SOMERSAULT 
STEAK SAUCE 
STEALTH BOMBER 
STEAM- SPRAY- DRY IRON 
SWIVEL CHAIR 
SWORD SCABBARD 
TACKLE BOX 
THE OTTOMAN EMPIRE 
THE SPHINX 
TOUCHDOWN RUN 
TOW TRUCK 
TRACK HURDLE 
TWIST-OFF CAP 
UNDERWATER CAMERA 
UPRIGHT FREEZER 
VACUUM BOTTLE 
VAMPIRE BAT 
VAULTING HORSE 
VISITING TEAM DUGOUT 
VOGUE MAGAZINE 
WESTERN OMELET 
WIDE-ANGLE BINOCULARS 
ARCHIE BUNKER 
B L STRYKER 
BABAR THE ELEPHANT 
BARNABY JONES 
BARNEY MILLER 
BECKY THATCHER 
BOSTON BLACKIE 
BUCK ROGERS 
CALAMITY JANE 
CAPTAIN KANGAROO 
CLUBBER LANG 
DADDY WARBUCKS 
DAISY MILLER 
DOCTOR KILDARE 
DAGWOOD BUMSTEAD 
DON QUIXOTE 
ELIZA DOOLITTLE 
FLASH GORDON 
FLETCHER CHRISTIAN 
FOGHORN LEGHORN 
HAGAR THE HORRIBLE 
HOPALONG CASSIDY 
INSPECTOR GADGET 
INSPECTOR JACQUES CLOUSEAU 
JACOB MARLEY 
JEAN VALJEAN 
JOE PALOOKA 
JOE THE BARTENDER 
LEX LUTHOR 
LITTLE ORPHAN ANNIE 
LUCY RICARDO 
MANDRAKE THE MAGICIAN 
MARCUS WELBY 
MARMADUKE 
MISS JANE MARPLE 
MISS MONEYPENNY 
MR BELVEDERE 
OLD KING COLE 
PERCY DOVETONSILS 
POSEIDON 
PRINCE VALIANT 
PROFESSOR HENRY HIGGINS 
PROFESSOR MORIARTY 
PUNKY BREWSTER 
QUASIMODO 
RALPH KRAMDEN 
REMINGTON STEELE 
ROCKY BALBOA 
ROGER RABBIT 
SERGEANT JOE FRIDAY 
SLAP MAXWELL 
SUZIE WONG 
THE GRINCH 
THE JOLLY GREEN GIANT 
THE LONE RANGER 
TRAPPER JOHN 
TUGBOAT ANNIE 
A BLAST FROM THE PAST 
A BREATH OF FRESH AIR 
A CHEATER NEVER WINS 
A CHIP OFF THE OLD BLOCK 
A CLEAN BILL OF HEALTH 
A COWARD DIES A THOUSAND TIMES 
A DIRTY LOW-DOWN TRICK 
A LARGER THAN LIFE ROLE 
A LONG BOMB FOR A TOUCHDOWN 
A LUCKY DAY 
A LUST FOR LIFE 
A PENNY SAVED IS A PENNY EARNED 
A SNAKE IN THE GRASS 
A STANDING ROOM ONLY AUDIENCE 
A TRIED AND TRUE METHOD 
A WASTE OF TIME AND ENERGY 
A WATERED- DOWN VERSION 
ADVANCE AND BE RECOGNIZED 
ADVICE TO THE LOVELORN 
ALL WORK GUARANTEED 
AN ACCIDENT WAITING TO HAPPEN 
SITTING ON TOP OF THE WORLD 
A DEATH- DEFYING STUNT 
A GENTLEMAN'S AGREEMENT 
A HOMETOWN CROWD 
A SNEAKING SUSPICION 
A SYMPATHETIC EAR 
A TOURNAMENT OF CHAMPIONS 
BACKFIELD IN MOTION 
BAPTISM UNDER FIRE 
BASEBALL RHUBARB 
BEAUTY IS IN THE EYE OF THE BEHOLDER 
BEAUTY IS SKIN DEEP 
BEING LED DOWN THE GARDEN PATH 
BLIND AS A BAT 
BLONDES HAVE MORE FUN 
BROTHER CAN YOU SPARE A DIME 
BUY THREE AND GET ONE FREE 
CAT GOT YOUR TONGUE 
CLEAN UP AFTER YOURSELF 
CLEAN AS A WHISTLE 
COLD HARD CASH 
COME BACK TO REALITY 
COURT IS ADJOURNED 
CRYING CROCODILE TEARS 
DON'T BET YOUR LIFE ON IT 
DON'T CRY OVER SPILT MILK 
DON'T MAKE A MONKEY OUT OF ME 
DOUBLE YOUR PLEASURE 
DOWN AND OUT 
DOWN FOR THE COUNT 
DOWN IN THE MOUTH 
DOWN IN THE DUMPS 
DRESS FOR SUCCESS 
EATING ON THE RUN 
FAMOUS LAST WORDS 
FIGHT FIRE WITH FIRE 
FIRST AND GOAL TO GO 
FLOATING A LOAN 
FOOTLOOSE AND FANCY FREE 
FOREVER YOUNG IN HEART 
FOR BETTER OR FOR WORSE 
FOURTH DOWN AND INCHES 
GETTING AHEAD IN THE WORLD 
GETTING BOGGED DOWN 
GETTING PAID BACK IN SPADES 
GIVE ME YOUR ATTENTION PLEASE 
GO HOME AND SLEEP ON IT 
GO OUT IN A BLAZE OF GLORY 
GO WITH THE FLOW 
GOING BUST 
GOING OUT OF BUSINESS SALE 
GRABBING A BITE TO EAT 
GROUNDS FOR DIVORCE 
HANG IN THERE 
HE WHO LAUGHS LAST LAUGHS BEST 
HEAVEN HELP US 
HOME IS WHERE THE HEART IS 
I CANNOT TELL A LIE 
I TOLD YOU SO 
INTO EVERY LIFE SOME RAIN MUST FALL 
IN A STATE OF PANIC 
IN OVER MY HEAD 
IT SENT CHILLS DOWN MY SPINE 
IT'S A PLEASURE TO KNOW YOU 
IT'S A LIVING 
I'M READY FOR ANYTHING 
I'VE GOT GOOD NEWS AND BAD NEWS 
JUST TAKE IT NICE AND EASY 
KEEP YOUR EYES PEELED 
KNOCK ON WOOD 
LAST BUT NOT LEAST 
LEARN FROM YOUR MISTAKES 
LEARN TO PLAY THE GAME 
LET'S GO METS 
LIVE AND LET LIVE 
LIVING BEYOND YOUR MEANS 
MARRYING ON THE REBOUND 
MEALS ON WHEELS 
MONEY IS THE ROOT OF ALL EVIL 
MONEY CAN'T BUY HAPPINESS 
NECESSITY IS THE MOTHER OF INVENTION 
NEVER A DULL MOMENT 
NEVER LOOK BACK 
NICE GUYS FINISH LAST 
NO PLACE TO GO BUT UP 
NOT WORTH A PLUG NICKEL 
NOTHING VENTURED NOTHING GAINED 
OLD ENOUGH TO KNOW BETTER 
ONE OF LIFE'S LITTLE BLESSINGS 
ONE PICTURE IS WORTH A THOUSAND WORDS 
ONLY TIME WILL TELL 
OPEN DOOR TRADE POLICY 
OPPORTUNITY KNOCKS 
ORDEAL BY FIRE 
ORDER IN THE COURT 
OVERCOMING ADVERSITY 
PASS BY THE SKIN OF YOUR TEETH 
PASS WITH FLYING COLORS 
PAY IN ADVANCE 
PHONY AS A TWO-DOLLAR BILL 
PLAYING IT BY EAR 
PLAYING POSSUM 
PLAYING THE DEVIL'S ADVOCATE 
POSITIVE FEEDBACK 
PUT UP OR SHUT UP 
PUTTING YOUR CARDS ON THE TABLE 
READY WILLING AND ABLE 
ROTTEN TO THE CORE 
RUNNING FOR COVER 
RUNNING ON EMPTY 
SEALED WITH A KISS 
SEVENTH- INNING STRETCH 
SICK AS A DOG 
SOME FOOD FOR THOUGHT 
SOMETHING SMELLS FISHY HERE 
STAND UP AND BE COUNTED 
STAND UP FOR YOUR RIGHTS 
STAND AT ATTENTION 
STAND BY YOUR MAN 
STARTING FROM SCRATCH 
START WITH A CLEAN SLATE 
STILL WATERS RUN DEEP 
STUCK IN A RUT 
SURVIVAL OF THE FITTEST 
TAKE IT ONE DAY AT A TIME 
TAKE A DEEP BREATH 
TALKING THROUGH YOUR HAT 
TELL IT TO THE MARINES 
THAT WAS A CLOSE CALL 
THAT'S SO FUNNY I FORGOT TO LAUGH 
THAT'S A TALL ORDER 
THAT'S MUSIC TO MY EARS 
THE AGONY OF DEFEAT 
THE APPLE OF HIS EYE 
THE BRAVE ONLY DIE ONCE 
THE CHECK IS IN THE MAIL 
THE END JUSTIFIES THE MEANS 
THE FLESH IS WEAK 
THE STAR OF THE SHOW 
THE VOICE OF DOOM 
THE GREEN GRASS OF HOME 
THE LOVE OF MY LIFE 
THE ORDER OF THE DAY 
THE PERFECT COUPLE 
THE VOICE OF AN ANGEL 
THE WHOLE WORLD IS A STAGE 
THIS WON'T HURT A BIT 
THREE STRIKES AND YOU'RE OUT 
TIME HEALS ALL WOUNDS 
TOO CLOSE TO CALL 
TRUTH IS STRANGER THAN FICTION 
WAKE UP AND SMELL THE COFFEE 
WHEN I TALK YOU JUMP 
YOU ARE WHAT YOU EAT 
YOU CAN'T CHEAT AN HONEST MAN 
YOU DESERVE A BREAK TODAY 
YOU GOTTA BELIEVE 
A BELL FOR ADANO 
A MAN FOR ALL SEASONS 
A TALE OF TWO CITIES 
ALL MY CHILDREN 
ALL QUIET ON THE WESTERN FRONT 
ALL IN THE FAMILY 
ALL'S WELL THAT ENDS WELL 
AMERICAN GRAFFITI 
ANNIE GET YOUR GUN 
ANTONY AND CLEOPATRA 
AROUND THE WORLD IN EIGHTY DAYS 
ARROWSMITH 
ARSENIC AND OLD LACE 
AS YOU LIKE IT 
A CURRENT AFFAIR 
A STREETCAR NAMED DESIRE 
BANG THE DRUM SLOWLY 
BAREFOOT IN THE PARK 
BORN YESTERDAY 
CACTUS FLOWER 
CAPTAINS COURAGEOUS 
CAROUSEL 
CASABLANCA 
CASINO ROYALE 
CAT BALLOU 
CAT ON A HOT TIN ROOF 
CHARLOTTE'S WEB 
CRIME AND PUNISHMENT 
DAMN YANKEES 
DAVID COPPERFIELD 
DEAD POETS SOCIETY 
DON'T GO NEAR THE WATER 
DOONESBURY 
DR JEKYLL AND MR HYDE 
FAR FROM THE MADDING CROWD 
FROM HERE TO ETERNITY 
FROM RUSSIA WITH LOVE 
FULL METAL JACKET 
GUESS WHO'S COMING TO DINNER 
GULLIVER'S TRAVELS 
GUYS AND DOLLS 
HARVEY 
HELLO DOLLY 
HIGH PLAINS DRIFTER 
HOW THE CAMEL GOT ITS HUMP 
HOW THE RHINOCEROS GOT ITS SKIN 
HOW GREEN WAS MY VALLEY 
HOW THE WEST WAS WON 
HUCKLEBERRY FINN 
IN THE HEAT OF THE NIGHT 
INDIANA JONES AND THE LAST CRUSADE 
INHERIT THE WIND 
IRMA LA DOUCE 
ISLAND OF THE BLUE DOLPHINS 
IT'S A MAD MAD MAD MAD WORLD 
JONATHAN LIVINGSTON SEAGULL 
LADY AND THE TRAMP 
LAST TANGO IN PARIS 
LES MISERABLES 
LIFE WITH FATHER 
LONG DAY'S JOURNEY INTO NIGHT 
LOOK HOMEWARD ANGEL 
LOST HORIZON 
MARJORIE MORNINGSTAR 
MARRIED TO THE MOB 
MIDNIGHT COWBOY 
MURDERS IN THE RUE MORGUE 
MY FAIR LADY 
MY SISTER EILEEN 
NO TIME FOR SERGEANTS 
NOT NECESSARILY THE NEWS 
ON THE WATERFRONT 
PAJAMA GAME 
PAPER MOON 
PEYTON PLACE 
PHANTOM OF THE OPERA 
PLANET OF THE APES 
PORTNOY'S COMPLAINT 
ROMEO AND JULIET 
ROSEMARY'S BABY 
SANFORD AND SON 
SERGEANT YORK 
SHANE 
SHENANDOAH 
SHIP OF FOOLS 
SOYLENT GREEN 
STAGECOACH 
SWAN LAKE 
TAKE ME OUT TO THE BALL GAME 
TALES OF THE SOUTH PACIFIC 
TEAHOUSE OF THE AUGUST MOON 
THAT TOUCH OF MINK 
THE BELLS ARE RINGING 
THE BRIDGE ON THE RIVER KWAI 
THE CASK OF AMONTILLADO 
THE DIARY OF ANNE FRANK 
THE DAY OF THE JACKAL 
THE FALL OF THE HOUSE OF USHER 
THE FOUR HORSEMEN OF THE APOCALYPSE 
THE LIFE AND DEATH OF KING JOHN 
THE LION IN WINTER 
THE MARY TYLER MOORE SHOW 
THE MASQUE OF THE RED DEATH 
THE PIT AND THE PENDULUM 
THE PRINCE AND THE PAUPER 
THE RED BADGE OF COURAGE 
THE SOUND OF MUSIC 
THE SPY WHO CAME IN FROM THE COLD 
THE VICAR OF WAKEFIELD 
THE YOUNG AND THE RESTLESS 
THE SUBJECT WAS ROSES 
THE AGONY AND THE ECSTASY 
THE ARRANGEMENT 
THE BEST YEARS OF OUR LIVES 
THE BLACK CAT 
THE BRIDGE OF SAN LUIS REY 
THE BROTHERS KARAMAZOV 
THE CAINE MUTINY 
THE CAROL BURNETT SHOW 
THE COMEDY OF ERRORS 
THE CRUCIBLE 
THE DICK VAN DYKE SHOW 
THE GRADUATE 
THE GREATEST SHOW ON EARTH 
THE GREAT WHITE HOPE 
THE GREEN BERETS 
THE HOUSE OF THE SEVEN GABLES 
THE HUNCHBACK OF NOTRE DAME 
THE KEYS OF THE KINGDOM 
THE LIGHT THAT FAILED 
THE LONGEST DAY 
THE MERCHANT OF VENICE 
THE MIKADO 
THE MIRACLE OF THE BELLS 
THE MONKEY'S PAW 
THE ODESSA FILE 
THE OUTSIDERS 
THE PARENT TRAP 
THE PARTRIDGE FAMILY 
THE PATHFINDER 
THE PICTURE OF DORIAN GRAY 
THE POSEIDON ADVENTURE 
THE PRISONER OF ZENDA 
THE SAND PEBBLES 
THE SATANIC VERSES 
THE SECRET GARDEN 
THE SEVEN YEAR ITCH 
THE SHAGGY DOG 
THE SHOES OF THE FISHERMAN 
THE SONG OF BERNADETTE 
THE SWISS FAMILY ROBINSON 
THE TAMING OF THE SHREW 
THE THREE MUSKETEERS 
THE UNSINKABLE MOLLY BROWN 
THIRTY SOMETHING 
THOROUGHLY MODERN MILLIE 
THUNDERBALL 
TO KILL A MOCKINGBIRD 
TO SIR WITH LOVE 
TREASURE ISLAND 
TREASURE OF SIERRA MADRE 
TROILUS AND CRESSIDA 
TWO GENTLEMEN OF VERONA 
UPSTAIRS DOWNSTAIRS 
VALLEY OF THE DOLLS 
WEBSTER'S NEW WORLD LARGE PRINT DICTIONARY 
WHAT'S NEW PUSSYCAT 
WHO'S AFRAID OF VIRGINIA WOOLF 
WUTHERING HEIGHTS 
YANKEE DOODLE DANDY 
YOU CAN'T DO THAT ON TELEVISION 
YOU CAN'T TAKE IT WITH YOU 
YOU ONLY LIVE TWICE 
YOU'RE A GOOD MAN CHARLIE BROWN 
ACCOUNTING FIRM 
AIR RAID WARDENS 
AMERICAN LEAGUE ALL-STAR TEAM 
BOLSHOI BALLET 
BOSOM BUDDIES 
BOSTON POPS ORCHESTRA 
CANDY- STRIPER VOLUNTEERS 
CHAMBER OF COMMERCE 
CHILD STUDY TEAM 
CITY COUNCIL 
CUBAN EXILES 
FOREIGN INVESTORS 
GAME SHOW CONTESTANTS 
GRADUATING CLASS 
GREGG ALLMAN BAND 
HOUSE OF COMMONS 
INNOCENT BYSTANDERS 
KNIGHTS OF THE ROUND TABLE 
LITTLE LEAGUE CHAMPIONS 
LONDON BOBBIES 
LOTTERY WINNERS 
MARINE PATROL 
PHILISTINES 
POWER SQUADRON 
PYGMIES 
RADIO CITY MUSIC HALL ROCKETTES 
ROMULUS AND REMUS 
ROOKIE COPS 
SALVATION ARMY SANTAS 
SAMSON AND DELILAH 
SPYRO GYRA 
SUPREME COURT JUSTICES 
SWAT TEAM 
SYMPHONY ORCHESTRA 
TAXICAB DRIVERS 
TEAMSTERS UNION MEMBERS 
THE BLUE ANGELS 
THE DALLAS COWBOYS 
THE DIRTY DOZEN BRASS BAND 
THE FLORIDA STATE SEMINOLES 
THE LITTLE RASCALS 
THE MIAMI HEAT 
THE MONKEES 
THE OKLAHOMA SOONERS 
THE PRESIDENT'S CABINET 
VISIGOTHS 
WORLD CLASS WRESTLERS 
A ROYAL CORONATION 
AFTERNOON NAP 
AMERICAN KENNEL CLUB DOG SHOW 
BATTLE OF THE BULGE 
BAY OF PIGS INVASION 
BRIDAL SHOWER 
CANNES FILM FESTIVAL 
EXXON VALDEZ OIL SPILL 
FOOTBALL HALFTIME SHOW 
JANUARY WHITE SALE 
LOTTERY DRAWING 
MILITARY COURT MARTIAL 
MUSCULAR DYSTROPHY TELETHON 
NATIONAL SPELLING BEE CONTEST 
ORGAN TRANSPLANT SURGERY 
PIE-EATING CONTEST 
RIBBON- CUTTING CEREMONY 
SALZBURG MUSIC FESTIVAL 
SECRETARIES DAY 
SPRING BREAK 
SWEET SIXTEEN PARTY 
TAKING THE BAR EXAM 
THE ALLIED INVASION OF ANZIO 
THE DARK AGES 
THE AMERICAN REVOLUTION 
THE COLLEGE WORLD SERIES 
THE JUNIOR OLYMPICS 
THE ORANGE BOWL FESTIVAL 
THE SIEGE OF LENINGRAD 
THE SPANISH CIVIL WAR 
THE TROJAN WAR 
TOURNAMENT OF ROSES PARADE 
TUPPERWARE PARTY 
UNASSISTED DOUBLE-PLAY 
WEDDING ANNIVERSARY 
ADAM MAE AND JERRY WEST 
ADLAI AND ROBERT LOUIS STEVENSON 
AGNES AND CECIL B DE MILLE 
AMY AND WASHINGTON IRVING 
ANDREW AND GIG YOUNG 
ANDREW JACK AND LYNDON JOHNSON 
ANDY HANK AND JO BETH WILLIAMS 
ANTHONY AND DAN QUAYLE 
ANTHONY MIRIAM AND HARRY HOPKINS 
ARETHA AND BENJAMIN FRANKLIN 
ARNOLD AND LILY PALMER 
ARTHUR GLENN AND BARNEY MILLER 
ARTIE AND GEORGE BERNARD SHAW 
BARBARA AND JOHANN SEBASTIAN BACH 
BARRY ANNIE AND JOHN L SULLIVAN 
ARTHUR BENNY AND BUNKER HILL 
BETSY AND DIANA ROSS 
BILLY AND DEAN MARTIN 
BOB AND JOANNE WOODWARD 
BOOG AND DICK POWELL 
BROOKLYN LONDON AND LLOYD BRIDGES 
BUDDY AND RICHIE RICH 
BUTCH AND SHAWN CASSIDY 
BUTTERFLY AND STEVE MCQUEEN 
CAPE AND LITTLE BIG HORN 
CAROLE ALAN AND STEPHEN KING 
CHARLIE AND HELEN KELLER 
CHIC ALAN AND ROLAND YOUNG 
CHRISTINE AND RUBY KEELER 
CHRISTOPHER AND PHILIP MARLOWE 
CLIFTON AND JACK WEBB 
DANIEL PAT AND RICHARD BOONE 
DEBBIE AND R J REYNOLDS 
DICK AND RAMSEY CLARK 
DR BENJAMIN AND MR SPOCK 
DUCHESS OF AND CLARK KENT 
DUSTIN AND ABBIE HOFFMAN 
EDWARD G JACKIE AND MRS ROBINSON 
ELIZABETH AND EVE ARDEN 
ELMO AND ABRAHAM LINCOLN 
ERSKINE AND TAYLOR CALDWELL 
ESTHER TED AND BILLY DEE WILLIAMS 
EVANGELINE AND EDWIN BOOTH 
F LEE AND BEETLE BAILEY 
FAYE AND RALPH WALDO EMERSON 
FORREST AND SOPHIE TUCKER 
GARRY AND PIERRE TRUDEAU 
GENE AND THORTON WILDER 
GEORGE ARTHUR AND ROSE KENNEDY 
GEORGE AND T S ELIOT 
GEORGE BERNARD AND ROBERT SHAW 
GEORGE HENRY AND IRVING WALLACE 
GINGER BUCK AND BUDDY ROGERS 
GORGEOUS AND BOY GEORGE 
GROVER CLEVELAND AND BRANDY ALEXANDER 
GYPSY ROSE BRUCE AND ROBERT E LEE 
HARRISON GERALD AND MODEL T FORD 
HAROLD NANCY AND WOODROW WILSON 
HARRY AND JESSIE JAMES 
HAYLEY AND GENERAL MILLS 
HELEN GURLEY AND CHARLIE BROWN 
HUGH AND CHURCHILL DOWNS 
IAN AND RHONDA FLEMING 
INDIANA TOM AND GRACE JONES 
ISAAC AND BILL STERN 
JACKIE WALKER AND GORDON COOPER 
JACK JOHNNY AND KIT CARSON 
JACLYN KATE AND JOHN SMITH 
JAMES LES AND JIMMY BROWN 
JAMES AND CARROLL BAKER 
JAMES AND VAUGHAN MONROE 
JAY AND ELLIOTT GOULD 
JEANETTE ROSS AND OLD MACDONALD 
JERRY SHARI AND JOHN L LEWIS 
JIMMY JACK AND LINDA CARTER 
JODIE AND STEPHEN FOSTER 
JOHN CAMERON AND PATRICK SWAYZE 
JOSEPH AND CHARLIE MCCARTHY 
JOSEPH AND WILLIAM CONRAD 
JOE AND ROY CAMPANELLA 
JULIE AND MAXINE ANDREWS 
KAREN AND SCOTT CARPENTER 
KATE GLENDA AND STONEWALL JACKSON 
KIRK MIKE AND WILLIAM O DOUGLAS 
LARRY AND BIG BIRD 
LEONARD AND CARL BERNSTEIN 
LE VAR AND RICHARD BURTON 
LEVI AND PETER STRAUSS 
LILLIAN AND PHILIP ROTH 
LONI JACK AND MAXWELL ANDERSON 
LORETTA GIG AND CY YOUNG 
MARIA AND CHARLIE CALLAS 
MARLO TERRY AND ISIAH THOMAS 
MARNI AND RICHARD NIXON 
MARY AND RICHARD TODD 
MEL AND MONT BLANC 
MEL AND OUR MISS BROOKS 
MICHAEL J AND TWENTIETH CENTURY FOX 
MICHAEL SERGEANT AND DUKE OF YORK 
NEIL AND BASEBALL DIAMOND 
NEIL AND JACK ARMSTRONG 
NEVILLE AND WILT CHAMBERLAIN 
NIPSEY AND KURT RUSSELL 
NOLAN AND ROBERT RYAN 
NORMAN AND GEORGE LINCOLN ROCKWELL 
O J AND WALLIS WARFIELD SIMPSON 
OMAR AND BILL BRADLEY 
ORAL AND MR ROBERTS 
ORSON AND H G WELLES 
ROBERT PETER AND NATHANIEL BENCHLEY 
PETER AND EMIL JENNINGS 
QUICK DRAW TUG AND ALI MC GRAW 
RAYMOND AND AARON BURR 
REX AND GEORGE HARRISON 
RICHARD AND FORT DIX 
RICKY AND BABY FACE NELSON 
RINGO BRENDA AND KAY STARR 
ROBERT AND GEORGE BURNS 
ROCK AND HENRY HUDSON 
RUTHERFORD AND GABBY HAYES 
SALLY MARSHALL AND SOLDIER FIELD 
SARAH AND ROBERT VAUGHN 
SHELLEY AND JONATHAN WINTERS 
SIGOURNEY DENNIS AND PAT WEAVER 
SINCLAIR AND JERRY LEE LEWIS 
SIR WALTER AND GEORGE C SCOTT 
SANDRA DAY DONALD AND CARROLL O'CONNOR 
SPENCER AND DICK TRACY 
THELMA AND TEX RITTER 
THEODORE SANFORD AND BETTY WHITE 
THURGOOD AND E G MARSHALL 
TONY AND JOAN BENNETT 
VERONICA ARTHUR AND GREAT SALT LAKE 
VINCENT AND LEONTYNE PRICE 
WALDO AND CLAUDE PEPPER 
WALT GENE AND GRACE KELLY 
WHOOPI AND RUBE GOLDBERG 
WILLIAM AMANDA AND ROBERT BLAKE 
WOODY MARTY AND ETHAN ALLEN 
ASTEROIDS 
ATOMIC SUBMARINES 
BAR AND DUMBBELL SET 
CARPENTER ANTS 
CARVING KNIVES 
COMPUTER CHIPS 
DOMINOES 
ICE SKATES 
INDEX CARDS 
JOYSTICKS 
LIBRARY BOOKS 
LYMPH NODES 
MATH PROBLEMS 
METEORITES 
MEZZANINE SEATS 
MONTHLY BILLS 
MOSQUITOES 
NAUTILUS EQUIPMENT 
PARALLEL BARS 
RUFFLED CURTAINS 
SCIENCE EXPERIMENTS 
SOCIAL SECURITY BENEFITS 
STORM CLOUDS 
TAX REFUND CHECKS 
THIRD- DEGREE BURNS 
UNDERWATER GOGGLES 
VIDEO CASSETTE RECORDERS 
WANTED POSTERS 
WATER SKIS 
FOREIGN FILMS 
OLD NEWSPAPERS 
GARDEN WEEDS 
GUERNSEY COWS
`;

let wofJuniorAnswers=
`
CLOSE CAPTIONED 
PARACHUTE 
BOARD OF HEALTH 
AUTOGRAPH BOOK 
YANKEE DOODLE DANDY 
ONLY YOU CAN PREVENT FOREST FIRES 
BUBBLE GUM 
THE ALLMAN BROTHERS 
STOMACH ACHE 
DAVID COPPERFIELD 
TABLE OF CONTENTS 
BACK TO THE FUTURE 
HARTFORD CONNECTICUT 
HOT FUDGE SUNDAE 
HOT BUTTERED POPCORN 
HAWAIIAN ISLANDS 
MISS PIGGY 
NEW ZEALAND 
BOZO THE CLOWN 
EYEWITNESS 
THE CHIPMUNKS 
FLAT TIRE 
LINE OF SCRIMMAGE 
STEPPING- STONE 
COUNTERFEIT MONEY 
PLANET OF THE APES 
JUMPING JACK 
NATIONAL ANTHEM 
BATHING SUIT 
WHOLE NUMBER 
FIREHOUSE 
SELF- CLEANING OVEN 
PAPA SMURF 
BUMPER STICKER 
SUNGLASSES 
HOT DOG 
IN THE DOGHOUSE 
PACIFIC OCEAN 
SOLAR ECLIPSE 
BUGS BUNNY 
MY TWO CENTS WORTH 
TENNIS INSTRUCTOR 
PITCH A TENT 
CHARLIE BROWN 
SNOW WHITE 
I CANNOT TELL A LIE 
HORSESHOES 
SURF'S UP 
ORANGE JUICE 
THE THREE WISE MEN 
REAR-VIEW MIRROR 
TINA TURNER 
MILK AND COOKIES 
ROMAN NUMERAL 
OCTOPUS 
CLASSROOM 
TELEPHONE DIRECTORY 
KITCHEN TABLE 
CATERPILLAR 
FOLLOW THE LEADER 
AQUALUNG 
CASH REGISTER 
BOWLING ALLEY 
QUOTATION MARKS 
TWINKLE TWINKLE LITTLE STAR 
DUBLIN IRELAND 
MONEY ORDER 
SWIMMING POOL 
TOMATO JUICE 
TO THE ENDS OF THE EARTH 
THE PRINCIPAL'S OFFICE 
DEATH VALLEY 
PIN THE TAIL ON THE DONKEY 
COLLEGE PROFESSOR 
MISSISSIPPI RIVER 
STORE MANAGER 
THE GRAND CANYON 
BETTY BOOP 
BASEBALL CARDS 
CREDIT CARD 
SACRAMENTO CALIFORNIA 
PENCILS 
TURKEY DRUMSTICK 
ENGAGEMENT RING 
SPIDERMAN 
JERRY LEWIS 
AQUARIUM 
BASE HIT 
PING PONG TABLE 
SHOOTING STAR 
BOY SCOUTS OF AMERICA 
FRENCH FRIES 
CHICKEN AND DUMPLINGS 
BACON AND EGGS 
FAST-FOOD RESTAURANT 
HAPPY NEW YEAR 
EAGER BEAVER 
SALTED PRETZELS 
FLEA MARKET 
WYNKEN BLYNKEN AND NOD 
OUT OF BREATH 
FORTUNE COOKIE 
MAY THE FORCE BE WITH YOU 
YELLOWSTONE NATIONAL PARK 
POISON IVY 
KING KONG 
KNIGHT RIDER 
WITH LIBERTY AND JUSTICE FOR ALL 
SLEEP-AWAY CAMP 
MIDGET FOOTBALL TEAM 
MILK OF MAGNESIA 
HIGH SCHOOL DIPLOMA 
TOM SAWYER 
SCHOOL BUS 
BILLY JOEL 
WATCHDOG 
VANNA WHITE 
DOWN TO EARTH 
SO FAR SO GOOD 
TARZAN KING OF THE JUNGLE 
DOG COLLAR 
HOW'S IT GOING 
A WEALTH OF INFORMATION 
MONDAY NIGHT FOOTBALL 
IT'S A SMALL WORLD 
SILENT PARTNER 
CATCH A COLD 
SUGAR RAY LEONARD 
BOOBY PRIZE 
SCRABBLE 
HAM AND CHEESE SANDWICH 
BUCKLE UP FOR SAFETY 
SHOULDER HOLSTER 
CABBAGE PATCH DOLL 
DINOSAURS 
ABNER DOUBLEDAY 
PERFECT STRANGERS 
PEPPERMINT LIFE SAVERS 
HELP WANTED 
TAXICAB DRIVER 
MODEL AIRPLANE 
PUT THE FROSTING ON THE CAKE 
ALARM CLOCK 
SPRING AND MATTRESS 
THE GOONIES 
GUINNESS BOOK OF WORLD RECORDS 
DIESEL ENGINE 
ELECTRIC GUITAR 
DON JOHNSON 
SYLVESTER STALLONE 
BILL OF RIGHTS 
DEAD-END STREET 
POPEYE THE SAILOR MAN 
PRACTICAL JOKE 
THE STAR- SPANGLED BANNER 
SAINT BERNARD DOG 
FOUR-LEAF CLOVER 
THE SOUND OF MUSIC 
BOARDING SCHOOL 
THIRD BASE UMPIRE 
SUMMER VACATION 
DOWN ESCALATOR 
DEPOSIT SLIP 
PEANUT BUTTER AND JELLY SANDWICH 
RAMBO 
WISDOM TOOTH 
CAPE CANAVERAL 
KERMIT THE FROG 
COUNT DRACULA 
BOZO THE CLOWN 
BLACK AND BLUE MARK 
LIGHTNING BUG 
PAUL BUNYAN 
LOSE ONE'S TEMPER 
A DIME A DOZEN 
YOGI BERRA 
RIP VAN WINKLE 
LITTLE TOMMY TUCKER 
ALL ABOARD 
AROUND THE CLOCK 
THE WUZZLES 
POTATO CHIPS 
PIGGY BANK 
EXPLORER 
BOOMERANG 
BIRTHDAY PARTY 
GUIDANCE COUNSELOR 
FAMILY TIES 
MIAMI DOLPHINS 
DOG CATCHER 
I HEARD IT THROUGH THE GRAPEVINE 
THERMOS BOTTLE 
HANG IN THERE 
SUPERMARKET 
AMUSEMENT PARK 
THE FIRST DAY OF SCHOOL 
ADAM'S APPLE 
THE BAD NEWS BEARS 
THE FARMER IN THE DELL 
PICK-UP TRUCK 
DONALD DUCK 
NEW YEAR'S RESOLUTION 
TUNA FISH SANDWICH 
PUMPKIN PIE 
GUMBY AND POKEY 
THE FACTS OF LIFE 
PLUMBER 
FLUORESCENT LIGHT 
STRAWBERRY ICE CREAM 
FISHING ROD 
CASPER THE FRIENDLY GHOST 
FINDERS KEEPERS LOSERS WEEPERS 
PICKPOCKET 
KENTUCKY FRIED CHICKEN 
THE THREE LITTLE PIGS 
OPTIMUS PRIME 
TAKE A COFFEE BREAK 
TELEVISION ANTENNA 
PLATOON SERGEANT 
LUNAR ROVER 
TOASTED MARSHMALLOW 
DAN AYKROYD 
THE FREEZING POINT 
BASKETBALL 
CLAM CHOWDER 
EASTER BUNNY 
CHICKEN POX 
SWITZERLAND 
HOT CROSS BUNS 
EYE SHADOW 
THE LONE RANGER 
FOOD PROCESSOR 
CHECKOUT LINE 
ROCK AND ROLL MUSIC 
COBBLESTONE STREET 
BULLETIN BOARD 
OPTICAL ILLUSION 
HIGH SCHOOL PROM 
WEIGHT LIFTER 
TRICK OR TREAT 
LUCKY CHARM 
MAGNIFYING GLASS 
PANAMA CANAL 
ELVIS PRESLEY 
MICHAEL JACKSON 
FLUORIDATED WATER 
BET YOU CAN'T EAT JUST ONE 
GEORGE WASHINGTON 
SNOOPY AND WOODSTOCK 
PEN AND PENCIL SET 
CIVIL WAR 
BATMAN AND ROBIN 
ROCK CONCERT 
PLAYING CARDS 
CROCODILE DUNDEE 
PUERTO RICO 
FAMILY DOCTOR 
DAVY CROCKETT 
TEDDY BEAR 
BLOOD VESSEL 
CANNIBAL 
RUDOLPH THE RED-NOSED REINDEER 
FREEZE IN YOUR TRACKS 
CHRISTMAS VACATION 
DISC JOCKEY 
ROBINSON CRUSOE 
AIRPLANE PROPELLER 
AMAZON RIVER 
RETURN OF THE JEDI 
POLAR BEAR 
SUPER BOWL GAME 
ANIMATOR 
STAMP COLLECTOR 
CHRISTMAS EVE 
SPAGHETTI AND MEATBALLS 
SYNTHESIZER 
POLO SHIRTS 
ON TOP OF THE WORLD 
LEAD PENCIL 
PIN CUSHION 
THE MUPPETS TAKE MANHATTAN 
VENETIAN BLINDS 
CACTUS PLANT 
FOURTH OF JULY 
MARY MARY QUITE CONTRARY 
CAPTAIN HOOK 
INSURANCE POLICY 
HEAD OF THE CLASS 
PAJAMA BOTTOMS 
MAGICIAN 
SPIDER WEB 
MARTIN LUTHER KING 
BREAK A PROMISE 
TELEVISION SET 
SUBMARINE PERISCOPE 
REPORT CARD 
STEAM ENGINE 
AIR-TO-AIR MISSILE 
ALCATRAZ 
GUINEA PIG 
RING AROUND THE ROSIE 
STRAIGHT FROM THE HORSE'S MOUTH 
X-RAY MACHINE 
RAGGEDY ANN AND ANDY 
JELLYBEANS 
HYPNOTIST 
LOOSE-LEAF NOTEBOOK 
CREDIT APPLICATION 
WORLD WRESTLING FEDERATION 
GREMLINS 
BASEBALL BAT 
BAR MITZVAH 
GET READY GET SET GO 
SABER- TOOTHED TIGER 
LAWN MOWER 
DON'T COUNT ON IT 
EXTENSION CORD 
WEDDING CEREMONY 
QUESTION MARK 
FUNNY BONE 
SWEET SIXTEEN PARTY 
POCKET CALCULATOR 
ZIP CODE 
SPACE WALK 
TYPEWRITER 
LEMONADE STAND 
FINGER LICKING GOOD 
DRIP-DRY SHIRT 
ALBERT EINSTEIN 
MY THREE SONS 
GRANOLA BAR 
EARTHQUAKE 
GRAND SLAM HOME RUN 
MOTHER GOOSE 
BARBECUE GRILL 
DRAWBRIDGE 
MONOPOLY 
MICKEY MANTLE 
COSTUME JEWELRY 
TOPSY-TURVY 
CHRISTMAS STOCKING 
ROCKING HORSE 
FIT AS A FIDDLE 
LITTLE LEAGUE BASEBALL TEAM 
INDIAN CHIEF 
PERMISSION SLIP 
ROBIN HOOD 
CLEAN UP YOUR ROOM 
CHUCK NORRIS 
BLACK WIDOW SPIDER 
A DROP IN THE BUCKET 
BULLETPROOF VEST 
STOP LOOK AND LISTEN 
IT'S RAINING CATS AND DOGS 
WASTEBASKET 
COURT MARTIAL 
SWEATSHIRT 
THERMOMETER 
BEDTIME STORY 
JUMP ROPE 
BEAUTY AND THE BEAST 
BEVERLY HILLS 
CHRISTOPHER COLUMBUS 
ASPARAGUS 
CRACKER JACK 
HOWARD COSELL 
BROCCOLI 
PEE-WEE HERMAN 
LADY AND THE TRAMP 
BINOCULARS 
WAFFLES AND ICE CREAM 
ROAD RUNNER 
A FORK IN THE ROAD 
FRANCIS SCOTT KEY 
FERRIS WHEEL 
LIFE PRESERVER 
JUGGLER 
PLAY THE PIANO 
AUDITORIUM 
HOMEMADE APPLE PIE 
SURPRISE PARTY 
THE CALIFORNIA RAISINS 
SAN DIEGO ZOO 
DISNEYLAND 
MEXICO CITY 
LOTTERY TICKET 
VIDEO CASSETTE RECORDER 
PAJAMA PARTY 
HEXAGON 
GULF OF MEXICO 
HORSE AND BUGGY 
HELICOPTER 
PLASTER OF PARIS 
DAILY NEWSPAPER 
SPRING BREAK 
BABY CARRIAGE 
COCKROACH 
LOS ANGELES CALIFORNIA 
WHIPPED CREAM CAKE 
SNOWBALLS 
GARFIELD 
GARAGE SALE 
THE WASHINGTON MONUMENT 
DANIEL BOONE 
FRED FLINTSTONE 
ACCORDION 
DAN MARINO 
THE FAT BOYS 
DOUBLE HEADER 
MASTERS OF THE UNIVERSE 
SWAT TEAM 
MILKY WAY GALAXY 
SCUBA DIVER 
HURRICANE 
TEN-SPEED BICYCLE 
CHOCOLATE CHIP COOKIES 
COAST GUARD 
YOSEMITE SAM 
EGG ROLL 
JUPITER 
PHIL DONAHUE 
HOLOGRAM 
TALCUM POWDER 
DICTIONARY 
FRENCH TOAST 
NORFOLK VIRGINIA 
HANS CHRISTIAN ANDERSEN 
TROUBLE- MAKER 
QUEEN ELIZABETH 
SAUDI ARABIA 
JOHN RITTER 
RAILROAD TIMETABLE 
VIDEO GAMES 
SHOCK ABSORBER 
PINOCCHIO 
CRASH HELMET 
CEMETERY 
ABACUS 
LOBSTER TAILS 
ATLANTIC OCEAN 
BABY'S FIRST TOOTH 
THERE'S NOTHING TO IT 
THE EYE OF THE HURRICANE 
PINEAPPLE UPSIDE-DOWN CAKE 
HEADS OR TAILS 
PETER RABBIT 
LUKE SKYWALKER 
INFIRMARY 
WORLD TRADE CENTER 
HEATHCLIFF 
OLD MOTHER HUBBARD 
ALICE IN WONDERLAND 
ELEMENTARY SCHOOL 
WATERBED 
SALTWATER TAFFY 
VIETNAM 
PLAY DOH 
EASTER SUNDAY 
AMERICAN FLAG 
MARMADUKE 
BEHIND THE EIGHT BALL 
CAIRO EGYPT 
PRINCE 
CAESAR SALAD 
DRIVE A HARD BARGAIN 
TEE SHIRT 
RONALD REAGAN 
THE LITTLE RASCALS 
SNAPPING TURTLE 
PARATROOPER 
WHAT'S UP DOC 
SALTINE CRACKERS 
CHIMPANZEE 
DENTAL FLOSS 
BRAIN SURGEON 
WICKED WITCH OF THE EAST 
TREE HOUSE 
SNAP CRACKLE AND POP 
IRONING BOARD 
JACK FROST 
EASTER EGG HUNT 
HERCULES 
HAPPY HANUKKAH 
COUCH POTATO 
GLASS BOTTOM BOAT 
NEPTUNE 
NATIONAL FOOTBALL LEAGUE 
GOD BLESS AMERICA 
TELESCOPE 
CANDY CANES 
TAPE MEASURE 
WHO KILLED COCK ROBIN 
LOOK IT UP 
THE FLINTSTONE KIDS 
THE BRADY BUNCH 
SOCCER GAME 
SET A GOOD EXAMPLE 
OUTER SPACE 
BARBIE DOLL 
DRIVE-IN WINDOW 
ESCALATOR 
JACKIE ROBINSON 
PORKY PIG 
CITIZEN'S BAND RADIO 
SOUTH AMERICA 
THE DISNEY CHANNEL 
PUBLIC LIBRARY 
MASQUERADE PARTY 
COCA-COLA 
PLAY FAIR AND SQUARE 
THE INCREDIBLE HULK 
BUTTERFLY 
CAPE HATTERAS 
MARILYN MONROE 
FATHER TIME 
PHOTOCOPY MACHINE 
BUTTONHOLE 
NUTTY AS A FRUITCAKE 
THE ACE OF SPADES 
SOCIAL STUDIES TEACHER 
GIRL SCOUT COOKIES 
FRIED RICE 
CONTINENTAL CONGRESS 
SYLVESTER THE CAT 
SUPER MARIO BROTHERS 
BEETLE BAILEY 
MOTHER IN LAW 
TROPICAL FISH 
HICKORY DICKORY DOCK 
SESAME STREET 
DR JEKYLL AND MR HYDE 
STEVEN SPIELBERG 
CONTACT LENS 
ELECTRIC CHAIR 
SLEEPWALKER 
CABIN CRUISER 
GULLIVER'S TRAVELS 
GRASSHOPPER 
MACARONI AND CHEESE CASSEROLE 
BILL COSBY 
ASH WEDNESDAY 
HEAVYWEIGHT BOXER 
SHERLOCK HOLMES 
TOTEM POLE 
HAPPY BIRTHDAY 
PERRY MASON 
WILLIAM SHATNER 
SUNFLOWER SEEDS 
GAS STATION 
SCRAMBLED EGGS 
DENTIST'S OFFICE 
DOGGIE BAG 
CROSSWORD PUZZLE 
MEMORIAL DAY 
STRAWBERRY SHORTCAKE 
PUNCTUATION MARK 
BAKER'S DOZEN 
MULTIPLE CHOICE QUIZ 
INDIANA JONES 
SUBWAY TRAIN 
HIDE AND SEEK 
JELLY DOUGHNUT 
RUBBER BAND 
TOBOGGAN 
FAMILY CIRCLE 
BABE RUTH 
CEMENT MIXER 
WEDDING RING 
AMBASSADOR 
BACKGAMMON 
PARIS FRANCE 
PRAYING MANTIS 
BE MY VALENTINE 
PUSSY WILLOW 
KNIGHTS OF THE ROUND TABLE 
DOG BISCUIT 
SLEEPING BEAUTY 
SPACE SHUTTLE 
KEEP ONE'S PROMISE 
POPCORN 
WATERMELON 
ODDS AND EVENS 
CALGARY CANADA 
MERRY CHRISTMAS 
MICHAEL J FOX 
WILLIE MAYS 
FORTUNE TELLER 
PENCIL SHARPENER 
THE GREAT LAKES 
TREASURE HUNT 
CORN FLAKES 
REGISTERED NURSE 
BOMBS AWAY 
HUGS AND KISSES 
NEW YORK CITY 
TENNIS RACKET 
BABY-SITTER 
DRESS REHEARSAL 
LONG DISTANCE OPERATOR 
BERT AND ERNIE 
BRIDE AND GROOM 
TWO-WAY MIRROR 
TONY THE TIGER 
SMOKE SIGNALS 
SCIENCE EXPERIMENT 
FORKLIFT TRUCK 
SCHOOL CAFETERIA 
HOWARD THE DUCK 
WASHING MACHINE 
GEIGER COUNTER 
PEPPERONI PIZZA 
TOM AND JERRY 
A BOY NAMED CHARLIE BROWN 
FLYING FISH 
TOUCHDOWN 
FOOTBALL HELMET 
DIACRITICAL MARK 
STATION WAGON 
LAS VEGAS NEVADA 
CHAUFFEUR 
SMOKEY THE BEAR 
FROSTY THE SNOWMAN 
I LOVE YOU 
CHOCOLATE PUDDING 
CORN ON THE COB 
DRY CLEANER 
CRANBERRY SAUCE 
RICE PUDDING 
PONY EXPRESS RIDER 
PORK AND BEANS 
A HOME COMPUTER 
HONESTY IS THE BEST POLICY 
CARE BEARS 
SECRET AGENT 
CAN OPENER 
DRIVER'S LICENSE 
MUSTACHE COMB 
SIMON SAYS 
DAVID LETTERMAN 
BOOSTER SHOT 
DEPUTY SHERIFF 
CURLY MOE AND LARRY 
BREAD AND BUTTER 
CHEERIOS 
HOT WHEELS 
BUBBLE BATH 
SIAMESE TWINS 
THE KARATE KID 
MOUSETRAP 
THE SCHOOL CUSTODIAN 
THE A TEAM 
DADDY LONGLEGS 
SIX-INCH RULER 
GLOVE COMPARTMENT 
MICROWAVE OVEN 
LITTERBUG 
COTTAGE CHEESE 
HOCKEY PUCK 
RONALD MCDONALD 
STAND ON ONE'S OWN TWO FEET 
WASHINGTON REDSKINS 
COMIC BOOK 
CROSS AT THE GREEN 
GOLDEN GATE BRIDGE 
BOBBY PIN 
TRAFFIC SIGNAL 
SLIDING GLASS DOOR 
APARTMENT HOUSE 
EMPIRE STATE BUILDING 
I'LL DO IT TOMORROW 
MICKEY MOUSE 
GOLF CLUBS 
EASY COME EASY GO 
CHALKBOARD 
DENTAL HYGIENIST 
UNITED STATES OF AMERICA 
NUCLEAR SUBMARINE 
TURN GREEN WITH ENVY 
CAPTAIN KANGAROO 
HOOVER DAM 
WINNIE THE POOH 
STOP DROP AND ROLL 
COMPUTER GAMES 
COLLEGE GRADUATION 
FALSE TEETH 
COLUMBUS DAY 
SCREWDRIVER 
SENIOR CITIZEN 
SYMPHONY ORCHESTRA 
GRANDFATHER CLOCK 
ARCTIC CIRCLE 
A PAIR OF GLOVES 
ALLIGATOR 
PREPOSITION 
OPRAH WINFREY 
VITAMIN PILLS 
DALLAS TEXAS 
GENERATION GAP 
JACK-O- LANTERN 
KNITTING NEEDLES 
HAMMERHEAD SHARK 
UMBRELLA 
EDDIE MURPHY 
IT WAS A CLOSE CALL 
WORLD CUP SOCCER MATCH 
BREAK DANCING CONTEST 
FIRE PREVENTION WEEK 
BIRTH CERTIFICATE 
REMOTE CONTROL CARS 
DIGITAL WATCH 
ABOUT FACE 
DAY-CARE CENTER 
BUNK BEDS 
DRIVE-IN THEATER 
CHICKEN MCNUGGETS 
THE WHITE HOUSE 
DARRYL STRAWBERRY 
AN AMERICAN TAIL 
ROCKY MOUNTAINS 
A HOLE IN ONE 
OFFENSIVE TACKLE 
A FROG IN MY THROAT 
CARNIVAL 
COTTON CANDY 
EJECTION SEAT 
TOM CRUISE 
THE EMPEROR'S NEW CLOTHES 
BULLFIGHTER 
WHAT YOU SEE IS WHAT YOU GET 
EPCOT CENTER 
ARITHMETIC BOOK 
COOKIE MONSTER 
MEDAL OF HONOR 
HAMMER AND NAILS 
WOODY WOODPECKER 
DUFFEL BAG 
COUNTRY AND WESTERN MUSIC 
ANTARCTICA 
CHARLEY HORSE 
PIG OUT 
FIRST ANNIVERSARY 
LEAKY FAUCET 
TRACK AND FIELD DAY 
MOUNT EVEREST 
BRUCE SPRINGSTEEN 
WONDER WOMAN 
HANG TEN 
BALLET DANCER 
IT WAS AN ACCIDENT 
EVENING STAR 
CHECKING ACCOUNT 
TOOTH FAIRY 
SPACE MOUNTAIN 
CHINESE CHECKERS 
CALAMINE LOTION 
ROLLER COASTER 
LICENSE PLATE 
GERMAN SHEPHERD DOG 
FLY OFF THE HANDLE 
ENGLISH CHANNEL 
SURFBOARD 
A RUBBER DUCK 
LOW-CALORIE DIET 
LIKE A FISH OUT OF WATER 
DENNIS THE MENACE 
KANGAROO 
DART BOARD 
MODEL RAILROAD 
GENERAL OF THE ARMY 
MAKE AN EXCEPTION 
THE MAYFLOWER 
MOUNT RUSHMORE 
WEAR A LONG FACE 
COMPOUND WORD 
FRAGGLE ROCK 
ADHESIVE TAPE 
HAVE A NICE DAY 
HAMBURGER 
BOW AND ARROW 
DENNIS THE MENACE 
NO TRESPASSING 
SWEET POTATO 
HANSEL AND GRETEL 
PISTACHIO NUTS 
CARBON DIOXIDE GAS 
HEIGH-HO HEIGH-HO 
THE BIG DIPPER 
ELECTRIC TRAIN SET 
TELEVISION COMMERCIAL 
GOVERNOR 
LONDON ENGLAND 
THE PINK PANTHER 
STATUE OF LIBERTY 
NINA PINTA AND SANTA MARIA 
MAKE UP YOUR MIND 
MOTLEY CRUE 
MOTHER'S DAY 
DARTH VADER 
HOMEWORK ASSIGNMENT 
AIRCRAFT CARRIER 
HALF-DOLLAR 
POLAROID CAMERA 
HAWAIIAN SHIRT 
JACK-IN- THE-BOX 
EQUAL SIGN 
BASEBALL DIAMOND 
VACUUM CLEANER 
COVERED WAGON 
POP GOES THE WEASEL 
BALLPOINT PEN 
WRISTWATCH 
RINGTOSS 
MARY POPPINS 
WORD PROCESSOR 
FIRST-PRIZE WINNER 
ABSENCE NOTE 
COMPACT DISC 
ABOMINABLE SNOWMAN 
BACK-SEAT DRIVER 
CORDLESS TELEPHONE 
IDENTICAL TWINS 
THREE-RING CIRCUS 
ENTER AT YOUR OWN RISK 
TOOTSIE ROLL 
MAGAZINE 
NEW YORK METS 
KLEENEX TISSUES 
ORANGE BOWL PARADE 
ABRAHAM LINCOLN 
A GOOD SPORT 
XYLOPHONE 
BAKED POTATO 
DO NOT DISTURB 
NO VACANCY 
PINCH HITTER 
MERCURY 
BURGLAR 
GARBAGE PAIL KIDS CARDS 
ALGONQUIN INDIANS 
NO PROBLEM 
VETERANS DAY 
MOVIE FILM PROJECTOR 
CORVETTE 
MR POTATO HEAD 
DURAN DURAN 
HALLOWEEN 
GYMNASIUM 
SUPERMAN 
BAKING POWDER 
SKATEBOARD 
TOPIC SENTENCE 
MIAMI FLORIDA 
SECOND COUSIN 
HOLY COMMUNION 
SANTA CLAUS 
SALT AND PEPPER 
WITCH DOCTOR 
OVER THE TOP 
THE NUTCRACKER SUITE 
JOHN FITZGERALD KENNEDY 
NORTH AMERICA 
PETER PETER PUMPKIN EATER 
PUNKY BREWSTER 
JIGSAW PUZZLE 
TREASURE ISLAND 
THE BEATLES 
RAINBOW BRITE 
ROLLER SKATING RINK 
ASTRONAUT 
THE WIZARD OF OZ 
CREPE PAPER 
PRESIDENTS DAY 
WATER FOUNTAIN 
HEY THERE IT'S YOGI BEAR 
THE WORLD SERIES 
WHAT TIME IS IT 
YANKEE STADIUM 
ELECTRON MICROSCOPE 
WHEEL OF FORTUNE 
THE BEACH BOYS 
E T PHONE HOME 
VALENTINE'S DAY 
YUGOSLAVIA 
AUCTIONEER 
CAPTAIN POWER 
SOUNDPROOF ROOM 
GOOD GRIEF CHARLIE BROWN 
CANTALOUPE 
OBSERVATION DECK 
JOHNNY APPLESEED 
PINBALL MACHINE 
MISS AMERICA PAGEANT 
HERMIT CRAB 
JELLYFISH 
GO FLY A KITE 
QUEEN ISABELLA 
STEREO SYSTEM 
COLORING BOOK 
PRIVATE DETECTIVE 
RED BLOOD CELLS 
MURDER SHE WROTE 
CREAM AND SUGAR 
ANIMAL CRACKERS 
TOMAHAWK 
CHRISTENING 
CINDERELLA 
WASHINGTON D C 
ASSEMBLY PROGRAM 
BERENSTAIN BEARS 
NIAGARA FALLS 
EUCALYPTUS LEAVES 
KOALA BEAR 
HAVE A SCREW LOOSE 
LAUNCHING PAD 
PAWNSHOP 
THINK IT OVER 
TRAVELING SALESMAN 
SHAME ON YOU 
PRINCETON UNIVERSITY 
LIBERTY BELL 
ACAPULCO MEXICO 
THROW ONE'S WEIGHT AROUND 
ZIMBABWE RHODESIA 
THIRD- DEGREE BURN 
LIE- DETECTOR TEST 
LOUIS PASTEUR 
PHILIPPINE ISLANDS 
OUTBOARD MOTOR 
POTBELLIED STOVE 
LEANING TOWER OF PISA 
HIT-AND-RUN DRIVER 
HALIFAX NOVA SCOTIA 
OPERA HOUSE 
HOSPITAL EMERGENCY ROOM 
MORNING GLORY 
KODIAK ISLAND 
PROOF- READER 
LIGHTNING ROD 
OREGON TRAIL 
LEAP YEAR 
DAMASCUS SYRIA 
STICK-IN- THE-MUD 
ZION NATIONAL PARK 
ATTORNEY AT LAW 
RACK YOUR BRAINS 
QUARTZ WATCH 
EBENEZER SCROOGE 
WIDE RECEIVER 
THIS IS NO LAUGHING MATTER 
TRAVELER'S CHECK 
SPEEDY GONZALEZ 
TREASURY BOND 
ALEXANDER HAMILTON 
LEXINGTON KENTUCKY 
HANDCUFFS 
BASEBALL HALL OF FAME 
MORSE CODE 
LICORICE CANDY 
OUTFIELDER 
HIROSHIMA JAPAN 
ORANGUTAN 
A CHANGE OF PACE 
HACKENSACK NEW JERSEY 
NATIONAL GUARD 
HOME PLATE 
HOCUS- POCUS 
OPEN- HEART SURGERY 
BURN A HOLE IN ONE'S POCKET 
OSHKOSH WISCONSIN 
ORPHANAGE 
LET YOUR HAIR DOWN 
OVERTIME PAY 
DEAD SEA 
YOU SHOULD KNOW BETTER 
THE KREMLIN 
PRISONER OF WAR 
ELMER FUDD 
IN THE LAP OF LUXURY 
SHAWNEE INDIANS 
HAVE THE LAST LAUGH 
HALF BROTHER 
VOLUNTEER 
HE'S PULLING YOUR LEG 
KEEP A STIFF UPPER LIP 
LIBRARY OF CONGRESS 
TRICERATOPS 
SEVEN- LAYER CAKE 
AIRLINE PASSENGER 
BY TRIAL AND ERROR 
WEEPING WILLOW TREE 
GUIDE DOG 
GLOWWORM 
MORGUE 
HITCH-HIKER 
LAUNDROMAT 
SAINT LAWRENCE SEAWAY 
GLASS BLOWER 
NIGHT OF THE FULL MOON 
FROM RUSSIA WITH LOVE 
JAPANESE BEETLE 
MOUNTAIN CLIMBER 
QUINTUPLETS 
STEAM SHOVEL 
QUICKSAND 
ROMAN CANDLES 
MEXICAN SOMBRERO 
TAXPAYER 
MOUNT VESUVIUS 
MIGRANT WORKER 
MEET FACE TO FACE 
HELSINKI FINLAND 
DUDE RANCH 
COONSKIN CAP 
ANTIFREEZE 
PALM SPRINGS CALIFORNIA 
RALEIGH NORTH CAROLINA
`;