
function wofFindPuzzles($parentDiv,wordList)
{
	
	let regEx = createRegExFromCharMap($parentDiv);
	
	if (regEx==null) return;
	
	let results = wordList.match(regEx);
	
	let matchMessage = "";
	let freqMessage = ""
	if (results == null)
	{
		message = "No matches";
		freqMessage="";
	}
	else
	{
		message = results.join("\n");
		let freqMap = results2CharFreqMap(results);
		freqMessage = charFreqMap2Message(freqMap);
	}

	$parentDiv.find("textarea.results").first().val(message);
	$parentDiv.find("textarea.freq").first().val(freqMessage);
}

function results2CharFreqMap(resultsArr)
{
	let result="", letter="", i=0;
	let map = new Map();
	let charCounts = {}
	
	//for (result in resultsArr)
	//{
	resultsArr.forEach(result => {
		let realAnswer = result.split("|")[1];

		for (i=0; i<realAnswer.length; i++)
		{
			letter = realAnswer.charAt(i);
			//addOneToMap(map,letter);
			if (letter > 'Z' || letter < 'A') continue;
			
		    charCounts[letter] = ++charCounts[letter] || 1;
		}
	});
	
	return charCounts;
}

function addOneToMap(map,letter)
{
	let curCount = map.get(letter);
	if (curCount < 0) curCount=1;
	
	curCount += 1;
	
	map.set(letter,curCount);
}

function charFreqMap2Message(freqMap)
{
	//let mapCounts = new Map();
	let mapCounts= {};
	let letter="";
	
	//first organize letter counts into groupings based on count
	for (letter of Object.keys(freqMap))
	{
		let letterCount = freqMap[letter];
		let charList = mapCounts[letterCount];
		
		if (!charList || charList.length == 0)
		{
			charList = "";
		}
		
		charList += letter;
		
		mapCounts[letterCount]=charList;
	}
	
	//now iterate the counts and show letters for each count (decreasing)
	let message = "";
	let keyArray = Object.keys(mapCounts).map(value => parseInt(value));
	keyArray.sort((a,b)=>b-a);
	//for (var count in keyArray)
	keyArray.forEach(count => {
		let currentLine=""
		currentLine += (""+count).padStart(3) + ": "
		let letters = mapCounts[count];
		for (letter of letters)
		{
			currentLine += letter + " ";
		}
		message += currentLine + "\n";
	});
	
	return message;
}

function createRegExFromCharMap($parentElem)
{
	let $inputElem = $parentElem.find("input.charMap").first();
	let $categoryList = $parentElem.find("input.category");
	let charMap = $inputElem.val();
	let firstWord = true;
	let categoryString = "";
	let pattern = "";
	//if (charMap.length == 0 ) return;
	
	//Create the list of categories from  the inputs
	$categoryList.each(function() {
		if ($(this).is(":checked"))
		{
			if (!firstWord)
			{
				categoryString += "|"
			}
			categoryString += $(this).val();
			firstWord = false;
		}
	});

	if (categoryString.length==0)
	{
		pattern = ".*\\|";
	}
	else
	{
		pattern = categoryString + "\\|";
	}

	let charCounts = charMap.split(" ");
	firstWord = true;
	for (let i=0; i<charCounts.length; i++)
	{
		let charCount = charCounts[i];
		if (charCount.length == 0) continue;
		if (isNaN(charCount)) continue;
		if (!firstWord)
		{
			pattern += ' ';
		}
		
		pattern += '[\\w\'-]{' + charCount + '}';

		firstWord = false;
	}
	
	if (pattern.length > 0)
	{
		pattern = '^' + pattern + '[ ]?$';
		return new RegExp(pattern,'gmi');
	}
	
	return null;
}


let wofAnswers=
`
PLACE|KINGSTON JAMAICA
PLACE|PEKING CHINA
PLACE|PLANETARIUM
PLACE|NOME ALASKA
PLACE|YELLOWSTONE NATIONAL PARK
PLACE|LEXINGTON KENTUCKY
PLACE|OVAL OFFICE
PLACE|LA GUARDIA AIRPORT
PLACE|SAN LUIS OBISPO
PLACE|SALEM OREGON
PLACE|FORT KNOX
PLACE|TIMES SQUARE
PLACE|MOBILE ALABAMA
PLACE|THE EVERGLADES
PLACE|THE FAR CORNERS OF THE EARTH
PLACE|STATE CAPITOL
PLACE|ALCATRAZ
PLACE|LOUISVILLE KENTUCKY
PLACE|MIDDLE ATLANTIC STATES
PLACE|WARSAW POLAND
PLACE|THE CUMBERLAND PASS
PLACE|THE VATICAN
PLACE|LAKE PLACID
PLACE|CINCINNATI
PLACE|SANTIAGO CHILE
PLACE|CARLSBAD CAVERNS
PLACE|FISHERMAN'S WHARF
PLACE|CHINATOWN
PLACE|MONTICELLO
PLACE|TUCSON ARIZONA
PLACE|EXECUTIVE WASHROOM
PLACE|ALBANY NEW YORK
PLACE|NEW ZEALAND
PLACE|LOST AND FOUND COUNTER
PLACE|DOWN UNDER
PLACE|PLAYGROUND
PLACE|SACRAMENTO
PLACE|TOP OF THE HEAP
PLACE|NOTTINGHAM ENGLAND
PLACE|HELSINKI FINLAND
PLACE|FRONT ROW CENTER
PLACE|ATLANTIC CITY
PLACE|THE PENTAGON
PLACE|ALEXANDRIA VIRGINIA
PLACE|OUTER SPACE
PLACE|PORTLAND MAINE
PLACE|UPPER RIGHTHAND CORNER
PLACE|SYDNEY AUSTRALIA
PLACE|CENTER STAGE
PLACE|HANNIBAL MISSOURI
PLACE|CORNER DRUGSTORE
PLACE|PENTHOUSE SUITE
PLACE|BURBANK CALIFORNIA
PLACE|THE PAINTED DESERT
PLACE|COMBAT ZONE
PLACE|BOOT HILL
PLACE|SANTA ANITA RACETRACK
PLACE|ANDOVER MARYLAND
PLACE|ANAHEIM STADIUM
PLACE|OUT OF THE WAY
PLACE|MUNICH GERMANY
PLACE|MINE SHAFT
PLACE|ORLANDO FLORIDA
PLACE|THE HOLY LAND
PLACE|SAUDI ARABIA
PLACE|THE BACKWOODS
PLACE|ELLIS ISLAND
PLACE|SAN JUAN PUERTO RICO
PLACE|IRELAND
PLACE|WESTERN HEMISPHERE
PLACE|FROZEN FOOD SECTION
PLACE|MONTEGO BAY
PLACE|DENTIST'S OFFICE
PLACE|GREENWICH VILLAGE
PLACE|BARNYARD
PLACE|MANHATTAN ISLAND
PLACE|THE GROUND FLOOR
PLACE|UNIVERSAL STUDIOS
PLACE|THE LOUVRE
PLACE|MADRID SPAIN
PLACE|UNDER THE CHRISTMAS TREE
PLACE|HONOLULU
PLACE|DETROIT MICHIGAN
PLACE|DOWN BY THE OLD MILL STREAM
PLACE|MIDDLE OF THE ROAD
PLACE|EAST PAKISTAN
PLACE|IN THE ATTIC
PLACE|FLORENCE ITALY
PLACE|CENTER COURT
PLACE|O'HARE AIRPORT
PLACE|IN THE MIDDLE OF THE RING
PLACE|CARACAS VENEZUELA
PLACE|CITY HALL
PLACE|BERN SWITZERLAND
PLACE|HOMETOWN
PLACE|NEWPORT BEACH
PLACE|CONTINENTAL DIVIDE
PLACE|HIDDEN COMPARTMENT
PLACE|SMOKY MOUNTAINS
PLACE|THE EQUATOR
PLACE|NEXT TO LAST
PLACE|ATHENS GEORGIA
PLACE|PIZZA PARLOR
PLACE|HIROSHIMA
PLACE|BOWLING ALLEY
PLACE|MILWAUKEE
PLACE|THE BALCONY
PLACE|UPPER ATMOSPHERE
PLACE|THE BOTTOM RUNG
PLACE|RADIO CITY MUSIC HALL
PLACE|VIENNA AUSTRIA
PLACE|ACAPULCO
PLACE|AUSTIN TEXAS
PLACE|ON THE PERIMETER
PLACE|UP THE ROAD APIECE
PLACE|ANNAPOLIS
PLACE|STUTTGART GERMANY
PLACE|GRAND CENTRAL STATION
PLACE|ON THE HIGH SEAS
PLACE|TIMES SQUARE
PLACE|ZIMBABWE AFRICA
PLACE|HAWAIIAN ISLANDS
PLACE|CAPE COD
PLACE|SEASIDE
PLACE|BANGKOK THAILAND
PLACE|THE BACK ROW
PLACE|PAWNSHOP
PLACE|CAIRO EGYPT
PLACE|SCHOOL ROOM
PLACE|CARIBBEAN
PLACE|SEOUL KOREA
PLACE|GOVERNOR'S MANSION
PLACE|VIENNA AUSTRIA
PLACE|AROUND THE BEND
PLACE|UNITED STATES NAVAL ACADEMY
PLACE|FAIRFAX NOVA SCOTIA
PLACE|ON THE OUTSIDE LOOKING IN
PLACE|NEW DELHI INDIA
PLACE|HONG KONG
PLACE|HOUSTON ASTRODOME
PLACE|LOWER MANHATTAN
PLACE|WALL STREET
PLACE|DURHAM NORTH CAROLINA
PLACE|SUPERMARKET
PLACE|ANCHORAGE
PLACE|ASIA MINOR
PLACE|STILLWATER OKLAHOMA
PLACE|THEATER BALCONY
PLACE|ETHIOPIA
PLACE|OUTER MONGOLIA
PLACE|SPRINGFIELD ILLINOIS
PLACE|LAUNDROMAT
PLACE|TIJUANA MEXICO
PLACE|MISSISSIPPI
PLACE|KATMANDU
PLACE|BROOKLYN
PLACE|HARVARD MEDICAL SCHOOL
PLACE|HIMALAYAN MOUNTAINS
PLACE|SAN DIEGO
PLACE|RHODE ISLAND
PLACE|BROOM CLOSET
PLACE|DISNEYLAND
PLACE|COLUMBIA
PLACE|ROME ITALY
PLACE|BASEBALL DIAMOND
PLACE|BASKETBALL COURT
PERSON|COPERNICUS
PERSON|THURGOOD MARSHALL
PERSON|CHAMBERMAID
PERSON|WOODY ALLEN
PERSON|SHOESHINE BOY
PERSON|GEORGE WASHINGTON CARVER
PERSON|SIGMUND FREUD
PERSON|LYNDON BAINES JOHNSON
PERSON|TELEPHONE OPERATOR
PERSON|GAS STATION ATTENDANT
PERSON|BERT PARKS
PERSON|SHORT- ORDER COOK
PERSON|COMPANY CLERK
PERSON|HEAD FOOTBALL COACH
PERSON|ELEANOR ROOSEVELT
PERSON|THOMAS PAINE
PERSON|MEDICAL DOCTOR
PERSON|ENGINEER
PERSON|MILLARD FILLMORE
PERSON|DIESEL MECHANIC
PERSON|CHURCH USHER
PERSON|TOP BANANA
PERSON|GARBAGE COLLECTOR
PERSON|NATHAN HALE
PERSON|REGIONAL DIRECTOR
PERSON|COAL MINER
PERSON|ORTHOPEDIC SURGEON
PERSON|ANGIE DICKINSON
PERSON|CHESS CHAMPION
PERSON|APPLIANCE REPAIRMAN
PERSON|ROBERT KENNEDY
PERSON|ASSISTANT DIRECTOR
PERSON|PHYSICAL THERAPIST
PERSON|BABE RUTH
PERSON|BABY SITTER
PERSON|BALLET DANCER
PERSON|SECRET AGENT
PERSON|COMPUTER PROGRAMMER
PERSON|HUMAN BEING
PERSON|ARCHBISHOP OF CANTERBURY
PERSON|SALES CLERK
PERSON|MICHAEL CAINE
PERSON|THE PARISH PRIEST
PERSON|LAW STUDENT
PERSON|CHANCELLOR
PERSON|ISAAC NEWTON
PERSON|BOOKER T WASHINGTON
PERSON|INDIRA GANDHI
PERSON|BEN FRANKLIN
PERSON|MARTIN LUTHER KING
PERSON|NAPOLEON BONAPARTE
PERSON|CARL SANDBURG
PERSON|EDGAR ALLEN POE
PERSON|THOMAS JEFFERSON
PERSON|CAKE DECORATOR
PERSON|DEFENSIVE TACKLE
PERSON|UNINVITED GUEST
PERSON|ANGLO- SAXON
PERSON|UNDERWRITER
PERSON|WINSTON CHURCHILL
PERSON|DIRECTOR OF MARKETING
PERSON|CARRIE NATION
PERSON|ENGLISH TEACHER
PERSON|NIGHT WATCHMAN
PERSON|ALEXANDER GRAHAM BELL
PERSON|CONVENTION DELEGATE
PERSON|NEXT DOOR NEIGHBOR
PERSON|LADYBIRD JOHNSON
PERSON|MEDICAL STUDENT
PERSON|VINCE LOMBARDI
PERSON|TALENT SCOUT
PERSON|NIKITA KRUSCHEV
PERSON|JIMMY CONNERS
PERSON|WILLIAM THE CONQUEROR
PERSON|NEWSPAPER COLUMNIST
PERSON|PUBLISHED AUTHOR
PERSON|JULIUS CAESAR
PERSON|SMOOTH TALKER
PERSON|HAIR STYLIST
PERSON|THEODORE ROOSEVELT
PERSON|CIVILIAN
PERSON|THE SHAH OF IRAN
PERSON|SERGEANT YORK
PERSON|REAL ESTATE BROKER
PERSON|TOMMY DORSEY
PERSON|CAMP COUNSELOR
PERSON|SALVADOR DALI
PERSON|ELIGIBLE BACHELOR
PERSON|JILTED SUITOR
PERSON|BILLIE JEAN KING
PERSON|SYSTEMS ANALYST
PERSON|POCAHONTAS
PERSON|INNOCENT BYSTANDER
PERSON|THOMAS EDISON
PERSON|CLASS CLOWN
PERSON|RALPH WALDO EMERSON
PERSON|MATA HARI
PERSON|HIGH SCHOOL DROPOUT
PERSON|ADJUTANT GENERAL
PERSON|ELEVATOR OPERATOR
PERSON|FRANK LLOYD WRIGHT
PERSON|EXPECTANT MOTHER
PERSON|JOHN GLENN
PERSON|ALBERT SCHWEITZER
PERSON|JACK-OF- ALL-TRADES
PERSON|MORTICIAN
PERSON|ALEXANDER HAMILTON
PERSON|CONSTANT COMPANION
PERSON|ARISTOTLE ONASSIS
PERSON|ESCAPED CONVICT
PERSON|ANN LANDERS
PERSON|RIGHT-HAND MAN
PERSON|AARON BURR
PERSON|MARIE ANTOINETTE
PERSON|ANTIQUE COLLECTOR
PERSON|ANIMAL TAMER
PERSON|ARNOLD PALMER
PERSON|HEAD UMPIRE
PERSON|THE LAST MAN ON EARTH
PERSON|DANIEL BOONE
PERSON|BARRY GOLDWATER
PERSON|APPRENTICE
PERSON|ICE-CREAM VENDOR
PERSON|JOHNNY COME LATELY
PERSON|FERDINAND MAGELLAN
PERSON|TICKET TAKER
PERSON|BRUCE SPRINGSTEEN
PERSON|JACKIE COOPER
PERSON|UNDERMINER
PERSON|PAPERHANGER
PERSON|BLACKSMITH
PERSON|MARQUIS DE SADE
PERSON|MECHANICAL ENGINEER
PERSON|CESAR CHAVEZ
PERSON|HEAD WAITER
PERSON|EUROPEAN IMMIGRANT
PERSON|MENACHEM BEGIN
PERSON|SEVENTH-DAY ADVENTIST
PERSON|NAILBITER
PERSON|ANDREW JACKSON
PERSON|DISK JOCKEY
PERSON|KEEPER OF THE FLAME
PERSON|EVANGELIST
PERSON|DALE CARNEGIE
PERSON|WILLIAM SHAKESPEARE
PERSON|GIFTED CHILD
PERSON|SAM HOUSTON
PERSON|GROVER CLEVELAND
PERSON|JASON ROBARDS
PERSON|PHILANDERER
PERSON|CAMERAMAN
PERSON|WILLIAM RANDOLPH HEARST
PERSON|SNAKE CHARMER
PERSON|MEREDITH BAXTER BIRNEY
PERSON|CERTIFIED PUBLIC ACCOUNTANT
PERSON|BUS DRIVER
PERSON|LEONARD BERNSTEIN
PERSON|NAVIGATOR
PERSON|MAO TSE- TUNG
PERSON|CZAR NICHOLAS
PERSON|PERSONNEL DIRECTOR
PERSON|CONFUCIUS
PERSON|KAREEM ABDUL- JABBAR
PERSON|ANDY WARHOL
PERSON|HIRED HAND
PERSON|WILT CHAMBERLAIN
PERSON|ELECTED OFFICIAL
PERSON|CLASSMATE
PERSON|STATE SENATOR
PERSON|MINNESOTA FATS
PERSON|PUPPETEER
PERSON|JAMES MADISON
PERSON|OBJECTIVE OBSERVER
PERSON|WYATT EARP
PERSON|EUCLID
PERSON|DANNY THOMAS
PERSON|REMBRANDT
PERSON|POLITICAL POLLSTER
PERSON|SAINT FRANCIS OF ASSISI
PERSON|LAWRENCE OLIVIER
PERSON|JESSE JAMES
PERSON|HARRY TRUMAN
PERSON|TAX COLLECTOR
PERSON|MUHAMMAD ALI
PERSON|COMMITTEE CHAIRMAN
PERSON|DWIGHT DAVID EISENHOWER
PERSON|NOVELIST
PERSON|SIR WALTER RALEIGH
PERSON|CITY PLANNER
PERSON|GALILEO
PERSON|CLAIMS ADJUSTER
THING|GOLD KEYCHAIN
THING|PORKPIE HAT
THING|CRANBERRY SAUCE
THING|PLUTONIUM
THING|BOTTLED WATER
THING|TURNTABLE
THING|BEAMED CEILING
THING|HANGNAIL
THING|STUDHORSE
THING|HAIRPIN
THING|PIGGY BANK
THING|CANTALOUPE
THING|JUMPING JACK
THING|BAKING SODA
THING|NEW ENGLAND CLAM CHOWDER
THING|LIQUOR CABINET
THING|APPLE CIDER
THING|PUNCTUATION MARK
THING|DANDELION
THING|PHONOGRAPH RECORD
THING|ORGANIC COMPOUND
THING|SPLIT PEA SOUP
THING|BIRD FEEDER
THING|CHOCOLATE CHIP COOKIE
THING|MOSQUITO
THING|BUTTERCUP
THING|WEDDING RING
THING|POLLING BOOTH
THING|ENGLISH MUFFIN
THING|SOUP LADLE
THING|INCLEMENT WEATHER
THING|BLACK OLIVE
THING|VEGETABLE OIL
THING|CONTRACTION
THING|TIMEPIECE
THING|COCONUT
THING|HEDGE CLIPPER
THING|HORSESHOE
THING|CHRISTMAS TREE
THING|HOMEMADE BREAD
THING|ROLLER SKATE
THING|INTEGRATED CIRCUIT
THING|PATCHWORK
THING|SKYSCRAPER
THING|THERMOMETER
THING|TOMATO SAUCE
THING|MUSICAL NOTE
THING|POTATO SKIN
THING|SALAMANDER
THING|FISHING LURE
THING|PRINTING PRESS
THING|MEAT CLEAVER
THING|TELEVISION ANTENNA
THING|LOUNGE CHAIR
THING|GREEN PEPPER
THING|DUMBWAITER
THING|SNOWMOBILE
THING|WINDSHIELD WIPER
THING|MIGRAINE HEADACHE
THING|HANDMADE QUILT
THING|SALT SHAKER
THING|TOOTHACHE
THING|BROKEN SPOKE
THING|ACHILLES HEEL
THING|DEPLETION ALLOWANCE
THING|CORKSCREW
THING|PACK ANIMAL
THING|CHINESE FOOD
THING|SAUSAGE PATTY
THING|REVOLVING DOOR
THING|CASHIER'S CHECK
THING|CAN OPENER
THING|JACKET POCKET
THING|HAIRPIN
THING|BLOCK AND TACKLE
THING|BAKED POTATO
THING|PENCIL SHARPENER
THING|CALCULATOR
THING|AFFIDAVIT
THING|EXTENDED WARRANTY
THING|HORS D'OEUVRE
THING|UNSALTED PEANUT
THING|WINDMILL
THING|SHOOTING STAR
THING|MICROWAVE OVEN
THING|TUXEDO
THING|COMMON SENSE
THING|LONG DISTANCE PHONE CALL
THING|VIOLIN CASE
THING|LEAST COMMON DENOMINATOR
THING|HARVEY WALLBANGER
THING|HANG GLIDER
THING|ESCALATOR
THING|CORN ON THE COB
THING|MONOCLE
THING|RUBBER BAND
THING|INGROWN TOENAIL
THING|LACERATED CONTUSION
THING|HUMMINGBIRD
THING|LULLABY
THING|FUEL INJECTOR
THING|AIRCRAFT CARRIER
THING|SHOE POLISH
THING|MERRY-GO- ROUND
THING|UNSOLICITED RESPONSE
THING|CHESTNUT
THING|SOUP OF THE DAY
THING|SAUERKRAUT
THING|ELECTRIC BLANKET
THING|WATERMELON
THING|HUMPBACK WHALE
THING|CHURCH STEEPLE
THING|INCOME TAX RETURN
THING|CUBIC METER
THING|TORN LIGAMENT
THING|SUGAR CUBE
THING|BACK INVENTORY
THING|SUBMARINE
THING|SMOKED OYSTER
THING|THUMBTACK
THING|MORNING NEWSPAPER
THING|GRASSHOPPER
THING|AREA CODE
THING|TOOTHPICK
THING|CORN POPPER
THING|DRIVER'S LICENSE
THING|MANNEQUIN
THING|WASHING MACHINE
THING|PEN AND PENCIL SET
THING|HARPSICHORD
THING|PLASTER CAST
THING|CHINESE ALGEBRA
THING|KITCHEN TABLE
THING|CUMMERBUND
THING|CIGARETTE LIGHTER
THING|RADIO TRANSMITTER
THING|CRUDE OIL
THING|SOUR NOTE
THING|MEATBALL
THING|FISHING POLE
THING|DOLLAR BILL
THING|ALLIGATOR
THING|HANDLEBAR MOUSTACHE
THING|WINDOW PANE
THING|SCRATCH PAD
THING|BABY CARRIAGE
THING|LIBRARY CARD
THING|EIGHTEEN WHEELER
THING|ENCHILADA
THING|BAROMETER
THING|PORTRAIT
THING|OBITUARY
THING|WALKING CANE
THING|FRIED RICE
THING|COLLECTOR'S ITEM
THING|CORRUGATED ALUMINUM
THING|SUNDAY FUNNIES
THING|SILVER DOLLAR
LANDMARK|THE GRAND CANYON
LANDMARK|MADISON SQUARE GARDEN
LANDMARK|THE LONDON BRIDGE
LANDMARK|EMPIRE STATE BUILDING
LANDMARK|THE EIFFEL TOWER
LANDMARK|GREAT WALL OF CHINA
LANDMARK|THE ALAMO
LANDMARK|THE LIBERTY BELL
LANDMARK|LINCOLN MEMORIAL
LANDMARK|THE BERLIN WALL
LANDMARK|HOOVER DAM
LANDMARK|GOLDEN GATE BRIDGE
LANDMARK|THE TAJ MAHAL
LANDMARK|THE SWISS ALPS
LANDMARK|GRANT'S TOMB
LANDMARK|PIKE'S PEAK
LANDMARK|THE OK CORRAL
LANDMARK|THE GRAND OLE OPRY
LANDMARK|THE PETRIFIED FOREST
LANDMARK|NOTRE DAME CATHEDRAL
LANDMARK|CAPE CANAVERAL
PHRASE|DON'T ROCK THE BOAT
PHRASE|ON THE UP AND UP
PHRASE|THE DEVIL MADE ME DO IT
PHRASE|THERE'S PLENTY FOR EVERYBODY
PHRASE|DON'T FORGET TO READ THE FINE PRINT
PHRASE|IT'S THE NEXT BEST THING TO BEING THERE
PHRASE|DON'T BE A BACK SEAT DRIVER
PHRASE|TIME IS MONEY
PHRASE|TOO MANY COOKS SPOIL THE BROTH
PHRASE|MANY ARE CALLED BUT FEW ARE CHOSEN
PHRASE|PRIDE GOETH BEFORE THE FALL
PHRASE|IT COMES AND GOES
PHRASE|IT'S ONLY THE TIP OF THE ICEBERG
PHRASE|FOR THE MAN WHO HAS EVERYTHING
PHRASE|THERE'S NO SUCH THING AS A FREE LUNCH
PHRASE|IT'S FOR A GOOD CAUSE
PHRASE|DON'T START SOMETHING YOU CAN'T FINISH
PHRASE|IT'S THE LAW OF THE LAND
PHRASE|LET SLEEPING DOGS LIE
PHRASE|TAKING IT EASY
PHRASE|DON'T BITE THE HAND THAT FEEDS YOU
PHRASE|LOOK BOTH WAYS BEFORE CROSSING
PHRASE|DON'T SPEND IT ALL IN ONE PLACE
PHRASE|OUT TO LUNCH
PHRASE|TAKE TWO ASPIRIN AND CALL ME IN THE MORNING
PHRASE|PERISH THE THOUGHT
PHRASE|YOU CAN'T SAY I DIDN'T WARN YOU
PHRASE|GOOD TABLE MANNERS
PHRASE|EVERY LITTLE BIT COUNTS
PHRASE|MAKING A MOUNTAIN OUT OF A MOLEHILL
PHRASE|THE PROOF IS IN THE PUDDING
PHRASE|SOME GUYS HAVE ALL THE LUCK
PHRASE|DON'T JUMP THE GUN
PHRASE|THE MEANING IS LOST IN THE TRANSLATION
PHRASE|IT'S JUST WATER UNDER THE BRIDGE
PHRASE|NOW THAT THE SHOE IS ON THE OTHER FOOT
PHRASE|OVERLY EXCITED
PHRASE|CLOSED FOR REMODELING
PHRASE|RIPE FOR THE PICKING
PHRASE|JUST WHEN YOU THOUGHT YOU'D HEARD EVERYTHING
PHRASE|FROM THE CRADLE TO THE GRAVE
PHRASE|PLAYING FOR KEEPS
PHRASE|MY BACK'S AGAINST THE WALL
PHRASE|TURN THE OTHER CHEEK
PHRASE|HITTING BELOW THE BELT
PHRASE|I'M HOLDING MY OWN
PHRASE|UNDER THE WEATHER
PHRASE|NOT ON YOUR LIFE
PHRASE|THERE'S SOMETHING FOR EVERYBODY
PHRASE|NEVER SAY NEVER
PHRASE|SAVE IT FOR A RAINY DAY
PHRASE|WITHIN A BLINK OF AN EYE
PHRASE|DON'T LOOK BACK
PHRASE|THERE'S A SUCKER BORN EVERY MINUTE
PHRASE|NEVER AT A LOSS FOR WORDS
PHRASE|LET THE GOOD TIMES ROLL
PHRASE|ON COMMON GROUND
PHRASE|TOO LITTLE TOO LATE
PHRASE|THIRD RATE ROMANCE
PHRASE|TAKEN FOR GRANTED
PHRASE|NOT TOO BAD UNDER THE CONDITIONS
PHRASE|HOPE TO SEE YOU SOON
PHRASE|EARN WHILE YOU LEARN
PHRASE|HELPFUL HINT
PHRASE|WINNER AND STILL CHAMPION
PHRASE|NOTHING BUT THE FACTS
PHRASE|ALL OR NOTHING
PHRASE|EVERY MAN FOR HIMSELF
PHRASE|SOMETHING FOR NOTHING
PHRASE|LOVE IT OR LEAVE IT
PHRASE|A DIAMOND IN THE ROUGH
PHRASE|BLOWING HOT AND COLD
PHRASE|OPENING UP A CAN OF WORMS
PHRASE|TWIDDLING YOUR THUMBS
PHRASE|HONESTY IS THE BEST POLICY
PHRASE|BURSTING AT THE SEAMS
PHRASE|SIGN ON THE DOTTED LINE
PHRASE|FLICK OF THE WRIST
PHRASE|A NEW BROOM SWEEPS CLEAN
PHRASE|WISH YOU WERE HERE
PHRASE|GETTING DOWN TO BRASS TACKS
PHRASE|NEAT AS A PIN
PHRASE|HIGH JINKS
PHRASE|THE SOONER THE BETTER
PHRASE|EVERYTHING BUT THE KITCHEN SINK
PHRASE|TAKE THE BULL BY THE HORNS
PHRASE|DOUBLE OR NOTHING
PHRASE|CHARITY BEGINS AT HOME
PHRASE|TAKE A BREAK
PHRASE|TAKE IT AS IT COMES
PHRASE|TOO MUCH TOO SOON
PHRASE|SEEING IS BELIEVING
PHRASE|SOMETHING HAS TO BE DONE ABOUT IT
PHRASE|BLOOD IS THICKER THAN WATER
PHRASE|BELIEVE IT OR NOT
PHRASE|EVERY DOG HAS ITS DAY
PHRASE|SEVEN COME ELEVEN
PHRASE|SOME THINGS ARE BETTER LEFT UNSAID
PHRASE|MAKE ME AN OFFER
PHRASE|CLOSE COVER BEFORE STRIKING
PHRASE|KEEP YOUR GUARD UP
PHRASE|NO LAUGHING MATTER
PHRASE|SOME PEOPLE NEVER LEARN
PHRASE|IT JUST DOESN'T ADD UP
PHRASE|BEHIND THE EIGHT BALL
PHRASE|DON'T COUNT ON IT
PHRASE|BY THE GRACE OF GOD
PHRASE|LEAVE IT BE
PHRASE|ON CLOUD NINE
PHRASE|UNDER THE TABLE
PHRASE|DON'T TAKE IT FOR GRANTED
PHRASE|MAYBE SO AND MAYBE NOT
PHRASE|AT THE CROSSROADS
PHRASE|TAKE IT TO THE LIMIT
PHRASE|OVER-THE- COUNTER
PHRASE|IN THE DOGHOUSE
PHRASE|MY TWO CENTS WORTH
PHRASE|OVER THE HILL
PHRASE|BRINGING UP THE REAR
PHRASE|THE STRAW THAT BROKE THE CAMEL'S BACK
PHRASE|COMING OF AGE
PHRASE|THE MORE THE MERRIER
PHRASE|THE LAST PLACE YOU'D THINK OF
PHRASE|HAPPY DAYS ARE HERE AGAIN
PHRASE|THE WHOLE NINE YARDS
PHRASE|GO TO THE HEAD OF THE CLASS
PHRASE|IN THE TWINKLING OF AN EYE
PHRASE|RETURN TO SENDER
PHRASE|I'VE HAD IT UP TO HERE
PHRASE|THE LONG AND SHORT OF IT
PHRASE|THE BOTTOM OF THE BARREL
PHRASE|HOLD THE PHONE
PHRASE|ON THE RAZOR'S EDGE
PHRASE|LET THE CHIPS FALL WHERE THEY MAY
PHRASE|THE WRONG SIDE OF THE TRACKS
PHRASE|STOP THE PRESSES
PHRASE|THE WORM HAS TURNED
PHRASE|NO USE CRYING OVER SPILLED MILK
PHRASE|CASH AND CARRY
PHRASE|CRIME DOESN'T PAY
PHRASE|BOY MEETS GIRL
PHRASE|NOTHING BUT THE BEST
PHRASE|THE GOLDEN RULE
PHRASE|ONE GOOD TURN DESERVES ANOTHER
PHRASE|KEEP A STIFF UPPER LIP
PHRASE|HE WHO LAUGHS LAST
PHRASE|ON THE RIGHT TRACK
PHRASE|SECOND TO NONE
PHRASE|IN THE RIGHT FRAME OF MIND
PHRASE|DON'T TAKE ANY WOODEN NICKELS
PHRASE|SO BE IT
PHRASE|LET'S MAKE A DAY OF IT
PHRASE|LOOK IT UP
PHRASE|THE BEST AND THE BRIGHTEST
PHRASE|IT'S OPEN FOR DISCUSSION
PHRASE|THE JOKE'S ON YOU
PHRASE|THE BUCK STOPS HERE
PHRASE|STANDING ROOM ONLY
PHRASE|RIGHT BETWEEN THE EYES
PHRASE|GONE BUT NOT FORGOTTEN
PHRASE|THE TIME IS NOW
PHRASE|THE CREAM ALWAYS RISES TO THE TOP
PHRASE|MY CUP RUNNETH OVER
PHRASE|THERE'S NO DOUBT ABOUT IT
PHRASE|YOU CAN BANK ON IT
PHRASE|OVER AND OUT
PHRASE|YOU CAN TAKE MY WORD ON IT
PHRASE|LIFE IS FOR THE LIVING
PHRASE|LEND ME AN EAR
PHRASE|LONG LIVE THE KING
PHRASE|THERE'S NOTHING TO IT
PHRASE|I DON'T GET NO RESPECT
PHRASE|THE AGONY AND THE ECSTASY
PHRASE|PAUL REVERE'S RIDE
PHRASE|MAKE THE MOST OF IT
PHRASE|TALK IS CHEAP
PHRASE|SQUEAKY CLEAN
PHRASE|THERE'S NO EXCUSE FOR IT
PHRASE|ON THE BUTTON
PHRASE|DON'T LEAVE WITHOUT SAYING GOODBYE
PHRASE|YOU GO YOUR WAY AND I'LL GO MINE
PHRASE|ONE HAND WASHES THE OTHER
PHRASE|IT'S BIGGER THAN THE BOTH OF US
PHRASE|I'LL MEET YOU HALFWAY
PHRASE|DON'T CALL US WE'LL CALL YOU
PHRASE|DON'T BITE OFF MORE THAN YOU CAN CHEW
PHRASE|LOOK ME IN THE EYE AND SAY THAT
PHRASE|GOING FOR BROKE
THINGS|BANANA SPLITS
THINGS|CEILING FANS
THINGS|BLUEPRINTS
THINGS|TENNIS SHOES
THINGS|CLING PEACHES
THINGS|FINGERNAIL CLIPPERS
THINGS|CHAPPED LIPS
THINGS|HORSE AND BUGGY
THINGS|PAIRS OF SHOES
THINGS|BACON AND EGGS
THINGS|MACARONI AND CHEESE
THINGS|BREAD AND BUTTER
THINGS|BEER AND PRETZELS
THINGS|APPLES AND ORANGES
THINGS|NEEDLES AND PINS
THINGS|ANIMAL VEGETABLE OR MINERAL
THINGS|CAT AND MOUSE
THINGS|CHICKEN AND DUMPLINGS
THINGS|BOWS AND ARROWS
THINGS|CHEESE AND CRACKERS
THINGS|HASH BROWN POTATOES
THINGS|HAMMER AND NAIL
THINGS|STARS AND STRIPES
THINGS|PEACHES AND CREAM
THINGS|CLOAK AND DAGGER
THINGS|ARM AND HAMMER
THINGS|PORK AND BEANS
TITLE|THE EXODUS
TITLE|WHITE CHRISTMAS
TITLE|LIEUTENANT COLONEL
TITLE|EXECUTIVE VICE- PRESIDENT
TITLE|SECRETARY OF DEFENSE
TITLE|SPEAKER OF THE HOUSE
TITLE|BRIGADIER GENERAL
TITLE|CHIEF-OF- POLICE
TITLE|NATIONAL VELVET
TITLE|COMMANDER- IN-CHIEF
TITLE|SURGEON GENERAL
TITLE|SECRETARY OF THE INTERIOR
TITLE|POSTMASTER GENERAL
TITLE|SERGEANT- AT-ARMS
TITLE|UNCHAINED MELODY
TITLE|SENATE MAJORITY WHIP
TITLE|GONE WITH THE WIND
TITLE|DISTRICT ATTORNEY
TITLE|PRIME MINISTER
TITLE|THE DAYS OF WINE AND ROSES
TITLE|LOVE LETTERS IN THE SAND
TITLE|NONE BUT THE BRAVE
TITLE|RETURN OF THE JEDI
TITLE|THE GOOD THE BAD AND THE UGLY
TITLE|MOON RIVER
TITLE|SOMEWHERE OVER THE RAINBOW
TITLE|HEAVYWEIGHT CHAMPION
TITLE|DUCHESS OF WINDSOR
TITLE|WHERE EAGLES DARE
TITLE|THE AFRICAN QUEEN
TITLE|DIAL M FOR MURDER
TITLE|THE EMPIRE STRIKES BACK
TITLE|THE NAKED AND THE DEAD
TITLE|BEETHOVEN'S NINTH
TITLE|INSPECTOR GENERAL
TITLE|THE DIRTY DOZEN
TITLE|THE STING
TITLE|A CLOCKWORK ORANGE
TITLE|MISSION IMPOSSIBLE
TITLE|THE GHOST AND MRS MUIR
TITLE|MAN OF LA MANCHA
TITLE|APOCALYPSE NOW
TITLE|BRIDGE ON THE RIVER KWAI
TITLE|THE SANDS OF IWO JIMA
TITLE|THE HIGH AND THE MIGHTY
TITLE|SEND IN THE CLOWNS
TITLE|I DID IT MY WAY
TITLE|LOVE STORY
TITLE|BREAKFAST AT TIFFANY'S
TITLE|THE LEGEND OF SLEEPY HOLLOW
TITLE|TWINKLE TWINKLE LITTLE STAR
TITLE|IF I WERE A RICH MAN
TITLE|PSYCHO
TITLE|A NIGHT AT THE OPERA
TITLE|ATTORNEY GENERAL
TITLE|BEN HUR
TITLE|THE GUNS OF NAVARONE
TITLE|BEAUTY AND THE BEAST
TITLE|THE OLD MAN AND THE SEA
TITLE|SESAME STREET
TITLE|NEVER ON SUNDAY
TITLE|THE GREAT GATSBY
TITLE|THE SUN ALSO RISES
TITLE|THE BLACKBOARD JUNGLE
TITLE|OF MICE AND MEN
TITLE|JINGLE BELLS
TITLE|THE RISE AND FALL OF THE ROMAN EMPIRE
TITLE|TOOTSIE
TITLE|THE LAST DAYS OF POMPEII
TITLE|MAJOR GENERAL
TITLE|GENTLEMEN PREFER BLONDES
TITLE|THE POSTMAN ALWAYS RINGS TWICE
TITLE|THE FRENCH CONNECTION
TITLE|IN COLD BLOOD
TITLE|WAR AND PEACE
TITLE|ANNIE HALL
TITLE|THE THREE LITTLE PIGS
TITLE|THE GRAPES OF WRATH
TITLE|THE RED PONY
TITLE|DOCTOR ZHIVAGO
TITLE|THE THREE FACES OF EVE
TITLE|PRIDE AND PREJUDICE
TITLE|SPARTACUS
TITLE|MARY POPPINS
TITLE|I WANT TO HOLD YOUR HAND
TITLE|FANTASIA
TITLE|SNOW WHITE
TITLE|SATURDAY NIGHT LIVE
TITLE|CRIME AND PUNISHMENT
TITLE|BONNIE AND CLYDE
TITLE|PLEASE DON'T EAT THE DAISIES
TITLE|HEARTBREAK HOTEL
TITLE|THE LAST OF THE MOHICANS
TITLE|PORGY AND BESS
TITLE|THE FRONT PAGE
TITLE|LOVE ME TENDER
TITLE|WIDE WORLD OF SPORTS
TITLE|GOODBYE MISTER CHIPS
TITLE|THE ELEPHANT MAN
TITLE|THE ILIAD
TITLE|THE CALL OF THE WILD
TITLE|SATURDAY NIGHT FEVER
TITLE|FIDDLER ON THE ROOF
TITLE|TENNESSEE WALTZ
TITLE|PLANET OF THE APES
PEOPLE|BLUE CROSS AND BLUE SHIELD
PEOPLE|LION'S CLUB
PEOPLE|COMMUNIST PARTY
PEOPLE|UNITED NATIONS
PEOPLE|BOY SCOUTS OF AMERICA
PEOPLE|LITTLE LEAGUE BASEBALL
PEOPLE|THE WRITER'S GUILD
PEOPLE|DAUGHTERS OF THE AMERICAN REVOLUTION
PEOPLE|UNIFIED SCHOOL DISTRICT
PEOPLE|CIVIL LIBERTIES UNION
PEOPLE|SCREEN ACTOR'S GUILD
PEOPLE|NATIONAL FOOTBALL LEAGUE
PEOPLE|THE ELK'S CLUB
PEOPLE|AMERICAN AUTOMOBILE ASSOCIATION
PEOPLE|RED CROSS
PEOPLE|COMMON CAUSE
PEOPLE|CHURCH CHOIR
PEOPLE|GREEN BAY PACKERS
PEOPLE|PRESIDENT'S CABINET
PEOPLE|CHURCH OF LATTER-DAY SAINTS
PEOPLE|NATIONAL SECURITY COUNCIL
PEOPLE|FIRE DEPARTMENT
PEOPLE|NATIONAL HOCKEY LEAGUE
PEOPLE|DEMOCRATIC PARTY
PEOPLE|PITTSBURGH PIRATES
PEOPLE|TEXTILE WORKERS' UNION
PEOPLE|DAIRYMEN'S ASSOCIATION
PEOPLE|SECURITIES EXCHANGE COMMISSION
PEOPLE|FRATERNAL ORDER OF POLICE
PEOPLE|BETTER BUSINESS BUREAU
PEOPLE|CONTINENTAL CONGRESS
PEOPLE|CANADIAN MOUNTED POLICE
PEOPLE|TEXAS RANGERS
PEOPLE|KIWANIS CLUB
PEOPLE|BIG BROTHERS OF AMERICA
PEOPLE|MUSCULAR DYSTROPHY ASSOCIATION
PEOPLE|AMERICAN LEGION
PEOPLE|WEIGHT WATCHERS
PEOPLE|YOUNG MEN'S CHRISTIAN ASSOCIATION
PEOPLE|AMERICAN AIRLINES
PEOPLE|KNIGHTS OF COLUMBUS
PEOPLE|REPUBLICAN NATIONAL COMMITTEE
EVENT|THREE DAY WEEKEND
EVENT|ROSE BOWL PARADE
EVENT|KENTUCKY DERBY
EVENT|DINNER AT THE WHITE HOUSE
EVENT|THE WORLD SERIES
EVENT|GRADUATION DAY
EVENT|LODGE MEETING
EVENT|ELECTION DAY
EVENT|STANLEY CUP PLAYOFFS
EVENT|CORONATION
EVENT|GROUND HOG'S DAY
EVENT|THE IRISH SWEEPSTAKES
EVENT|RETIREMENT PARTY
EVENT|POLICEMAN'S BALL
EVENT|HOMECOMING
EVENT|MARDI GRAS
EVENT|NEW YEAR'S EVE PARTY
EVENT|TULIP FESTIVAL
EVENT|ANTIQUE SHOW
EVENT|INDIAN POW-WOW
EVENT|SPRING VACATION
EVENT|WEDDING DAY
EVENT|MORTGAGE BURNING PARTY
EVENT|CORPORATE MERGER
EVENT|BIRTHDAY
EVENT|THE OLYMPIC GAMES
EVENT|COMING OUT PARTY
EVENT|CAMPAIGN FUND DRIVE
EVENT|LINCOLN'S BIRTHDAY
EVENT|BEAUTY PAGEANT
EVENT|SENIOR PROM
EVENT|WIMBLEDON TENNIS TOURNAMENT
EVENT|GRAND OPENING
EVENT|TWO-FOR-ONE SALE
EVENT|SHIP LAUNCHING
EVENT|SILVER ANNIVERSARY
EVENT|TOTAL ECLIPSE OF THE SUN
EVENT|FIRST DATE
EVENT|STATE OF THE UNION ADDRESS
EVENT|MOVIE PREMIERE
EVENT|BABY SHOWER
EVENT|EASTER SUNDAY
EVENT|THE SUPERBOWL
EVENT|FIRST COMMUNION
EVENT|SUNDAY SERVICES
EVENT|BOSTON TEA PARTY
EVENT|GOING OUT OF BUSINESS SALE
EVENT|HOLLOWEEN
EVENT|FAMILY REUNION
EVENT|LINCOLN AND DOUGLAS DEBATE
EVENT|STATE FAIR
EVENT|KENTUCKY DERBY
EVENT|THE CIVIL WAR
EVENT|FIRST SNOWFALL
EVENT|ACADEMY AWARDS
EVENT|PAYDAY
EVENT|THE SEASON OPENER
EVENT|HANUKKAH
EVENT|THE FIRST DAY OF SCHOOL
EVENT|CHRISTMAS EVE
EVENT|THE FIRST DAY OF SPRING
EVENT|SURRENDER AT APPOMATAX
EVENT|SERMON ON THE MOUNT
EVENT|BABY'S FIRST TOOTH
EVENT|HIGH SCHOOL REUNION
EVENT|THE FRENCH REVOLUTION
EVENT|FOURTH OF JULY PICNIC
EVENT|THE LAST SUPPER
EVENT|THE RETURN OF HALLEY'S COMET
EVENT|FRATERNITY RUSH PARTY
EVENT|VALENTINE'S DAY
EVENT|YOM KIPPUR
EVENT|THE PEACE CORPS
EVENT|CHRISTENING
EVENT|NORMANDY INVASION
EVENT|MOON LANDING
EVENT|BARN RAISING
EVENT|BASTILLE DAY
EVENT|WOODSTOCK
EVENT|BOSTON MARATHON
EVENT|CAR AUCTION
EVENT|MILITARY DISCHARGE
EVENT|BACHELOR PARTY
EVENT|MISS UNIVERSE PAGEANT
EVENT|RELIGIOUS RETREAT
EVENT|SPANISH INQUISITION
EVENT|PASSOVER
EVENT|WATERGATE
EVENT|INDIAN RAIN DANCE
EVENT|WORLD CUP SOCCER MATCH
EVENT|HAWAIIAN LUAU
EVENT|LOUISIANA PURCHASE
EVENT|THE AMERICA'S CUP RACE
EVENT|VERSAILLES TREATY
EVENT|FRENCH AND INDIAN WAR
EVENT|TURN OF THE CENTURY
EVENT|SPANISH- AMERICAN WAR
EVENT|ARMED FORCES DAY
EVENT|ARMISTICE DAY
EVENT|MEMORIAL DAY
EVENT|CHINESE NEW YEAR
EVENT|REPORT CARD DAY
EVENT|FIRST DAY ON THE JOB
`;

let wofJuniorAnswers02=
`
PLACE|ACAPULCO MEXICO
PLACE|ALCATRAZ
PLACE|AMAZON RIVER
PLACE|AMUSEMENT PARK
PLACE|ANTARCTICA
PLACE|APARTMENT HOUSE
PLACE|ARCTIC CIRCLE
PLACE|ATLANTIC OCEAN
PLACE|AUDITORIUM
PLACE|BASEBALL HALL OF FAME
PLACE|BEVERLY HILLS
PLACE|BOARDING SCHOOL
PLACE|BOWLING ALLEY
PLACE|CAIRO EGYPT
PLACE|CALGARY CANADA
PLACE|CAPE CANAVERAL
PLACE|CAPE HATTERAS
PLACE|CEMETERY
PLACE|CLASSROOM
PLACE|COBBLESTONE STREET
PLACE|DALLAS TEXAS
PLACE|DAMASCUS SYRIA
PLACE|DAY-CARE CENTER
PLACE|DEAD SEA
PLACE|DEAD-END STREET
PLACE|DEATH VALLEY
PLACE|DENTIST'S OFFICE
PLACE|DISNEYLAND
PLACE|DOWN ESCALATOR
PLACE|DRIVE-IN THEATER
PLACE|DRIVE-IN WINDOW
PLACE|DUBLIN IRELAND
PLACE|DUDE RANCH
PLACE|ELEMENTARY SCHOOL
PLACE|EMPIRE STATE BUILDING
PLACE|ENGLISH CHANNEL
PLACE|EPCOT CENTER
PLACE|FAST-FOOD RESTAURANT
PLACE|FIREHOUSE
PLACE|FLEA MARKET
PLACE|GAS STATION
PLACE|GOLDEN GATE BRIDGE
PLACE|GULF OF MEXICO
PLACE|GYMNASIUM
PLACE|HACKENSACK NEW JERSEY
PLACE|HALIFAX NOVA SCOTIA
PLACE|HARTFORD CONNECTICUT
PLACE|HAWAIIAN ISLANDS
PLACE|HELSINKI FINLAND
PLACE|HIROSHIMA JAPAN
PLACE|HOOVER DAM
PLACE|HOSPITAL EMERGENCY ROOM
PLACE|INFIRMARY
PLACE|JUPITER
PLACE|KODIAK ISLAND
PLACE|LAS VEGAS NEVADA
PLACE|LAUNDROMAT
PLACE|LEANING TOWER OF PISA
PLACE|LEXINGTON KENTUCKY
PLACE|LIBRARY OF CONGRESS
PLACE|LINE OF SCRIMMAGE
PLACE|LONDON ENGLAND
PLACE|LOS ANGELES CALIFORNIA
PLACE|MERCURY
PLACE|MEXICO CITY
PLACE|MIAMI FLORIDA
PLACE|MILKY WAY GALAXY
PLACE|MISSISSIPPI RIVER
PLACE|MORGUE
PLACE|MOUNT EVEREST
PLACE|MOUNT RUSHMORE
PLACE|MOUNT VESUVIUS
PLACE|NEPTUNE
PLACE|NEW YORK CITY
PLACE|NEW ZEALAND
PLACE|NIAGARA FALLS
PLACE|NORFOLK VIRGINIA
PLACE|NORTH AMERICA
PLACE|OBSERVATION DECK
PLACE|OPERA HOUSE
PLACE|OREGON TRAIL
PLACE|ORPHANAGE
PLACE|OSHKOSH WISCONSIN
PLACE|OUTER SPACE
PLACE|PACIFIC OCEAN
PLACE|PALM SPRINGS CALIFORNIA
PLACE|PANAMA CANAL
PLACE|PARIS FRANCE
PLACE|PAWNSHOP
PLACE|PHILIPPINE ISLANDS
PLACE|PRINCETON UNIVERSITY
PLACE|PUBLIC LIBRARY
PLACE|PUERTO RICO
PLACE|RALEIGH NORTH CAROLINA
PLACE|ROCKY MOUNTAINS
PLACE|ROLLER SKATING RINK
PLACE|SACRAMENTO CALIFORNIA
PLACE|SAINT LAWRENCE SEAWAY
PLACE|SAN DIEGO ZOO
PLACE|SAUDI ARABIA
PLACE|SCHOOL CAFETERIA
PLACE|SLEEP-AWAY CAMP
PLACE|SOUNDPROOF ROOM
PLACE|SOUTH AMERICA
PLACE|SPACE MOUNTAIN
PLACE|STATUE OF LIBERTY
PLACE|SUPERMARKET
PLACE|SWITZERLAND
PLACE|THE BIG DIPPER
PLACE|THE GRAND CANYON
PLACE|THE GREAT LAKES
PLACE|THE KREMLIN
PLACE|THE PRINCIPAL'S OFFICE
PLACE|THE WASHINGTON MONUMENT
PLACE|THE WHITE HOUSE
PLACE|UNITED STATES OF AMERICA
PLACE|VIETNAM
PLACE|WASHINGTON D C
PLACE|WORLD TRADE CENTER
PLACE|YANKEE STADIUM
PLACE|YELLOWSTONE NATIONAL PARK
PLACE|YUGOSLAVIA
PLACE|ZIMBABWE RHODESIA
PLACE|ZION NATIONAL PARK
PERSON|A GOOD SPORT
PERSON|ABNER DOUBLEDAY
PERSON|ABRAHAM LINCOLN
PERSON|AIRLINE PASSENGER
PERSON|ALBERT EINSTEIN
PERSON|ALEXANDER HAMILTON
PERSON|AMBASSADOR
PERSON|ANIMATOR
PERSON|ASTRONAUT
PERSON|ATTORNEY AT LAW
PERSON|AUCTIONEER
PERSON|BABE RUTH
PERSON|BABY-SITTER
PERSON|BALLET DANCER
PERSON|BILL COSBY
PERSON|BILLY JOEL
PERSON|BOZO THE CLOWN
PERSON|BOZO THE CLOWN
PERSON|BRAIN SURGEON
PERSON|BRUCE SPRINGSTEEN
PERSON|BULLFIGHTER
PERSON|BURGLAR
PERSON|CANNIBAL
PERSON|CAPTAIN KANGAROO
PERSON|CHAUFFEUR
PERSON|CHRISTOPHER COLUMBUS
PERSON|CHUCK NORRIS
PERSON|COLLEGE PROFESSOR
PERSON|COUCH POTATO
PERSON|DAN AYKROYD
PERSON|DAN MARINO
PERSON|DANIEL BOONE
PERSON|DARRYL STRAWBERRY
PERSON|DAVID COPPERFIELD
PERSON|DAVID LETTERMAN
PERSON|DAVY CROCKETT
PERSON|DENTAL HYGIENIST
PERSON|DEPUTY SHERIFF
PERSON|DISC JOCKEY
PERSON|DOG CATCHER
PERSON|DON JOHNSON
PERSON|DRY CLEANER
PERSON|EAGER BEAVER
PERSON|EDDIE MURPHY
PERSON|ELVIS PRESLEY
PERSON|EXPLORER
PERSON|EYEWITNESS
PERSON|FAMILY DOCTOR
PERSON|FIRST-PRIZE WINNER
PERSON|FORTUNE TELLER
PERSON|FRANCIS SCOTT KEY
PERSON|GENERAL OF THE ARMY
PERSON|GEORGE WASHINGTON
PERSON|GLASS BLOWER
PERSON|GOVERNOR
PERSON|GUIDANCE COUNSELOR
PERSON|HALF BROTHER
PERSON|HANS CHRISTIAN ANDERSEN
PERSON|HEAVYWEIGHT BOXER
PERSON|HIT-AND-RUN DRIVER
PERSON|HITCH-HIKER
PERSON|HOWARD COSELL
PERSON|HYPNOTIST
PERSON|INDIAN CHIEF
PERSON|JACKIE ROBINSON
PERSON|JERRY LEWIS
PERSON|JOHN FITZGERALD KENNEDY
PERSON|JOHN RITTER
PERSON|JOHNNY APPLESEED
PERSON|JUGGLER
PERSON|LITTERBUG
PERSON|LONG DISTANCE OPERATOR
PERSON|LOUIS PASTEUR
PERSON|MAGICIAN
PERSON|MARILYN MONROE
PERSON|MARTIN LUTHER KING
PERSON|MICHAEL J FOX
PERSON|MICHAEL JACKSON
PERSON|MICKEY MANTLE
PERSON|MIGRANT WORKER
PERSON|MOTHER IN LAW
PERSON|MOUNTAIN CLIMBER
PERSON|OFFENSIVE TACKLE
PERSON|OPRAH WINFREY
PERSON|OUTFIELDER
PERSON|PARATROOPER
PERSON|PEE-WEE HERMAN
PERSON|PHIL DONAHUE
PERSON|PICKPOCKET
PERSON|PINCH HITTER
PERSON|PLATOON SERGEANT
PERSON|PLUMBER
PERSON|PONY EXPRESS RIDER
PERSON|PRINCE
PERSON|PRISONER OF WAR
PERSON|PRIVATE DETECTIVE
PERSON|PROOF- READER
PERSON|QUEEN ELIZABETH
PERSON|QUEEN ISABELLA
PERSON|REGISTERED NURSE
PERSON|RONALD REAGAN
PERSON|SCUBA DIVER
PERSON|SECOND COUSIN
PERSON|SECRET AGENT
PERSON|SENIOR CITIZEN
PERSON|SILENT PARTNER
PERSON|SLEEPWALKER
PERSON|SOCIAL STUDIES TEACHER
PERSON|STAMP COLLECTOR
PERSON|STEVEN SPIELBERG
PERSON|STORE MANAGER
PERSON|SUGAR RAY LEONARD
PERSON|SYLVESTER STALLONE
PERSON|TAXICAB DRIVER
PERSON|TAXPAYER
PERSON|TENNIS INSTRUCTOR
PERSON|THE SCHOOL CUSTODIAN
PERSON|THIRD BASE UMPIRE
PERSON|TINA TURNER
PERSON|TOM CRUISE
PERSON|TRAVELING SALESMAN
PERSON|TROUBLE- MAKER
PERSON|VANNA WHITE
PERSON|VOLUNTEER
PERSON|WEIGHT LIFTER
PERSON|WIDE RECEIVER
PERSON|WILLIAM SHATNER
PERSON|WILLIE MAYS
PERSON|WITCH DOCTOR
PERSON|YOGI BERRA
THING|A HOME COMPUTER
THING|A PAIR OF GLOVES
THING|A RUBBER DUCK
THING|ABACUS
THING|ABSENCE NOTE
THING|ACCORDION
THING|ADHESIVE TAPE
THING|AIR-TO-AIR MISSILE
THING|AIRCRAFT CARRIER
THING|AIRPLANE PROPELLER
THING|ALARM CLOCK
THING|ALLIGATOR
THING|AMERICAN FLAG
THING|ANTIFREEZE
THING|AQUALUNG
THING|AQUARIUM
THING|ARITHMETIC BOOK
THING|ASPARAGUS
THING|AUTOGRAPH BOOK
THING|BABY CARRIAGE
THING|BABY'S FIRST TOOTH
THING|BACKGAMMON
THING|BAKED POTATO
THING|BAKER'S DOZEN
THING|BAKING POWDER
THING|BALLPOINT PEN
THING|BARBECUE GRILL
THING|BARBIE DOLL
THING|BASE HIT
THING|BASEBALL BAT
THING|BASEBALL DIAMOND
THING|BASKETBALL
THING|BATHING SUIT
THING|BEDTIME STORY
THING|BILL OF RIGHTS
THING|BINOCULARS
THING|BIRTH CERTIFICATE
THING|BLACK AND BLUE MARK
THING|BLACK WIDOW SPIDER
THING|BLOOD VESSEL
THING|BOBBY PIN
THING|BOOBY PRIZE
THING|BOOMERANG
THING|BOOSTER SHOT
THING|BROCCOLI
THING|BUBBLE BATH
THING|BUBBLE GUM
THING|BULLETIN BOARD
THING|BULLETPROOF VEST
THING|BUMPER STICKER
THING|BUTTERFLY
THING|BUTTONHOLE
THING|CABBAGE PATCH DOLL
THING|CABIN CRUISER
THING|CACTUS PLANT
THING|CAESAR SALAD
THING|CALAMINE LOTION
THING|CAN OPENER
THING|CANTALOUPE
THING|CARBON DIOXIDE GAS
THING|CARNIVAL
THING|CASH REGISTER
THING|CATERPILLAR
THING|CEMENT MIXER
THING|CHALKBOARD
THING|CHARLEY HORSE
THING|CHECKING ACCOUNT
THING|CHECKOUT LINE
THING|CHICKEN POX
THING|CHIMPANZEE
THING|CHOCOLATE PUDDING
THING|CHRISTMAS STOCKING
THING|CITIZEN'S BAND RADIO
THING|CLAM CHOWDER
THING|COCA-COLA
THING|COCKROACH
THING|COLORING BOOK
THING|COMIC BOOK
THING|COMPACT DISC
THING|COMPOUND WORD
THING|CONTACT LENS
THING|COONSKIN CAP
THING|CORDLESS TELEPHONE
THING|CORN ON THE COB
THING|CORVETTE
THING|COSTUME JEWELRY
THING|COTTAGE CHEESE
THING|COTTON CANDY
THING|COUNTERFEIT MONEY
THING|COUNTRY AND WESTERN MUSIC
THING|COVERED WAGON
THING|CRACKER JACK
THING|CRANBERRY SAUCE
THING|CRASH HELMET
THING|CREDIT APPLICATION
THING|CREDIT CARD
THING|CREPE PAPER
THING|CROSSWORD PUZZLE
THING|DADDY LONGLEGS
THING|DAILY NEWSPAPER
THING|DART BOARD
THING|DENTAL FLOSS
THING|DEPOSIT SLIP
THING|DIACRITICAL MARK
THING|DICTIONARY
THING|DIESEL ENGINE
THING|DIGITAL WATCH
THING|DOG BISCUIT
THING|DOG COLLAR
THING|DOGGIE BAG
THING|DOUBLE HEADER
THING|DRAWBRIDGE
THING|DRIP-DRY SHIRT
THING|DRIVER'S LICENSE
THING|DUFFEL BAG
THING|EGG ROLL
THING|EJECTION SEAT
THING|ELECTRIC CHAIR
THING|ELECTRIC GUITAR
THING|ELECTRIC TRAIN SET
THING|ELECTRON MICROSCOPE
THING|ENGAGEMENT RING
THING|EQUAL SIGN
THING|ESCALATOR
THING|EVENING STAR
THING|EXTENSION CORD
THING|EYE SHADOW
THING|FERRIS WHEEL
THING|FISHING ROD
THING|FLAT TIRE
THING|FLUORESCENT LIGHT
THING|FLUORIDATED WATER
THING|FLYING FISH
THING|FOOD PROCESSOR
THING|FOOTBALL HELMET
THING|FORKLIFT TRUCK
THING|FORTUNE COOKIE
THING|FOUR-LEAF CLOVER
THING|FRENCH TOAST
THING|FRIED RICE
THING|FUNNY BONE
THING|GEIGER COUNTER
THING|GERMAN SHEPHERD DOG
THING|GLASS BOTTOM BOAT
THING|GLOVE COMPARTMENT
THING|GLOWWORM
THING|GRAND SLAM HOME RUN
THING|GRANDFATHER CLOCK
THING|GRANOLA BAR
THING|GRASSHOPPER
THING|GUIDE DOG
THING|GUINEA PIG
THING|HALF-DOLLAR
THING|HAM AND CHEESE SANDWICH
THING|HAMBURGER
THING|HAMMERHEAD SHARK
THING|HAWAIIAN SHIRT
THING|HELICOPTER
THING|HERMIT CRAB
THING|HEXAGON
THING|HIGH SCHOOL DIPLOMA
THING|HOCKEY PUCK
THING|HOLOGRAM
THING|HOME PLATE
THING|HOMEMADE APPLE PIE
THING|HOMEWORK ASSIGNMENT
THING|HOT BUTTERED POPCORN
THING|HOT DOG
THING|HOT FUDGE SUNDAE
THING|HURRICANE
THING|INSURANCE POLICY
THING|IRONING BOARD
THING|JACK-IN- THE-BOX
THING|JACK-O- LANTERN
THING|JAPANESE BEETLE
THING|JELLY DOUGHNUT
THING|JELLYFISH
THING|JIGSAW PUZZLE
THING|JUMP ROPE
THING|JUMPING JACK
THING|KANGAROO
THING|KENTUCKY FRIED CHICKEN
THING|KITCHEN TABLE
THING|KNITTING NEEDLES
THING|KOALA BEAR
THING|LAUNCHING PAD
THING|LAWN MOWER
THING|LEAD PENCIL
THING|LEAKY FAUCET
THING|LEMONADE STAND
THING|LIBERTY BELL
THING|LICENSE PLATE
THING|LICORICE CANDY
THING|LIE- DETECTOR TEST
THING|LIFE PRESERVER
THING|LIGHTNING BUG
THING|LIGHTNING ROD
THING|LOOSE-LEAF NOTEBOOK
THING|LOTTERY TICKET
THING|LOW-CALORIE DIET
THING|LUCKY CHARM
THING|LUNAR ROVER
THING|MACARONI AND CHEESE CASSEROLE
THING|MAGAZINE
THING|MAGNIFYING GLASS
THING|MEXICAN SOMBRERO
THING|MICROWAVE OVEN
THING|MILK OF MAGNESIA
THING|MODEL AIRPLANE
THING|MODEL RAILROAD
THING|MONEY ORDER
THING|MORNING GLORY
THING|MORSE CODE
THING|MOUSETRAP
THING|MOVIE FILM PROJECTOR
THING|MULTIPLE CHOICE QUIZ
THING|MUSTACHE COMB
THING|NATIONAL ANTHEM
THING|NEW YEAR'S RESOLUTION
THING|NUCLEAR SUBMARINE
THING|OCTOPUS
THING|OPTICAL ILLUSION
THING|ORANGE JUICE
THING|ORANGUTAN
THING|OUTBOARD MOTOR
THING|OVERTIME PAY
THING|PAJAMA BOTTOMS
THING|PARACHUTE
THING|PEANUT BUTTER AND JELLY SANDWICH
THING|PEN AND PENCIL SET
THING|PENCIL SHARPENER
THING|PEPPERONI PIZZA
THING|PERMISSION SLIP
THING|PHOTOCOPY MACHINE
THING|PICK-UP TRUCK
THING|PIGGY BANK
THING|PIN CUSHION
THING|PINBALL MACHINE
THING|PINEAPPLE UPSIDE-DOWN CAKE
THING|PING PONG TABLE
THING|PLASTER OF PARIS
THING|PLAY DOH
THING|POCKET CALCULATOR
THING|POISON IVY
THING|POLAR BEAR
THING|POLAROID CAMERA
THING|POPCORN
THING|POTBELLIED STOVE
THING|PRACTICAL JOKE
THING|PRAYING MANTIS
THING|PREPOSITION
THING|PUMPKIN PIE
THING|PUNCTUATION MARK
THING|PUSSY WILLOW
THING|QUARTZ WATCH
THING|QUESTION MARK
THING|QUICKSAND
THING|RAILROAD TIMETABLE
THING|REAR-VIEW MIRROR
THING|REPORT CARD
THING|RICE PUDDING
THING|RINGTOSS
THING|ROCK AND ROLL MUSIC
THING|ROCKING HORSE
THING|ROLLER COASTER
THING|ROMAN NUMERAL
THING|RUBBER BAND
THING|SABER- TOOTHED TIGER
THING|SAINT BERNARD DOG
THING|SALTWATER TAFFY
THING|SCHOOL BUS
THING|SCIENCE EXPERIMENT
THING|SCREWDRIVER
THING|SELF- CLEANING OVEN
THING|SEVEN- LAYER CAKE
THING|SHOCK ABSORBER
THING|SHOULDER HOLSTER
THING|SIX-INCH RULER
THING|SKATEBOARD
THING|SLIDING GLASS DOOR
THING|SNAPPING TURTLE
THING|SPACE SHUTTLE
THING|SPIDER WEB
THING|STATION WAGON
THING|STEAM ENGINE
THING|STEAM SHOVEL
THING|STEPPING- STONE
THING|STEREO SYSTEM
THING|STOMACH ACHE
THING|STRAWBERRY ICE CREAM
THING|SUBMARINE PERISCOPE
THING|SUBWAY TRAIN
THING|SURFBOARD
THING|SWEATSHIRT
THING|SWEET POTATO
THING|SWIMMING POOL
THING|SYNTHESIZER
THING|TABLE OF CONTENTS
THING|TALCUM POWDER
THING|TAPE MEASURE
THING|TEDDY BEAR
THING|TEE SHIRT
THING|TELEPHONE DIRECTORY
THING|TELESCOPE
THING|TELEVISION ANTENNA
THING|TELEVISION COMMERCIAL
THING|TELEVISION SET
THING|TEN-SPEED BICYCLE
THING|TENNIS RACKET
THING|THE ACE OF SPADES
THING|THE DISNEY CHANNEL
THING|THE FREEZING POINT
THING|THE MAYFLOWER
THING|THERMOMETER
THING|THERMOS BOTTLE
THING|THIRD- DEGREE BURN
THING|TOASTED MARSHMALLOW
THING|TOBOGGAN
THING|TOMAHAWK
THING|TOMATO JUICE
THING|TOOTSIE ROLL
THING|TOPIC SENTENCE
THING|TOTEM POLE
THING|TOUCHDOWN
THING|TRAFFIC SIGNAL
THING|TRAVELER'S CHECK
THING|TREASURY BOND
THING|TREE HOUSE
THING|TRICERATOPS
THING|TUNA FISH SANDWICH
THING|TURKEY DRUMSTICK
THING|TWO-WAY MIRROR
THING|TYPEWRITER
THING|UMBRELLA
THING|VACUUM CLEANER
THING|VIDEO CASSETTE RECORDER
THING|WASHING MACHINE
THING|WASTEBASKET
THING|WATCHDOG
THING|WATER FOUNTAIN
THING|WATERBED
THING|WATERMELON
THING|WEDDING RING
THING|WEEPING WILLOW TREE
THING|WHIPPED CREAM CAKE
THING|WHOLE NUMBER
THING|WISDOM TOOTH
THING|WORD PROCESSOR
THING|WRISTWATCH
THING|X-RAY MACHINE
THING|XYLOPHONE
THING|ZIP CODE
FICTIONAL CHARACTER|ABOMINABLE SNOWMAN
FICTIONAL CHARACTER|BEETLE BAILEY
FICTIONAL CHARACTER|BETTY BOOP
FICTIONAL CHARACTER|BUGS BUNNY
FICTIONAL CHARACTER|CAPTAIN HOOK
FICTIONAL CHARACTER|CAPTAIN POWER
FICTIONAL CHARACTER|CASPER THE FRIENDLY GHOST
FICTIONAL CHARACTER|CHARLIE BROWN
FICTIONAL CHARACTER|COOKIE MONSTER
FICTIONAL CHARACTER|COUNT DRACULA
FICTIONAL CHARACTER|DARTH VADER
FICTIONAL CHARACTER|DENNIS THE MENACE
FICTIONAL CHARACTER|DENNIS THE MENACE
FICTIONAL CHARACTER|DONALD DUCK
FICTIONAL CHARACTER|EASTER BUNNY
FICTIONAL CHARACTER|EBENEZER SCROOGE
FICTIONAL CHARACTER|ELMER FUDD
FICTIONAL CHARACTER|FATHER TIME
FICTIONAL CHARACTER|FRED FLINTSTONE
FICTIONAL CHARACTER|GARFIELD
FICTIONAL CHARACTER|HEATHCLIFF
FICTIONAL CHARACTER|HERCULES
FICTIONAL CHARACTER|INDIANA JONES
FICTIONAL CHARACTER|JACK FROST
FICTIONAL CHARACTER|KERMIT THE FROG
FICTIONAL CHARACTER|KING KONG
FICTIONAL CHARACTER|LUKE SKYWALKER
FICTIONAL CHARACTER|MARMADUKE
FICTIONAL CHARACTER|MICKEY MOUSE
FICTIONAL CHARACTER|MISS PIGGY
FICTIONAL CHARACTER|MOTHER GOOSE
FICTIONAL CHARACTER|MR POTATO HEAD
FICTIONAL CHARACTER|OPTIMUS PRIME
FICTIONAL CHARACTER|PAPA SMURF
FICTIONAL CHARACTER|PAUL BUNYAN
FICTIONAL CHARACTER|PERRY MASON
FICTIONAL CHARACTER|PETER RABBIT
FICTIONAL CHARACTER|POPEYE THE SAILOR MAN
FICTIONAL CHARACTER|PORKY PIG
FICTIONAL CHARACTER|PUNKY BREWSTER
FICTIONAL CHARACTER|RAINBOW BRITE
FICTIONAL CHARACTER|ROAD RUNNER
FICTIONAL CHARACTER|ROBIN HOOD
FICTIONAL CHARACTER|RONALD MCDONALD
FICTIONAL CHARACTER|SANTA CLAUS
FICTIONAL CHARACTER|SHERLOCK HOLMES
FICTIONAL CHARACTER|SMOKEY THE BEAR
FICTIONAL CHARACTER|SNOW WHITE
FICTIONAL CHARACTER|SPEEDY GONZALEZ
FICTIONAL CHARACTER|SPIDERMAN
FICTIONAL CHARACTER|STRAWBERRY SHORTCAKE
FICTIONAL CHARACTER|SUPERMAN
FICTIONAL CHARACTER|SYLVESTER THE CAT
FICTIONAL CHARACTER|TARZAN KING OF THE JUNGLE
FICTIONAL CHARACTER|THE INCREDIBLE HULK
FICTIONAL CHARACTER|THE LONE RANGER
FICTIONAL CHARACTER|THE PINK PANTHER
FICTIONAL CHARACTER|TOM SAWYER
FICTIONAL CHARACTER|TONY THE TIGER
FICTIONAL CHARACTER|TOOTH FAIRY
FICTIONAL CHARACTER|WICKED WITCH OF THE EAST
FICTIONAL CHARACTER|WONDER WOMAN
FICTIONAL CHARACTER|WOODY WOODPECKER
FICTIONAL CHARACTER|YOSEMITE SAM
PHRASE|A CHANGE OF PACE
PHRASE|A DIME A DOZEN
PHRASE|A DROP IN THE BUCKET
PHRASE|A FORK IN THE ROAD
PHRASE|A FROG IN MY THROAT
PHRASE|A HOLE IN ONE
PHRASE|A WEALTH OF INFORMATION
PHRASE|ABOUT FACE
PHRASE|ADAM'S APPLE
PHRASE|ALL ABOARD
PHRASE|AROUND THE CLOCK
PHRASE|BACK-SEAT DRIVER
PHRASE|BE MY VALENTINE
PHRASE|BEHIND THE EIGHT BALL
PHRASE|BET YOU CAN'T EAT JUST ONE
PHRASE|BOMBS AWAY
PHRASE|BREAKA PROMISE
PHRASE|BUCKLE UP FOR SAFETY
PHRASE|BURN A HOLE IN ONE'S POCKET
PHRASE|BY TRIAL AND ERROR
PHRASE|CATCH A COLD
PHRASE|CLEAN UP YOUR ROOM
PHRASE|CLOSE CAPTIONED
PHRASE|CROSS AT THE GREEN
PHRASE|DO NOT DISTURB
PHRASE|DON'T COUNT ON IT
PHRASE|DOWN TO EARTH
PHRASE|DRIVE A HARD BARGAIN
PHRASE|E T PHONE HOME
PHRASE|EASY COME EASY GO
PHRASE|ENTER AT YOUR OWN RISK
PHRASE|FINDERS KEEPERS LOSERS WEEPERS
PHRASE|FINGER LICKING GOOD
PHRASE|FIT AS A FIDDLE
PHRASE|FLY OFF THE HANDLE
PHRASE|FOLLOW THE LEADER
PHRASE|FREEZE IN YOUR TRACKS
PHRASE|GENERATION GAP
PHRASE|GET READY GET SET GO
PHRASE|GO FLY A KITE
PHRASE|GOOD GRIEF CHARLIE BROWN
PHRASE|HANG IN THERE
PHRASE|HANG TEN
PHRASE|HAPPY BIRTHDAY
PHRASE|HAPPY HANUKKAH
PHRASE|HAPPY NEW YEAR
PHRASE|HAVE A NICE DAY
PHRASE|HAVE A SCREW LOOSE
PHRASE|HAVE THE LAST LAUGH
PHRASE|HE'S PULLING YOUR LEG
PHRASE|HEADS OR TAILS
PHRASE|HEIGH-HO HEIGH-HO
PHRASE|HELP WANTED
PHRASE|HIDE AND SEEK
PHRASE|HOCUS- POCUS
PHRASE|HONESTY IS THE BEST POLICY
PHRASE|HOW'S IT GOING
PHRASE|HUGS AND KISSES
PHRASE|I CANNOT TELL A LIE
PHRASE|I HEARD IT THROUGH THE GRAPEVINE
PHRASE|I LOVE YOU
PHRASE|I'LL DO IT TOMORROW
PHRASE|IN THE DOGHOUSE
PHRASE|IN THE LAP OF LUXURY
PHRASE|IT WAS A CLOSE CALL
PHRASE|IT WAS AN ACCIDENT
PHRASE|IT'S A SMALL WORLD
PHRASE|IT'S RAINING CATS AND DOGS
PHRASE|KEEP A STIFF UPPER LIP
PHRASE|KEEP ONE'S PROMISE
PHRASE|LET YOUR HAIR DOWN
PHRASE|LIKE A FISH OUT OF WATER
PHRASE|LOOK IT UP
PHRASE|LOSE ONE'S TEMPER
PHRASE|MAKE AN EXCEPTION
PHRASE|MAKE UP YOUR MIND
PHRASE|MAY THE FORCE BE WITH YOU
PHRASE|MEDAL OF HONOR
PHRASE|MEET FACE TO FACE
PHRASE|MERRY CHRISTMAS
PHRASE|MY TWO CENTS WORTH
PHRASE|NO PROBLEM
PHRASE|NO TRESPASSING
PHRASE|NO VACANCY
PHRASE|NUTTY AS A FRUITCAKE
PHRASE|ODDS AND EVENS
PHRASE|ON TOP OF THE WORLD
PHRASE|ONLY YOU CAN PREVENT FOREST FIRES
PHRASE|OUT OF BREATH
PHRASE|PIG OUT
PHRASE|PITCH A TENT
PHRASE|PLAY FAIR AND SQUARE
PHRASE|PLAY THE PIANO
PHRASE|PUT THE FROSTING ON THE CAKE
PHRASE|RACK YOUR BRAINS
PHRASE|SET A GOOD EXAMPLE
PHRASE|SHAME ON YOU
PHRASE|SIMON SAYS
PHRASE|SNAP CRACKLE AND POP
PHRASE|SO FAR SO GOOD
PHRASE|STAND ON ONE'S OWN TWO FEET
PHRASE|STICK-IN- THE-MUD
PHRASE|STOP DROP AND ROLL
PHRASE|STOP LOOK AND LISTEN
PHRASE|STRAIGHT FROM THE HORSE'S MOUTH
PHRASE|SURF'S UP
PHRASE|TAKE A COFFEE BREAK
PHRASE|THE EYE OF THE HURRICANE
PHRASE|THERE'S NOTHING TO IT
PHRASE|THINK IT OVER
PHRASE|THIS IS NO LAUGHING MATTER
PHRASE|THROW ONE'S WEIGHT AROUND
PHRASE|TO THE ENDS OF THE EARTH
PHRASE|TOPSY-TURVY
PHRASE|TRICK OR TREAT
PHRASE|TURN GREEN WITH ENVY
PHRASE|WEAR A LONG FACE
PHRASE|WHAT TIME IS IT
PHRASE|WHAT YOU SEE IS WHAT YOU GET
PHRASE|WHAT'S UP DOC
PHRASE|WITH LIBERTY AND JUSTICE FOR ALL
PHRASE|YOU SHOULD KNOW BETTER
THINGS|ANIMAL CRACKERS
THINGS|BACON AND EGGS
THINGS|BASEBALL CARDS
THINGS|BOW AND ARROW
THINGS|BREAD AND BUTTER
THINGS|BUNK BEDS
THINGS|CANDY CANES
THINGS|CHEERIOS
THINGS|CHICKEN AND DUMPLINGS
THINGS|CHICKEN MCNUGGETS
THINGS|CHINESE CHECKERS
THINGS|CHOCOLATE CHIP COOKIES
THINGS|COMPUTER GAMES
THINGS|CORN FLAKES
THINGS|CREAM AND SUGAR
THINGS|DINOSAURS
THINGS|EUCALYPTUS LEAVES
THINGS|FALSE TEETH
THINGS|FRENCH FRIES
THINGS|GARBAGE PAIL KIDS CARDS
THINGS|GIRL SCOUT COOKIES
THINGS|GOLF CLUBS
THINGS|HAMMER AND NAILS
THINGS|HANDCUFFS
THINGS|HORSE AND BUGGY
THINGS|HORSESHOES
THINGS|HOT WHEELS
THINGS|JELLYBEANS
THINGS|KLEENEX TISSUES
THINGS|LOBSTER TAILS
THINGS|MILK AND COOKIES
THINGS|NINA PINTA AND SANTA MARIA
THINGS|PENCILS
THINGS|PEPPERMINT LIFE SAVERS
THINGS|PISTACHIO NUTS
THINGS|PLAYING CARDS
THINGS|POLO SHIRTS
THINGS|PORK AND BEANS
THINGS|POTATO CHIPS
THINGS|QUOTATION MARKS
THINGS|RED BLOOD CELLS
THINGS|REMOTE CONTROL CARS
THINGS|ROMAN CANDLES
THINGS|SALT AND PEPPER
THINGS|SALTED PRETZELS
THINGS|SALTINE CRACKERS
THINGS|SCRAMBLED EGGS
THINGS|SMOKE SIGNALS
THINGS|SNOWBALLS
THINGS|SPAGHETTI AND MEATBALLS
THINGS|SPRING AND MATTRESS
THINGS|SUNFLOWER SEEDS
THINGS|SUNGLASSES
THINGS|TROPICAL FISH
THINGS|VENETIAN BLINDS
THINGS|VIDEO GAMES
THINGS|VITAMIN PILLS
THINGS|WAFFLES AND ICE CREAM
TITLE|A BOY NAMED CHARLIE BROWN
TITLE|ALICE IN WONDERLAND
TITLE|AN AMERICAN TAIL
TITLE|BACK TO THE FUTURE
TITLE|BEAUTY AND THE BEAST
TITLE|CINDERELLA
TITLE|CROCODILE DUNDEE
TITLE|DR JEKYLL AND MR HYDE
TITLE|FAMILY TIES
TITLE|FRAGGLE ROCK
TITLE|FROM RUSSIA WITH LOVE
TITLE|FROSTY THE SNOWMAN
TITLE|GOD BLESS AMERICA
TITLE|GREMLINS
TITLE|GUINNESS BOOK OF WORLD RECORDS
TITLE|GULLIVER'S TRAVELS
TITLE|HANSEL AND GRETEL
TITLE|HEAD OF THE CLASS
TITLE|HEY THERE IT'S YOGI BEAR
TITLE|HICKORY DICKORY DOCK
TITLE|HOT CROSS BUNS
TITLE|HOWARD THE DUCK
TITLE|KNIGHT RIDER
TITLE|LADY AND THE TRAMP
TITLE|LITTLE TOMMY TUCKER
TITLE|MARY MARY QUITE CONTRARY
TITLE|MARY POPPINS
TITLE|MASTERS OF THE UNIVERSE
TITLE|MONOPOLY
TITLE|MURDER SHE WROTE
TITLE|MY THREE SONS
TITLE|OLD MOTHER HUBBARD
TITLE|OVER THE TOP
TITLE|PERFECT STRANGERS
TITLE|PETER PETER PUMPKIN EATER
TITLE|PIN THE TAIL ON THE DONKEY
TITLE|PINOCCHIO
TITLE|PLANET OF THE APES
TITLE|POP GOES THE WEASEL
TITLE|RAMBO
TITLE|RETURN OF THE JEDI
TITLE|RING AROUND THE ROSIE
TITLE|RIP VAN WINKLE
TITLE|ROBINSON CRUSOE
TITLE|RUDOLPH THE RED-NOSED REINDEER
TITLE|SCRABBLE
TITLE|SESAME STREET
TITLE|SLEEPING BEAUTY
TITLE|SUPER MARIO BROTHERS
TITLE|THE BAD NEWS BEARS
TITLE|THE BRADY BUNCH
TITLE|THE EMPEROR'S NEW CLOTHES
TITLE|THE FACTS OF LIFE
TITLE|THE FARMER IN THE DELL
TITLE|THE GOONIES
TITLE|THE KARATE KID
TITLE|THE MUPPETS TAKE MANHATTAN
TITLE|THE NUTCRACKER SUITE
TITLE|THE SOUND OF MUSIC
TITLE|THE STAR- SPANGLED BANNER
TITLE|THE THREE LITTLE PIGS
TITLE|THE WIZARD OF OZ
TITLE|TREASURE ISLAND
TITLE|TWINKLE TWINKLE LITTLE STAR
TITLE|WHEEL OF FORTUNE
TITLE|WHO KILLED COCK ROBIN
TITLE|WINNIE THE POOH
TITLE|WYNKEN BLYNKEN AND NOD
TITLE|YANKEE DOODLE DANDY
PEOPLE|ALGONQUIN INDIANS
PEOPLE|BOARD OF HEALTH
PEOPLE|BOY SCOUTS OF AMERICA
PEOPLE|BRIDE AND GROOM
PEOPLE|COAST GUARD
PEOPLE|CONTINENTAL CONGRESS
PEOPLE|CURLY MOE AND LARRY
PEOPLE|DURAN DURAN
PEOPLE|FAMILY CIRCLE
PEOPLE|IDENTICAL TWINS
PEOPLE|LITTLE LEAGUE BASEBALL TEAM
PEOPLE|MIAMI DOLPHINS
PEOPLE|MIDGET FOOTBALL TEAM
PEOPLE|MOTLEY CRUE
PEOPLE|NATIONAL FOOTBALL LEAGUE
PEOPLE|NATIONAL GUARD
PEOPLE|NEW YORK METS
PEOPLE|QUINTUPLETS
PEOPLE|SHAWNEE INDIANS
PEOPLE|SIAMESE TWINS
PEOPLE|SWAT TEAM
PEOPLE|SYMPHONY ORCHESTRA
PEOPLE|THE ALLMAN BROTHERS
PEOPLE|THE BEACH BOYS
PEOPLE|THE BEATLES
PEOPLE|THE FAT BOYS
PEOPLE|THE THREE WISE MEN
PEOPLE|WASHINGTON REDSKINS
PEOPLE|WORLD WRESTLING FEDERATION
EVENT|ASH WEDNESDAY
EVENT|ASSEMBLY PROGRAM
EVENT|BAR MITZVAH
EVENT|BIRTHDAY PARTY
EVENT|BREAK DANCING CONTEST
EVENT|CHRISTENING
EVENT|CHRISTMAS EVE
EVENT|CHRISTMAS VACATION
EVENT|CIVIL WAR
EVENT|COLLEGE GRADUATION
EVENT|COLUMBUS DAY
EVENT|COURT MARTIAL
EVENT|DRESS REHEARSAL
EVENT|EARTHQUAKE
EVENT|EASTER EGG HUNT
EVENT|EASTER SUNDAY
EVENT|FIRE PREVENTION WEEK
EVENT|FIRST ANNIVERSARY
EVENT|FOURTH OF JULY
EVENT|GARAGE SALE
EVENT|HALLOWEEN
EVENT|HIGH SCHOOL PROM
EVENT|HOLY COMMUNION
EVENT|LEAP YEAR
EVENT|MASQUERADE PARTY
EVENT|MEMORIAL DAY
EVENT|MISS AMERICA PAGEANT
EVENT|MONDAY NIGHT FOOTBALL
EVENT|MOTHER'S DAY
EVENT|NIGHT OF THE FULL MOON
EVENT|OPEN- HEART SURGERY
EVENT|ORANGE BOWL PARADE
EVENT|PAJAMA PARTY
EVENT|PRESIDENTS DAY
EVENT|ROCK CONCERT
EVENT|SHOOTING STAR
EVENT|SOCCER GAME
EVENT|SOLAR ECLIPSE
EVENT|SPACE WALK
EVENT|SPRING BREAK
EVENT|SUMMER VACATION
EVENT|SUPER BOWL GAME
EVENT|SURPRISE PARTY
EVENT|SWEET SIXTEEN PARTY
EVENT|THE FIRST DAY OF SCHOOL
EVENT|THE WORLD SERIES
EVENT|THREE-RING CIRCUS
EVENT|TRACK AND FIELD DAY
EVENT|TREASURE HUNT
EVENT|VALENTINE'S DAY
EVENT|VETERANS DAY
EVENT|WEDDING CEREMONY
EVENT|WORLD CUP SOCCER MATCH
FICTIONAL CHARACTERS|BATMAN AND ROBIN
FICTIONAL CHARACTERS|BERENSTAIN BEARS
FICTIONAL CHARACTERS|BERT AND ERNIE
FICTIONAL CHARACTERS|CARE BEARS
FICTIONAL CHARACTERS|GUMBY AND POKEY
FICTIONAL CHARACTERS|KNIGHTS OF THE ROUND TABLE
FICTIONAL CHARACTERS|RAGGEDY ANN AND ANDY
FICTIONAL CHARACTERS|SNOOPY AND WOODSTOCK
FICTIONAL CHARACTERS|THE A TEAM
FICTIONAL CHARACTERS|THE CALIFORNIA RAISINS
FICTIONAL CHARACTERS|THE CHIPMUNKS
FICTIONAL CHARACTERS|THE FLINTSTONE KIDS
FICTIONAL CHARACTERS|THE LITTLE RASCALS
FICTIONAL CHARACTERS|THE WUZZLES
FICTIONAL CHARACTERS|TOM AND JERRY
`;

let wofFamilyAnswers02 = 
`
PLACE|ALLIGATOR ALLEY
PLACE|AMAZON JUNGLE
PLACE|ANTIOCH
PLACE|APPLE ORCHARD
PLACE|ART GALLERY
PLACE|AUTO BODY SHOP
PLACE|BADEN BADEN WEST GERMANY
PLACE|BATON ROUGE LOUISIANA
PLACE|CARTHAGE
PLACE|CENTRAL PARK
PLACE|CHERNOBYL
PLACE|CHESAPEAKE BAY
PLACE|CHILD CARE CENTER
PLACE|CLUB MED
PLACE|COLLEGE CAMPUS
PLACE|DAIRY FARM
PLACE|DEAD SEA
PLACE|DEATH VALLEY
PLACE|DES MOINES IOWA
PLACE|DRESSING ROOM
PLACE|DUBROVNIK YUGOSLAVIA
PLACE|DUDE RANCH
PLACE|EUREKA CALIFORNIA
PLACE|FARMERS MARKET
PLACE|FIJI ISLANDS
PLACE|FRANKFURT GERMANY
PLACE|FRATERNITY HOUSE
PLACE|FRONT PORCH
PLACE|FUNERAL HOME
PLACE|GOBI DESERT
PLACE|GRAND FORKS NORTH DAKOTA
PLACE|GRAND TETON NATIONAL PARK
PLACE|GREENWICH CONNECTICUT
PLACE|GUAYAQUIL ECUADOR
PLACE|HEATHROW AIRPORT
PLACE|HOME TEAM DUGOUT
PLACE|HOSPITAL RECOVERY ROOM
PLACE|INFANT NURSERY
PLACE|JEFFERSON CITY MISSOURI
PLACE|JERUSALEM
PLACE|JOHNSON SPACE CENTER
PLACE|KALAMAZOO MICHIGAN
PLACE|KOWLOON
PLACE|KUALA LUMPUR
PLACE|LA BREA TAR PITS
PLACE|LIBRARY OF CONGRESS
PLACE|LIBRARY REFERENCE ROOM
PLACE|LINCOLN MEMORIAL
PLACE|LONG ISLAND SOUND
PLACE|MAPLE LEAF GARDEN
PLACE|MATERNITY WARD
PLACE|MAUI HAWAII
PLACE|MECCA
PLACE|MEDICAL SCHOOL
PLACE|MINIATURE GOLF COURSE
PLACE|MINNEAPOLIS MINNESOTA
PLACE|MOBILE HOME PARK
PLACE|MONTERREY MEXICO
PLACE|MOUNT FUJI
PLACE|MOUNT RAINIER NATIONAL PARK
PLACE|MOVIE STUDIO BACK LOT
PLACE|MYKONOS
PLACE|NON-SMOKING SECTION
PLACE|NOTRE DAME CATHEDRAL
PLACE|NURSING HOME
PLACE|OCALA NATIONAL FOREST
PLACE|OPERATING ROOM
PLACE|ORCHESTRA PIT
PLACE|PAN- AMERICAN HIGHWAY
PLACE|PARADISE ISLAND
PLACE|PEOPLE'S REPUBLIC OF CHINA
PLACE|RACKETBALL COURT
PLACE|RALEIGH NORTH CAROLINA
PLACE|RED SQUARE
PLACE|REFRESHMENT STAND
PLACE|SAINT ANDREWS GOLF COURSE
PLACE|SAINT AUGUSTINE FLORIDA
PLACE|SAN JOSE COSTA RICA
PLACE|SANTA FE TRAIL
PLACE|SAN DIEGO ZOO
PLACE|SCHENECTADY NEW YORK
PLACE|SCHOOL CAFETERIA
PLACE|SCHOOL GYMNASIUM
PLACE|SHEA STADIUM
PLACE|SHOPPING CENTER PARKING LOT
PLACE|SIOUX FALLS SOUTH DAKOTA
PLACE|SPORTS COMPLEX
PLACE|STADIUM BLEACHERS
PLACE|STADIUM PRESSBOX
PLACE|STRAIT OF BOSPORUS
PLACE|STRATFORD ON AVON
PLACE|SUBWAY STATION
PLACE|SWEETWATER TEXAS
PLACE|SYRIA
PLACE|TEXARKANA
PLACE|THE FORBIDDEN CITY
PLACE|THE GALAPAGOS ISLANDS
PLACE|TIEN AN MEN SQUARE
PLACE|TOY DEPARTMENT
PLACE|VANCOUVER BRITISH COLUMBIA
PLACE|VENICE ITALY
PLACE|WALLA WALLA WASHINGTON
PLACE|WILMINGTON DELAWARE
PLACE|WINNIPEG MANITOBA CANADA
PLACE|YANGTZE RIVER
PLACE|YUKON NORTHWEST TERRITORY
PERSON|AEROBICS INSTRUCTOR
PERSON|ALEXANDER DUMAS
PERSON|ALEXANDER HAIG
PERSON|AN EQUAL- OPPORTUNITY EMPLOYER
PERSON|ANDREW JOHNSON
PERSON|ANDRE AGASSI
PERSON|ANIMAL TRAINER
PERSON|ARISTOCRAT
PERSON|ARMCHAIR QUARTERBACK
PERSON|ARMY BRAT
PERSON|ARSENIO HALL
PERSON|ASTRONOMER
PERSON|BENJAMIN HARRISON
PERSON|BLUES SINGER
PERSON|BOXING REFEREE
PERSON|BROOKS ROBINSON
PERSON|CAPTAIN JAMES COOK
PERSON|CARL YASTRZEMSKI
PERSON|CATHERINE DE MEDICI
PERSON|CATTLE RANCHER
PERSON|CHARLEMAGNE
PERSON|CHRISTOPHER COLUMBUS
PERSON|CONGRESSMAN
PERSON|CORBIN BERNSEN
PERSON|CRUSADER
PERSON|DANIEL WEBSTER
PERSON|DAVID GLASGOW FARRAGUT
PERSON|DEER HUNTER
PERSON|DENTAL SURGEON
PERSON|DIAN FOSSEY
PERSON|DONALD TRUMP
PERSON|DRESSMAKER
PERSON|DRUG COUNSELOR
PERSON|DR RUTH WESTHEIMER
PERSON|EGYPTIAN PHARAOH
PERSON|ELIAS HOWE
PERSON|ELIZABETH DOLE
PERSON|EL GRECO
PERSON|EMPEROR CLAUDIUS
PERSON|ERIC THE RED
PERSON|EURIPIDES
PERSON|EXPLORER
PERSON|FIRE INSPECTOR
PERSON|FRANKLIN DELANO ROOSEVELT
PERSON|GARRISON KEILLOR
PERSON|GENGHIS KHAN
PERSON|GEORGE HERMAN BABE RUTH
PERSON|GEORGE WASHINGTON
PERSON|GIAN CARLO MENOTTI
PERSON|GOSSIP COLUMNIST
PERSON|GREG LOUGANIS
PERSON|GROVER CLEVELAND ALEXANDER
PERSON|GUITAR PLAYER
PERSON|HANNIBAL
PERSON|HARRIET BEECHER STOWE
PERSON|HELEN OF TROY
PERSON|HENNY YOUNGMAN
PERSON|HENRY DAVID THOREAU
PERSON|HERSCHEL WALKER
PERSON|HIGH SCHOOL CHEERLEADER
PERSON|HISTORIAN
PERSON|HISTORY TEACHER
PERSON|HOME PLATE UMPIRE
PERSON|HOME RUN HITTER
PERSON|HONUS WAGNER
PERSON|HOTEL BUSBOY
PERSON|HUMORIST
PERSON|HYPNOTIST
PERSON|IVAN THE GREAT
PERSON|IVAN THE TERRIBLE
PERSON|JACQUES COUSTEAU
PERSON|JAMESA GARFIELD
PERSON|JAMES BUCHANAN
PERSON|JAMES WHISTLER
PERSON|JAZZ MUSICIAN
PERSON|JET SKIER
PERSON|JOAN OF ARC
PERSON|JOCKEY
PERSON|JOHN ADAMS
PERSON|JOHN PAUL JONES
PERSON|JOHN TYLER
PERSON|JON BON JOVI
PERSON|KONRAD ADENAUER
PERSON|KUBLAI KHAN
PERSON|LEONARDO DA VINCI
PERSON|LIGHTHOUSE KEEPER
PERSON|LUMBERJACK
PERSON|MAJOR LEAGUE BASEBALL PLAYER
PERSON|MANAGING EDITOR
PERSON|MANUEL NORIEGA
PERSON|MARATHON RUNNER
PERSON|MARIA VON TRAPP
PERSON|MARINE DRILL SERGEANT
PERSON|MARINE SERGEANT
PERSON|MARIO ANDRETTI
PERSON|MARTIN LUTHER
PERSON|MARY QUEEN OF SCOTS
PERSON|MARY TODD LINCOLN
PERSON|MATH TUTOR
PERSON|MATS WILANDER
PERSON|MAX VON SYDOW
PERSON|MAYNARD FERGUSON
PERSON|MEADOWLARK LEMON
PERSON|MERCHANT
PERSON|MERIWETHER LEWIS
PERSON|MISSISSIPPI RIVERBOAT GAMBLER
PERSON|MOISHE DAYAN
PERSON|MONDAY MORNING QUARTERBACK
PERSON|MOTORCYCLE COP
PERSON|MUSIC COMPOSER
PERSON|NATHANIEL HAWTHORNE
PERSON|NAVAL OFFICER
PERSON|NAVY ADMIRAL
PERSON|NEWS ANCHORMAN
PERSON|OFFENSIVE LINEMAN
PERSON|OLIVER CROMWELL
PERSON|ONCOLOGIST
PERSON|OPTICIAN
PERSON|OPTOMETRIST
PERSON|ORGAN DONOR
PERSON|PIANO PLAYER
PERSON|PIERRE SALINGER
PERSON|PIONEER
PERSON|PITCHING COACH
PERSON|PLAY BY PLAY ANNOUNCER
PERSON|PLUMBER'S APPRENTICE
PERSON|PRIVATE DETECTIVE
PERSON|PROFESSOR OF PHILOSOPHY
PERSON|PTOLEMY
PERSON|PULITZER PRIZE WINNER
PERSON|PYTHAGORAS
PERSON|QUEEN ISABELLA OF SPAIN
PERSON|QUEEN OF THE NILE
PERSON|RADIOLOGIST
PERSON|RALPH LAUREN
PERSON|ROBERTO CLEMENTE
PERSON|ROBIN GIVENS
PERSON|ROCK AND ROLL SINGER
PERSON|ROGER BACON
PERSON|ROGERS HORNSBY
PERSON|ROGER WILLIAMS
PERSON|ROYAL CANADIAN MOUNTIE
PERSON|ROY CAMPANELLA
PERSON|RUPERT MURDOCH
PERSON|RUTHERFORDB HAYES
PERSON|SACAJAWEA
PERSON|SALMAN RUSHDIE
PERSON|SAMUEL F B MORSE
PERSON|SANDY KOUFAX
PERSON|SANITATION WORKER
PERSON|SAXOPHONE PLAYER
PERSON|SCULPTOR
PERSON|SECRETARY OF STATE
PERSON|SENATE PAGE
PERSON|SHOE SALESMAN
PERSON|SPORTS COMMENTATOR
PERSON|STEPHEN DOUGLAS
PERSON|STEPHEN FOSTER
PERSON|STOOL PIGEON
PERSON|SUNDAY DRIVER
PERSON|TATTLETALE
PERSON|TED KOPPEL
PERSON|THE ARCHBISHOP OF CANTERBURY
PERSON|THIRD BASE COACH
PERSON|TREE SURGEON
PERSON|TUGBOAT CAPTAIN
PERSON|UNDERCOVER POLICEMAN
PERSON|VASCO DA GAMA
PERSON|WALT WHITMAN
PERSON|WASHINGTON IRVING
PERSON|WASHING MACHINE REPAIRMAN
PERSON|WEST POINT CADET
PERSON|WHISTLER'S MOTHER
PERSON|WILBUR WRIGHT
PERSON|WILLIAM CULLEN BRYANT
PERSON|WILLIAM MCKINLEY
PERSON|WILLIAM TECUMSEH SHERMAN
PERSON|WOLFMAN JACK
PERSON|WYNTON MARSALIS
PERSON|YASIR ARAFAT
THING|ADRENALIN
THING|ALCOHOLIC BEVERAGE
THING|ALKALINE BATTERY
THING|ANALOG QUARTZ WATCH
THING|APPLE CORE
THING|APPLE ORCHARD
THING|ARABIAN STALLION
THING|AREA RUG
THING|ASSEMBLY LINE
THING|ATTACHE CASE
THING|A SIX-MONTH C D
THING|A SWORN AFFIDAVIT
THING|BABY POWDER
THING|BATHROOM SINK
THING|BAYONET
THING|BIORHYTHM
THING|BIRTHDAY PRESENT
THING|BIRTH CERTIFICATE
THING|CARROT CAKE
THING|CHARLEY HORSE
THING|COLUMBIAN COFFEE
THING|COMPACT CAR
THING|CONDENSED MILK
THING|COPPERHEAD SNAKE
THING|CORDUROY JACKET
THING|CORMORANT
THING|CORNUCOPIA
THING|CORRECTED COPY
THING|COUNTERFEIT COIN
THING|CRABAPPLE TREE
THING|CRIMINAL LAW
THING|CRITICAL THINKING
THING|CROCKPOT
THING|CROQUET SET
THING|CROWBAR
THING|CUBAN CIGAR
THING|CUBIC ZIRCONIA EARRINGS
THING|CY YOUNG AWARD
THING|DESKTOP COPIER
THING|DIAPER SERVICE
THING|DOCTOR'S SCALE
THING|DRAWER ORGANIZER
THING|ELECTRONIC KEYBOARD
THING|ELECTRONIC SCOREBOARD
THING|EMPEROR MOTH
THING|FACSIMILE MACHINE
THING|FACTORY WARRANTY
THING|FEATURE LENGTH FILM
THING|FISH CROQUETTE
THING|FOLDING STEP STOOL
THING|FOLDING UMBRELLA
THING|FOOL'S GOLD
THING|FROZEN YOGURT
THING|FUNGO BAT
THING|GARBAGE DUMPSTER
THING|GAZEBO
THING|GLAZED DONUT
THING|GOLF CART
THING|GOOSE FEATHER PILLOW
THING|GRANNY SMITH APPLE
THING|HAND GRENADE
THING|HEARING DISORDER
THING|HOME ADDRESS
THING|HOME MORTGAGE
THING|HUMIDIFIER
THING|HURRICANE
THING|HYDROGEN PEROXIDE
THING|HYGROMETER
THING|ICEBERG
THING|ICEBOX
THING|ICHTHYOLOGY
THING|JEWELRY BOX
THING|KEY LIME PIE
THING|LASER BEAM SURGERY
THING|LAWN SPRINKLER
THING|LIBERTY BELL
THING|LIFE INSURANCE POLICY
THING|MATERNITY DRESS
THING|MEDIUM- RANGE MISSILE
THING|MILK CONTAINER
THING|MURIATIC ACID
THING|NOBEL PEACE PRIZE
THING|NUCLEAR REACTOR
THING|OPOSSUM
THING|OPTICAL ILLUSION
THING|ORANGE JUICE
THING|ORDINAL NUMBER
THING|ORGAN BANK
THING|PERSIAN RUG
THING|PHOTO ALBUM
THING|WATER PITCHER
THING|POCKET KNIFE
THING|POISONOUS SNAKE
THING|POLKA- DOT BIKINI
THING|POPCORN POPPER
THING|PRAIRIE DOG
THING|PSEUDONYM
THING|PULSE RATE
THING|QUARTZ ALARM CLOCK
THING|QUICKSAND
THING|RADAR DETECTOR
THING|REFERENCE BOOK
THING|ROAST PORK FRIED RICE
THING|ROSETTA STONE
THING|RUBBING ALCOHOL
THING|RUM FACTORY
THING|SAMOVAR
THING|SANDY BEACH
THING|SAPPHIRE BRACELET
THING|SATELLITE DISH
THING|SATYR
THING|SAUNA BATH
THING|SAVINGS ACCOUNT
THING|SAWDUST
THING|SAWHORSE
THING|SAXOPHONE
THING|SHOESTRING CATCH
THING|SLEEPING BAG
THING|SOLAR- POWERED CALCULATOR
THING|SOMERSAULT
THING|STEAK SAUCE
THING|STEALTH BOMBER
THING|STEAM- SPRAY- DRY IRON
THING|SWIVEL CHAIR
THING|SWORD SCABBARD
THING|TACKLE BOX
THING|THE OTTOMAN EMPIRE
THING|THE SPHINX
THING|TOUCHDOWN RUN
THING|TOW TRUCK
THING|TRACK HURDLE
THING|TWIST-OFF CAP
THING|UNDERWATER CAMERA
THING|UPRIGHT FREEZER
THING|VACUUM BOTTLE
THING|VAMPIRE BAT
THING|VAULTING HORSE
THING|VISITING TEAM DUGOUT
THING|VOGUE MAGAZINE
THING|WESTERN OMELET
THING|WIDE-ANGLE BINOCULARS
FICTIONAL CHARACTER|ARCHIE BUNKER
FICTIONAL CHARACTER|B L STRYKER
FICTIONAL CHARACTER|BABAR THE ELEPHANT
FICTIONAL CHARACTER|BARNABY JONES
FICTIONAL CHARACTER|BARNEY MILLER
FICTIONAL CHARACTER|BECKY THATCHER
FICTIONAL CHARACTER|BOSTON BLACKIE
FICTIONAL CHARACTER|BUCK ROGERS
FICTIONAL CHARACTER|CALAMITY JANE
FICTIONAL CHARACTER|CAPTAIN KANGAROO
FICTIONAL CHARACTER|CLUBBER LANG
FICTIONAL CHARACTER|DADDY WARBUCKS
FICTIONAL CHARACTER|DAISY MILLER
FICTIONAL CHARACTER|DOCTOR KILDARE
FICTIONAL CHARACTER|DAGWOOD BUMSTEAD
FICTIONAL CHARACTER|DON QUIXOTE
FICTIONAL CHARACTER|ELIZA DOOLITTLE
FICTIONAL CHARACTER|FLASH GORDON
FICTIONAL CHARACTER|FLETCHER CHRISTIAN
FICTIONAL CHARACTER|FOGHORN LEGHORN
FICTIONAL CHARACTER|HAGAR THE HORRIBLE
FICTIONAL CHARACTER|HOPALONG CASSIDY
FICTIONAL CHARACTER|INSPECTOR GADGET
FICTIONAL CHARACTER|INSPECTOR JACQUES CLOUSEAU
FICTIONAL CHARACTER|JACOB MARLEY
FICTIONAL CHARACTER|JEAN VALJEAN
FICTIONAL CHARACTER|JOE PALOOKA
FICTIONAL CHARACTER|JOE THE BARTENDER
FICTIONAL CHARACTER|LEX LUTHOR
FICTIONAL CHARACTER|LITTLE ORPHAN ANNIE
FICTIONAL CHARACTER|LUCY RICARDO
FICTIONAL CHARACTER|MANDRAKE THE MAGICIAN
FICTIONAL CHARACTER|MARCUS WELBY
FICTIONAL CHARACTER|MARMADUKE
FICTIONAL CHARACTER|MISS JANE MARPLE
FICTIONAL CHARACTER|MISS MONEYPENNY
FICTIONAL CHARACTER|MR BELVEDERE
FICTIONAL CHARACTER|OLD KING COLE
FICTIONAL CHARACTER|PERCY DOVETONSILS
FICTIONAL CHARACTER|POSEIDON
FICTIONAL CHARACTER|PRINCE VALIANT
FICTIONAL CHARACTER|PROFESSOR HENRY HIGGINS
FICTIONAL CHARACTER|PROFESSOR MORIARTY
FICTIONAL CHARACTER|PUNKY BREWSTER
FICTIONAL CHARACTER|QUASIMODO
FICTIONAL CHARACTER|RALPH KRAMDEN
FICTIONAL CHARACTER|REMINGTON STEELE
FICTIONAL CHARACTER|ROCKY BALBOA
FICTIONAL CHARACTER|ROGER RABBIT
FICTIONAL CHARACTER|SERGEANT JOE FRIDAY
FICTIONAL CHARACTER|SLAP MAXWELL
FICTIONAL CHARACTER|SUZIE WONG
FICTIONAL CHARACTER|THE GRINCH
FICTIONAL CHARACTER|THE JOLLY GREEN GIANT
FICTIONAL CHARACTER|THE LONE RANGER
FICTIONAL CHARACTER|TRAPPER JOHN
FICTIONAL CHARACTER|TUGBOAT ANNIE
PHRASE|A BLAST FROM THE PAST
PHRASE|A BREATH OF FRESH AIR
PHRASE|A CHEATER NEVER WINS
PHRASE|A CHIP OFF THE OLD BLOCK
PHRASE|A CLEAN BILL OF HEALTH
PHRASE|A COWARD DIES A THOUSAND TIMES
PHRASE|A DIRTY LOW-DOWN TRICK
PHRASE|A LARGER THAN LIFE ROLE
PHRASE|A LONG BOMB FOR A TOUCHDOWN
PHRASE|A LUCKY DAY
PHRASE|A LUST FOR LIFE
PHRASE|A PENNY SAVED IS A PENNY EARNED
PHRASE|A SNAKE IN THE GRASS
PHRASE|A STANDING ROOM ONLY AUDIENCE
PHRASE|A TRIED AND TRUE METHOD
PHRASE|A WASTE OF TIME AND ENERGY
PHRASE|A WATERED- DOWN VERSION
PHRASE|ADVANCE AND BE RECOGNIZED
PHRASE|ADVICE TO THE LOVELORN
PHRASE|ALL WORK GUARANTEED
PHRASE|AN ACCIDENT WAITING TO HAPPEN
PHRASE|SITTING ON TOP OF THE WORLD
PHRASE|A DEATH- DEFYING STUNT
PHRASE|A GENTLEMAN'S AGREEMENT
PHRASE|A HOMETOWN CROWD
PHRASE|A SNEAKING SUSPICION
PHRASE|A SYMPATHETIC EAR
PHRASE|A TOURNAMENT OF CHAMPIONS
PHRASE|BACKFIELD IN MOTION
PHRASE|BAPTISM UNDER FIRE
PHRASE|BASEBALL RHUBARB
PHRASE|BEAUTY IS IN THE EYE OF THE BEHOLDER
PHRASE|BEAUTY IS SKIN DEEP
PHRASE|BEING LED DOWN THE GARDEN PATH
PHRASE|BLIND AS A BAT
PHRASE|BLONDES HAVE MORE FUN
PHRASE|BROTHER CAN YOU SPARE A DIME
PHRASE|BUY THREE AND GET ONE FREE
PHRASE|CAT GOT YOUR TONGUE
PHRASE|CLEAN UP AFTER YOURSELF
PHRASE|CLEAN AS A WHISTLE
PHRASE|COLD HARD CASH
PHRASE|COME BACK TO REALITY
PHRASE|COURT IS ADJOURNED
PHRASE|CRYING CROCODILE TEARS
PHRASE|DON'T BET YOUR LIFE ON IT
PHRASE|DON'T CRY OVER SPILT MILK
PHRASE|DON'T MAKE A MONKEY OUT OF ME
PHRASE|DOUBLE YOUR PLEASURE
PHRASE|DOWN AND OUT
PHRASE|DOWN FOR THE COUNT
PHRASE|DOWN IN THE MOUTH
PHRASE|DOWN IN THE DUMPS
PHRASE|DRESS FOR SUCCESS
PHRASE|EATING ON THE RUN
PHRASE|FAMOUS LAST WORDS
PHRASE|FIGHT FIRE WITH FIRE
PHRASE|FIRST AND GOAL TO GO
PHRASE|FLOATING A LOAN
PHRASE|FOOTLOOSE AND FANCY FREE
PHRASE|FOREVER YOUNG IN HEART
PHRASE|FOR BETTER OR FOR WORSE
PHRASE|FOURTH DOWN AND INCHES
PHRASE|GETTING AHEAD IN THE WORLD
PHRASE|GETTING BOGGED DOWN
PHRASE|GETTING PAID BACK IN SPADES
PHRASE|GIVE ME YOUR ATTENTION PLEASE
PHRASE|GO HOME AND SLEEP ON IT
PHRASE|GO OUT IN A BLAZE OF GLORY
PHRASE|GO WITH THE FLOW
PHRASE|GOING BUST
PHRASE|GOING OUT OF BUSINESS SALE
PHRASE|GRABBING A BITE TO EAT
PHRASE|GROUNDS FOR DIVORCE
PHRASE|HANG IN THERE
PHRASE|HE WHO LAUGHS LAST LAUGHS BEST
PHRASE|HEAVEN HELP US
PHRASE|HOME IS WHERE THE HEART IS
PHRASE|I CANNOT TELL A LIE
PHRASE|I TOLD YOU SO
PHRASE|INTO EVERY LIFE SOME RAIN MUST FALL
PHRASE|IN A STATE OF PANIC
PHRASE|IN OVER MY HEAD
PHRASE|IT SENT CHILLS DOWN MY SPINE
PHRASE|IT'S A PLEASURE TO KNOW YOU
PHRASE|IT'S A LIVING
PHRASE|I'M READY FOR ANYTHING
PHRASE|I'VE GOT GOOD NEWS AND BAD NEWS
PHRASE|JUST TAKE IT NICE AND EASY
PHRASE|KEEP YOUR EYES PEELED
PHRASE|KNOCK ON WOOD
PHRASE|LAST BUT NOT LEAST
PHRASE|LEARN FROM YOUR MISTAKES
PHRASE|LEARN TO PLAY THE GAME
PHRASE|LET'S GO METS
PHRASE|LIVE AND LET LIVE
PHRASE|LIVING BEYOND YOUR MEANS
PHRASE|MARRYING ON THE REBOUND
PHRASE|MEALS ON WHEELS
PHRASE|MONEY IS THE ROOT OF ALL EVIL
PHRASE|MONEY CAN'T BUY HAPPINESS
PHRASE|NECESSITY IS THE MOTHER OF INVENTION
PHRASE|NEVER A DULL MOMENT
PHRASE|NEVER LOOK BACK
PHRASE|NICE GUYS FINISH LAST
PHRASE|NO PLACE TO GO BUT UP
PHRASE|NOT WORTH A PLUG NICKEL
PHRASE|NOTHING VENTURED NOTHING GAINED
PHRASE|OLD ENOUGH TO KNOW BETTER
PHRASE|ONE OF LIFE'S LITTLE BLESSINGS
PHRASE|ONE PICTURE IS WORTH A THOUSAND WORDS
PHRASE|ONLY TIME WILL TELL
PHRASE|OPEN DOOR TRADE POLICY
PHRASE|OPPORTUNITY KNOCKS
PHRASE|ORDEAL BY FIRE
PHRASE|ORDER IN THE COURT
PHRASE|OVERCOMING ADVERSITY
PHRASE|PASS BY THE SKIN OF YOUR TEETH
PHRASE|PASS WITH FLYING COLORS
PHRASE|PAY IN ADVANCE
PHRASE|PHONY AS A TWO-DOLLAR BILL
PHRASE|PLAYING IT BY EAR
PHRASE|PLAYING POSSUM
PHRASE|PLAYING THE DEVIL'S ADVOCATE
PHRASE|POSITIVE FEEDBACK
PHRASE|PUT UP OR SHUT UP
PHRASE|PUTTING YOUR CARDS ON THE TABLE
PHRASE|READY WILLING AND ABLE
PHRASE|ROTTEN TO THE CORE
PHRASE|RUNNING FOR COVER
PHRASE|RUNNING ON EMPTY
PHRASE|SEALED WITH A KISS
PHRASE|SEVENTH- INNING STRETCH
PHRASE|SICK AS A DOG
PHRASE|SOME FOOD FOR THOUGHT
PHRASE|SOMETHING SMELLS FISHY HERE
PHRASE|STAND UP AND BE COUNTED
PHRASE|STAND UP FOR YOUR RIGHTS
PHRASE|STAND AT ATTENTION
PHRASE|STAND BY YOUR MAN
PHRASE|STARTING FROM SCRATCH
PHRASE|START WITH A CLEAN SLATE
PHRASE|STILL WATERS RUN DEEP
PHRASE|STUCK IN A RUT
PHRASE|SURVIVAL OF THE FITTEST
PHRASE|TAKE IT ONE DAY AT A TIME
PHRASE|TAKE A DEEP BREATH
PHRASE|TALKING THROUGH YOUR HAT
PHRASE|TELL IT TO THE MARINES
PHRASE|THAT WASA CLOSE CALL
PHRASE|THAT'S SO FUNNY I FORGOT TO LAUGH
PHRASE|THAT'S A TALL ORDER
PHRASE|THAT'S MUSIC TO MY EARS
PHRASE|THE AGONY OF DEFEAT
PHRASE|THE APPLE OF HIS EYE
PHRASE|THE BRAVE ONLY DIE ONCE
PHRASE|THE CHECK IS IN THE MAIL
PHRASE|THE END JUSTIFIES THE MEANS
PHRASE|THE FLESH IS WEAK
PHRASE|THE STAR OF THE SHOW
PHRASE|THE VOICE OF DOOM
PHRASE|THE GREEN GRASS OF HOME
PHRASE|THE LOVE OF MY LIFE
PHRASE|THE ORDER OF THE DAY
PHRASE|THE PERFECT COUPLE
PHRASE|THE VOICE OF AN ANGEL
PHRASE|THE WHOLE WORLD IS A STAGE
PHRASE|THIS WON'T HURT A BIT
PHRASE|THREE STRIKES AND YOU'RE OUT
PHRASE|TIME HEALS ALL WOUNDS
PHRASE|TOO CLOSE TO CALL
PHRASE|TRUTH IS STRANGER THAN FICTION
PHRASE|WAKE UP AND SMELL THE COFFEE
PHRASE|WHEN I TALK YOU JUMP
PHRASE|YOU ARE WHAT YOU EAT
PHRASE|YOU CAN'T CHEAT AN HONEST MAN
PHRASE|YOU DESERVE A BREAK TODAY
PHRASE|YOU GOTTA BELIEVE
TITLE|A BELL FOR ADANO
TITLE|A MAN FOR ALL SEASONS
TITLE|A TALE OF TWO CITIES
TITLE|ALL MY CHILDREN
TITLE|ALL QUIET ON THE WESTERN FRONT
TITLE|ALL IN THE FAMILY
TITLE|ALL'S WELL THAT ENDS WELL
TITLE|AMERICAN GRAFFITI
TITLE|ANNIE GET YOUR GUN
TITLE|ANTONY AND CLEOPATRA
TITLE|AROUND THE WORLD IN EIGHTY DAYS
TITLE|ARROWSMITH
TITLE|ARSENIC AND OLD LACE
TITLE|AS YOU LIKE IT
TITLE|A CURRENT AFFAIR
TITLE|A STREETCAR NAMED DESIRE
TITLE|BANG THE DRUM SLOWLY
TITLE|BAREFOOT IN THE PARK
TITLE|BORN YESTERDAY
TITLE|CACTUS FLOWER
TITLE|CAPTAINS COURAGEOUS
TITLE|CAROUSEL
TITLE|CASABLANCA
TITLE|CASINO ROYALE
TITLE|CAT BALLOU
TITLE|CAT ON A HOT TIN ROOF
TITLE|CHARLOTTE'S WEB
TITLE|CRIME AND PUNISHMENT
TITLE|DAMN YANKEES
TITLE|DAVID COPPERFIELD
TITLE|DEAD POETS SOCIETY
TITLE|DON'T GO NEAR THE WATER
TITLE|DOONESBURY
TITLE|DR JEKYLL AND MR HYDE
TITLE|FAR FROM THE MADDING CROWD
TITLE|FROM HERE TO ETERNITY
TITLE|FROM RUSSIA WITH LOVE
TITLE|FULL METAL JACKET
TITLE|GUESS WHO'S COMING TO DINNER
TITLE|GULLIVER'S TRAVELS
TITLE|GUYS AND DOLLS
TITLE|HARVEY
TITLE|HELLO DOLLY
TITLE|HIGH PLAINS DRIFTER
TITLE|HOW THE CAMEL GOT ITS HUMP
TITLE|HOW THE RHINOCEROS GOT ITS SKIN
TITLE|HOW GREEN WAS MY VALLEY
TITLE|HOW THE WEST WAS WON
TITLE|HUCKLEBERRY FINN
TITLE|IN THE HEAT OF THE NIGHT
TITLE|INDIANA JONES AND THE LAST CRUSADE
TITLE|INHERIT THE WIND
TITLE|IRMA LA DOUCE
TITLE|ISLAND OF THE BLUE DOLPHINS
TITLE|IT'S A MAD MAD MAD MAD WORLD
TITLE|JONATHAN LIVINGSTON SEAGULL
TITLE|LADY AND THE TRAMP
TITLE|LAST TANGO IN PARIS
TITLE|LES MISERABLES
TITLE|LIFE WITH FATHER
TITLE|LONG DAY'S JOURNEY INTO NIGHT
TITLE|LOOK HOMEWARD ANGEL
TITLE|LOST HORIZON
TITLE|MARJORIE MORNINGSTAR
TITLE|MARRIED TO THE MOB
TITLE|MIDNIGHT COWBOY
TITLE|MURDERS IN THE RUE MORGUE
TITLE|MY FAIR LADY
TITLE|MY SISTER EILEEN
TITLE|NO TIME FOR SERGEANTS
TITLE|NOT NECESSARILY THE NEWS
TITLE|ON THE WATERFRONT
TITLE|PAJAMA GAME
TITLE|PAPER MOON
TITLE|PEYTON PLACE
TITLE|PHANTOM OF THE OPERA
TITLE|PLANET OF THE APES
TITLE|PORTNOY'S COMPLAINT
TITLE|ROMEO AND JULIET
TITLE|ROSEMARY'S BABY
TITLE|SANFORD AND SON
TITLE|SERGEANT YORK
TITLE|SHANE
TITLE|SHENANDOAH
TITLE|SHIP OF FOOLS
TITLE|SOYLENT GREEN
TITLE|STAGECOACH
TITLE|SWAN LAKE
TITLE|TAKE ME OUT TO THE BALL GAME
TITLE|TALES OF THE SOUTH PACIFIC
TITLE|TEAHOUSE OF THE AUGUST MOON
TITLE|THAT TOUCH OF MINK
TITLE|THE BELLS ARE RINGING
TITLE|THE BRIDGE ON THE RIVER KWAI
TITLE|THE CASK OF AMONTILLADO
TITLE|THE DIARY OF ANNE FRANK
TITLE|THE DAY OF THE JACKAL
TITLE|THE FALL OF THE HOUSE OF USHER
TITLE|THE FOUR HORSEMEN OF THE APOCALYPSE
TITLE|THE LIFE AND DEATH OF KING JOHN
TITLE|THE LION IN WINTER
TITLE|THE MARY TYLER MOORE SHOW
TITLE|THE MASQUE OF THE RED DEATH
TITLE|THE PIT AND THE PENDULUM
TITLE|THE PRINCE AND THE PAUPER
TITLE|THE RED BADGE OF COURAGE
TITLE|THE SOUND OF MUSIC
TITLE|THE SPY WHO CAME IN FROM THE COLD
TITLE|THE VICAR OF WAKEFIELD
TITLE|THE YOUNG AND THE RESTLESS
TITLE|THE SUBJECT WAS ROSES
TITLE|THE AGONY AND THE ECSTASY
TITLE|THE ARRANGEMENT
TITLE|THE BEST YEARS OF OUR LIVES
TITLE|THE BLACK CAT
TITLE|THE BRIDGE OF SAN LUIS REY
TITLE|THE BROTHERS KARAMAZOV
TITLE|THE CAINE MUTINY
TITLE|THE CAROL BURNETT SHOW
TITLE|THE COMEDY OF ERRORS
TITLE|THE CRUCIBLE
TITLE|THE DICK VAN DYKE SHOW
TITLE|THE GRADUATE
TITLE|THE GREATEST SHOW ON EARTH
TITLE|THE GREAT WHITE HOPE
TITLE|THE GREEN BERETS
TITLE|THE HOUSE OF THE SEVEN GABLES
TITLE|THE HUNCHBACK OF NOTRE DAME
TITLE|THE KEYS OF THE KINGDOM
TITLE|THE LIGHT THAT FAILED
TITLE|THE LONGEST DAY
TITLE|THE MERCHANT OF VENICE
TITLE|THE MIKADO
TITLE|THE MIRACLE OF THE BELLS
TITLE|THE MONKEY'S PAW
TITLE|THE ODESSA FILE
TITLE|THE OUTSIDERS
TITLE|THE PARENT TRAP
TITLE|THE PARTRIDGE FAMILY
TITLE|THE PATHFINDER
TITLE|THE PICTURE OF DORIAN GRAY
TITLE|THE POSEIDON ADVENTURE
TITLE|THE PRISONER OF ZENDA
TITLE|THE SAND PEBBLES
TITLE|THE SATANIC VERSES
TITLE|THE SECRET GARDEN
TITLE|THE SEVEN YEAR ITCH
TITLE|THE SHAGGY DOG
TITLE|THE SHOES OF THE FISHERMAN
TITLE|THE SONG OF BERNADETTE
TITLE|THE SWISS FAMILY ROBINSON
TITLE|THE TAMING OF THE SHREW
TITLE|THE THREE MUSKETEERS
TITLE|THE UNSINKABLE MOLLY BROWN
TITLE|THIRTY SOMETHING
TITLE|THOROUGHLY MODERN MILLIE
TITLE|THUNDERBALL
TITLE|TO KILLA MOCKINGBIRD
TITLE|TO SIR WITH LOVE
TITLE|TREASURE ISLAND
TITLE|TREASURE OF SIERRA MADRE
TITLE|TROILUS AND CRESSIDA
TITLE|TWO GENTLEMEN OF VERONA
TITLE|UPSTAIRS DOWNSTAIRS
TITLE|VALLEY OF THE DOLLS
TITLE|WEBSTER'S NEW WORLD LARGE PRINT DICTIONARY
TITLE|WHAT'S NEW PUSSYCAT
TITLE|WHO'S AFRAID OF VIRGINIA WOOLF
TITLE|WUTHERING HEIGHTS
TITLE|YANKEE DOODLE DANDY
TITLE|YOU CAN'T DO THAT ON TELEVISION
TITLE|YOU CAN'T TAKE IT WITH YOU
TITLE|YOU ONLY LIVE TWICE
TITLE|YOU'RE A GOOD MAN CHARLIE BROWN
PEOPLE|ACCOUNTING FIRM
PEOPLE|AIR RAID WARDENS
PEOPLE|AMERICAN LEAGUE ALL-STAR TEAM
PEOPLE|BOLSHOI BALLET
PEOPLE|BOSOM BUDDIES
PEOPLE|BOSTON POPS ORCHESTRA
PEOPLE|CANDY- STRIPER VOLUNTEERS
PEOPLE|CHAMBER OF COMMERCE
PEOPLE|CHILD STUDY TEAM
PEOPLE|CITY COUNCIL
PEOPLE|CUBAN EXILES
PEOPLE|FOREIGN INVESTORS
PEOPLE|GAME SHOW CONTESTANTS
PEOPLE|GRADUATING CLASS
PEOPLE|GREGG ALLMAN BAND
PEOPLE|HOUSE OF COMMONS
PEOPLE|INNOCENT BYSTANDERS
PEOPLE|KNIGHTS OF THE ROUND TABLE
PEOPLE|LITTLE LEAGUE CHAMPIONS
PEOPLE|LONDON BOBBIES
PEOPLE|LOTTERY WINNERS
PEOPLE|MARINE PATROL
PEOPLE|PHILISTINES
PEOPLE|POWER SQUADRON
PEOPLE|PYGMIES
PEOPLE|RADIO CITY MUSIC HALL ROCKETTES
PEOPLE|ROMULUS AND REMUS
PEOPLE|ROOKIE COPS
PEOPLE|SALVATION ARMY SANTAS
PEOPLE|SAMSON AND DELILAH
PEOPLE|SPYRO GYRA
PEOPLE|SUPREME COURT JUSTICES
PEOPLE|SWAT TEAM
PEOPLE|SYMPHONY ORCHESTRA
PEOPLE|TAXICAB DRIVERS
PEOPLE|TEAMSTERS UNION MEMBERS
PEOPLE|THE BLUE ANGELS
PEOPLE|THE DALLAS COWBOYS
PEOPLE|THE DIRTY DOZEN BRASS BAND
PEOPLE|THE FLORIDA STATE SEMINOLES
PEOPLE|THE LITTLE RASCALS
PEOPLE|THE MIAMI HEAT
PEOPLE|THE MONKEES
PEOPLE|THE OKLAHOMA SOONERS
PEOPLE|THE PRESIDENT'S CABINET
PEOPLE|VISIGOTHS
PEOPLE|WORLD CLASS WRESTLERS
EVENT|A ROYAL CORONATION
EVENT|AFTERNOON NAP
EVENT|AMERICAN KENNEL CLUB DOG SHOW
EVENT|BATTLE OF THE BULGE
EVENT|BAY OF PIGS INVASION
EVENT|BRIDAL SHOWER
EVENT|CANNES FILM FESTIVAL
EVENT|EXXON VALDEZ OIL SPILL
EVENT|FOOTBALL HALFTIME SHOW
EVENT|JANUARY WHITE SALE
EVENT|LOTTERY DRAWING
EVENT|MILITARY COURT MARTIAL
EVENT|MUSCULAR DYSTROPHY TELETHON
EVENT|NATIONAL SPELLING BEE CONTEST
EVENT|ORGAN TRANSPLANT SURGERY
EVENT|PIE-EATING CONTEST
EVENT|RIBBON- CUTTING CEREMONY
EVENT|SALZBURG MUSIC FESTIVAL
EVENT|SECRETARIES DAY
EVENT|SPRING BREAK
EVENT|SWEET SIXTEEN PARTY
EVENT|TAKING THE BAR EXAM
EVENT|THE ALLIED INVASION OF ANZIO
EVENT|THE DARK AGES
EVENT|THE AMERICAN REVOLUTION
EVENT|THE COLLEGE WORLD SERIES
EVENT|THE JUNIOR OLYMPICS
EVENT|THE ORANGE BOWL FESTIVAL
EVENT|THE SIEGE OF LENINGRAD
EVENT|THE SPANISH CIVIL WAR
EVENT|THE TROJAN WAR
EVENT|TOURNAMENT OF ROSES PARADE
EVENT|TUPPERWARE PARTY
EVENT|UNASSISTED DOUBLE-PLAY
EVENT|WEDDING ANNIVERSARY
SAME NAME|ADAM MAE AND JERRY WEST
SAME NAME|ADLAI AND ROBERT LOUIS STEVENSON
SAME NAME|AGNES AND CECIL B DE MILLE
SAME NAME|AMY AND WASHINGTON IRVING
SAME NAME|ANDREW AND GIG YOUNG
SAME NAME|ANDREW JACK AND LYNDON JOHNSON
SAME NAME|ANDY HANK AND JO BETH WILLIAMS
SAME NAME|ANTHONY AND DAN QUAYLE
SAME NAME|ANTHONY MIRIAM AND HARRY HOPKINS
SAME NAME|ARETHA AND BENJAMIN FRANKLIN
SAME NAME|ARNOLD AND LILY PALMER
SAME NAME|ARTHUR GLENN AND BARNEY MILLER
SAME NAME|ARTIE AND GEORGE BERNARD SHAW
SAME NAME|BARBARA AND JOHANN SEBASTIAN BACH
SAME NAME|BARRY ANNIE AND JOHN L SULLIVAN
SAME NAME|ARTHUR BENNY AND BUNKER HILL
SAME NAME|BETSY AND DIANA ROSS
SAME NAME|BILLY AND DEAN MARTIN
SAME NAME|BOB AND JOANNE WOODWARD
SAME NAME|BOOG AND DICK POWELL
SAME NAME|BROOKLYN LONDON AND LLOYD BRIDGES
SAME NAME|BUDDY AND RICHIE RICH
SAME NAME|BUTCH AND SHAWN CASSIDY
SAME NAME|BUTTERFLY AND STEVE MCQUEEN
SAME NAME|CAPE AND LITTLE BIG HORN
SAME NAME|CAROLE ALAN AND STEPHEN KING
SAME NAME|CHARLIE AND HELEN KELLER
SAME NAME|CHIC ALAN AND ROLAND YOUNG
SAME NAME|CHRISTINE AND RUBY KEELER
SAME NAME|CHRISTOPHER AND PHILIP MARLOWE
SAME NAME|CLIFTON AND JACK WEBB
SAME NAME|DANIEL PAT AND RICHARD BOONE
SAME NAME|DEBBIE AND R J REYNOLDS
SAME NAME|DICK AND RAMSEY CLARK
SAME NAME|DR BENJAMIN AND MR SPOCK
SAME NAME|DUCHESS OF AND CLARK KENT
SAME NAME|DUSTIN AND ABBIE HOFFMAN
SAME NAME|EDWARD G JACKIE AND MRS ROBINSON
SAME NAME|ELIZABETH AND EVE ARDEN
SAME NAME|ELMO AND ABRAHAM LINCOLN
SAME NAME|ERSKINE AND TAYLOR CALDWELL
SAME NAME|ESTHER TED AND BILLY DEE WILLIAMS
SAME NAME|EVANGELINE AND EDWIN BOOTH
SAME NAME|F LEE AND BEETLE BAILEY
SAME NAME|FAYE AND RALPH WALDO EMERSON
SAME NAME|FORREST AND SOPHIE TUCKER
SAME NAME|GARRY AND PIERRE TRUDEAU
SAME NAME|GENE AND THORTON WILDER
SAME NAME|GEORGE ARTHUR AND ROSE KENNEDY
SAME NAME|GEORGE AND T S ELIOT
SAME NAME|GEORGE BERNARD AND ROBERT SHAW
SAME NAME|GEORGE HENRY AND IRVING WALLACE
SAME NAME|GINGER BUCK AND BUDDY ROGERS
SAME NAME|GORGEOUS AND BOY GEORGE
SAME NAME|GROVER CLEVELAND AND BRANDY ALEXANDER
SAME NAME|GYPSY ROSE BRUCE AND ROBERT E LEE
SAME NAME|HARRISON GERALD AND MODEL T FORD
SAME NAME|HAROLD NANCY AND WOODROW WILSON
SAME NAME|HARRY AND JESSIE JAMES
SAME NAME|HAYLEY AND GENERAL MILLS
SAME NAME|HELEN GURLEY AND CHARLIE BROWN
SAME NAME|HUGH AND CHURCHILL DOWNS
SAME NAME|IAN AND RHONDA FLEMING
SAME NAME|INDIANA TOM AND GRACE JONES
SAME NAME|ISAAC AND BILL STERN
SAME NAME|JACKIE WALKER AND GORDON COOPER
SAME NAME|JACK JOHNNY AND KIT CARSON
SAME NAME|JACLYN KATE AND JOHN SMITH
SAME NAME|JAMES LES AND JIMMY BROWN
SAME NAME|JAMES AND CARROLL BAKER
SAME NAME|JAMES AND VAUGHAN MONROE
SAME NAME|JAY AND ELLIOTT GOULD
SAME NAME|JEANETTE ROSS AND OLD MACDONALD
SAME NAME|JERRY SHARI AND JOHN L LEWIS
SAME NAME|JIMMY JACK AND LINDA CARTER
SAME NAME|JODIE AND STEPHEN FOSTER
SAME NAME|JOHN CAMERON AND PATRICK SWAYZE
SAME NAME|JOSEPH AND CHARLIE MCCARTHY
SAME NAME|JOSEPH AND WILLIAM CONRAD
SAME NAME|JOE AND ROY CAMPANELLA
SAME NAME|JULIE AND MAXINE ANDREWS
SAME NAME|KAREN AND SCOTT CARPENTER
SAME NAME|KATE GLENDA AND STONEWALL JACKSON
SAME NAME|KIRK MIKE AND WILLIAM O DOUGLAS
SAME NAME|LARRY AND BIG BIRD
SAME NAME|LEONARD AND CARL BERNSTEIN
SAME NAME|LE VAR AND RICHARD BURTON
SAME NAME|LEVI AND PETER STRAUSS
SAME NAME|LILLIAN AND PHILIP ROTH
SAME NAME|LONI JACK AND MAXWELL ANDERSON
SAME NAME|LORETTA GIG AND CY YOUNG
SAME NAME|MARIA AND CHARLIE CALLAS
SAME NAME|MARLO TERRY AND ISIAH THOMAS
SAME NAME|MARNI AND RICHARD NIXON
SAME NAME|MARY AND RICHARD TODD
SAME NAME|MEL AND MONT BLANC
SAME NAME|MEL AND OUR MISS BROOKS
SAME NAME|MICHAEL J AND TWENTIETH CENTURY FOX
SAME NAME|MICHAEL SERGEANT AND DUKE OF YORK
SAME NAME|NEIL AND BASEBALL DIAMOND
SAME NAME|NEIL AND JACK ARMSTRONG
SAME NAME|NEVILLE AND WILT CHAMBERLAIN
SAME NAME|NIPSEY AND KURT RUSSELL
SAME NAME|NOLAN AND ROBERT RYAN
SAME NAME|NORMAN AND GEORGE LINCOLN ROCKWELL
SAME NAME|O J AND WALLIS WARFIELD SIMPSON
SAME NAME|OMAR AND BILL BRADLEY
SAME NAME|ORAL AND MR ROBERTS
SAME NAME|ORSON AND H G WELLES
SAME NAME|ROBERT PETER AND NATHANIEL BENCHLEY
SAME NAME|PETER AND EMIL JENNINGS
SAME NAME|QUICK DRAW TUG AND ALI MC GRAW
SAME NAME|RAYMOND AND AARON BURR
SAME NAME|REX AND GEORGE HARRISON
SAME NAME|RICHARD AND FORT DIX
SAME NAME|RICKY AND BABY FACE NELSON
SAME NAME|RINGO BRENDA AND KAY STARR
SAME NAME|ROBERT AND GEORGE BURNS
SAME NAME|ROCK AND HENRY HUDSON
SAME NAME|RUTHERFORD AND GABBY HAYES
SAME NAME|SALLY MARSHALL AND SOLDIER FIELD
SAME NAME|SARAH AND ROBERT VAUGHN
SAME NAME|SHELLEY AND JONATHAN WINTERS
SAME NAME|SIGOURNEY DENNIS AND PAT WEAVER
SAME NAME|SINCLAIR AND JERRY LEE LEWIS
SAME NAME|SIR WALTER AND GEORGE C SCOTT
SAME NAME|SANDRA DAY DONALD AND CARROLL O'CONNOR
SAME NAME|SPENCER AND DICK TRACY
SAME NAME|THELMA AND TEX RITTER
SAME NAME|THEODORE SANFORD AND BETTY WHITE
SAME NAME|THURGOOD AND E G MARSHALL
SAME NAME|TONY AND JOAN BENNETT
SAME NAME|VERONICA ARTHUR AND GREAT SALT LAKE
SAME NAME|VINCENT AND LEONTYNE PRICE
SAME NAME|WALDO AND CLAUDE PEPPER
SAME NAME|WALT GENE AND GRACE KELLY
SAME NAME|WHOOPI AND RUBE GOLDBERG
SAME NAME|WILLIAM AMANDA AND ROBERT BLAKE
SAME NAME|WOODY MARTY AND ETHAN ALLEN
THINGS|ASTEROIDS
THINGS|ATOMIC SUBMARINES
THINGS|BAR AND DUMBBELL SET
THINGS|CARPENTER ANTS
THINGS|CARVING KNIVES
THINGS|COMPUTER CHIPS
THINGS|DOMINOES
THINGS|ICE SKATES
THINGS|INDEX CARDS
THINGS|JOYSTICKS
THINGS|LIBRARY BOOKS
THINGS|LYMPH NODES
THINGS|MATH PROBLEMS
THINGS|METEORITES
THINGS|MEZZANINE SEATS
THINGS|MONTHLY BILLS
THINGS|MOSQUITOES
THINGS|NAUTILUS EQUIPMENT
THINGS|PARALLEL BARS
THINGS|RUFFLED CURTAINS
THINGS|SCIENCE EXPERIMENTS
THINGS|SOCIAL SECURITY BENEFITS
THINGS|STORM CLOUDS
THINGS|TAX REFUND CHECKS
THINGS|THIRD- DEGREE BURNS
THINGS|UNDERWATER GOGGLES
THINGS|VIDEO CASSETTE RECORDERS
THINGS|WANTED POSTERS
THINGS|WATER SKIS
THINGS|FOREIGN FILMS
THINGS|OLD NEWSPAPERS
THINGS|GARDEN WEEDS
THINGS|GUERNSEY COWS
`;