
function wofFindPuzzles($parentDiv,wordList)
{
	
	let regEx = createRegExFromCharMap($parentDiv);
	
	if (regEx==null) return;
	
	let results = wordList.match(regEx);
	
	let matchMessage = "";
	let freqMessage = ""
	if (results == null)
	{
		message = "No matches";
		freqMessage="";
	}
	else
	{
		message = results.join("\n");
		let freqMap = results2CharFreqMap(results);
		freqMessage = charFreqMap2Message(freqMap);
	}

	$parentDiv.find("textarea.results").first().val(message);
	$parentDiv.find("textarea.freq").first().val(freqMessage);
}

function results2CharFreqMap(resultsArr)
{
	let result="", letter="", i=0;
	let map = new Map();
	let charCounts = {}
	
	//for (result in resultsArr)
	//{
	resultsArr.forEach(result => {
		let realAnswer = result.split("|")[1];

		for (i=0; i<realAnswer.length; i++)
		{
			letter = realAnswer.charAt(i);
			//addOneToMap(map,letter);
			if (letter > 'Z' || letter < 'A') continue;
			
		    charCounts[letter] = ++charCounts[letter] || 1;
		}
	});
	
	return charCounts;
}

function addOneToMap(map,letter)
{
	let curCount = map.get(letter);
	if (curCount < 0) curCount=1;
	
	curCount += 1;
	
	map.set(letter,curCount);
}

function charFreqMap2Message(freqMap)
{
	//let mapCounts = new Map();
	let mapCounts= {};
	let letter="";
	
	//first organize letter counts into groupings based on count
	for (letter of Object.keys(freqMap))
	{
		let letterCount = freqMap[letter];
		let charList = mapCounts[letterCount];
		
		if (!charList || charList.length == 0)
		{
			charList = "";
		}
		
		charList += letter;
		
		mapCounts[letterCount]=charList;
	}
	
	//now iterate the counts and show letters for each count (decreasing)
	let message = "";
	let keyArray = Object.keys(mapCounts).map(value => parseInt(value));
	keyArray.sort((a,b)=>b-a);
	//for (var count in keyArray)
	keyArray.forEach(count => {
		let currentLine=""
		currentLine += (""+count).padStart(3) + ": "
		let letters = mapCounts[count];
		for (letter of letters)
		{
			currentLine += letter + " ";
		}
		message += currentLine + "\n";
	});
	
	return message;
}

function createRegExFromCharMap($parentElem)
{
	let $inputElem = $parentElem.find("input.charMap").first();
	let $categoryList = $parentElem.find("input.category");
	let charMap = $inputElem.val();
	let firstWord = true;
	let categoryString = "";
	let pattern = "";
	//if (charMap.length == 0 ) return;
	
	//Create the list of categories from  the inputs
	$categoryList.each(function() {
		if ($(this).is(":checked"))
		{
			if (!firstWord)
			{
				categoryString += "|"
			}
			categoryString += $(this).val();
			firstWord = false;
		}
	});

	if (categoryString.length==0)
	{
		pattern = ".*\\|";
	}
	else
	{
		pattern = categoryString + "\\|";
	}

	let charCounts = charMap.split(" ");
	firstWord = true;
	for (let i=0; i<charCounts.length; i++)
	{
		let charCount = charCounts[i];
		if (charCount.length == 0) continue;
		if (isNaN(charCount)) continue;
		if (!firstWord)
		{
			pattern += ' ';
		}
		
		pattern += '[\\w\'-]{' + charCount + '}';

		firstWord = false;
	}
	
	if (pattern.length > 0)
	{
		pattern = '^' + pattern + '[ ]?$';
		return new RegExp(pattern,'gmi');
	}
	
	return null;
}


let wofAnswers=
`
KINGSTON JAMAICA
PEKING CHINA
PLANETARIUM
NOME ALASKA
YELLOWSTONE NATIONAL PARK
LEXINGTON KENTUCKY
OVAL OFFICE
LA GUARDIA AIRPORT
SAN LUIS OBISPO
SALEM OREGON
FORT KNOX
TIMES SQUARE
MOBILE ALABAMA
THE EVERGLADES
THE FAR CORNERS OF THE EARTH
STATE CAPITOL
ALCATRAZ
LOUISVILLE KENTUCKY
MIDDLE ATLANTIC STATES
WARSAW POLAND
THE CUMBERLAND PASS
THE VATICAN
LAKE PLACID
CINCINNATI
SANTIAGO CHILE
CARLSBAD CAVERNS
FISHERMAN'S WHARF
CHINATOWN
MONTICELLO
TUCSON ARIZONA
EXECUTIVE WASHROOM
ALBANY NEW YORK
NEW ZEALAND
LOST AND FOUND COUNTER
DOWN UNDER
PLAYGROUND
SACRAMENTO
TOP OF THE HEAP
NOTTINGHAM ENGLAND
HELSINKI FINLAND
FRONT ROW CENTER
ATLANTIC CITY
THE PENTAGON
ALEXANDRIA VIRGINIA
OUTER SPACE
PORTLAND MAINE
UPPER RIGHTHAND CORNER
SYDNEY AUSTRALIA
CENTER STAGE
HANNIBAL MISSOURI
CORNER DRUGSTORE
PENTHOUSE SUITE
BURBANK CALIFORNIA
THE PAINTED DESERT
COMBAT ZONE
BOOT HILL
SANTA ANITA RACETRACK
ANDOVER MARYLAND
ANAHEIM STADIUM
OUT OF THE WAY
MUNICH GERMANY
MINE SHAFT
ORLANDO FLORIDA
THE HOLY LAND
SAUDI ARABIA
THE BACKWOODS
ELLIS ISLAND
SAN JUAN PUERTO RICO
IRELAND
WESTERN HEMISPHERE
FROZEN FOOD SECTION
MONTEGO BAY
DENTIST'S OFFICE
GREENWICH VILLAGE
BARNYARD
MANHATTAN ISLAND
THE GROUND FLOOR
UNIVERSAL STUDIOS
THE LOUVRE
MADRID SPAIN
UNDER THE CHRISTMAS TREE
HONOLULU
DETROIT MICHIGAN
DOWN BY THE OLD MILL STREAM
MIDDLE OF THE ROAD
EAST PAKISTAN
IN THE ATTIC
FLORENCE ITALY
CENTER COURT
O'HARE AIRPORT
IN THE MIDDLE OF THE RING
CARACAS VENEZUELA
CITY HALL
BERN SWITZERLAND
HOMETOWN
NEWPORT BEACH
CONTINENTAL DIVIDE
HIDDEN COMPARTMENT
SMOKY MOUNTAINS
THE EQUATOR
NEXT TO LAST
ATHENS GEORGIA
PIZZA PARLOR
HIROSHIMA
BOWLING ALLEY
MILWAUKEE
THE BALCONY
UPPER ATMOSPHERE
THE BOTTOM RUNG
RADIO CITY MUSIC HALL
VIENNA AUSTRIA
ACAPULCO
AUSTIN TEXAS
ON THE PERIMETER
UP THE ROAD APIECE
ANNAPOLIS
STUTTGART GERMANY
GRAND CENTRAL STATION
ON THE HIGH SEAS
TIMES SQUARE
ZIMBABWE AFRICA
HAWAIIAN ISLANDS
CAPE COD
SEASIDE
BANGKOK THAILAND
THE BACK ROW
PAWNSHOP
CAIRO EGYPT
SCHOOL ROOM
CARIBBEAN
SEOUL KOREA
GOVERNOR'S MANSION
VIENNA AUSTRIA
AROUND THE BEND
UNITED STATES NAVAL ACADEMY
FAIRFAX NOVA SCOTIA
ON THE OUTSIDE LOOKING IN
NEW DELHI INDIA
HONG KONG
HOUSTON ASTRODOME
LOWER MANHATTAN
WALL STREET
DURHAM NORTH CAROLINA
SUPERMARKET
ANCHORAGE
ASIA MINOR
STILLWATER OKLAHOMA
THEATER BALCONY
ETHIOPIA
OUTER MONGOLIA
SPRINGFIELD ILLINOIS
LAUNDROMAT
TIJUANA MEXICO
MISSISSIPPI
KATMANDU
BROOKLYN
HARVARD MEDICAL SCHOOL
HIMALAYAN MOUNTAINS
SAN DIEGO
RHODE ISLAND
BROOM CLOSET
DISNEYLAND
COLUMBIA
ROME ITALY
BASEBALL DIAMOND
BASKETBALL COURT
COPERNICUS
THURGOOD MARSHALL
CHAMBERMAID
WOODY ALLEN
SHOESHINE BOY
GEORGE WASHINGTON CARVER
SIGMUND FREUD
LYNDON BAINES JOHNSON
TELEPHONE OPERATOR
GAS STATION ATTENDANT
BERT PARKS
SHORT- ORDER COOK
COMPANY CLERK
HEAD FOOTBALL COACH
ELEANOR ROOSEVELT
THOMAS PAINE
MEDICAL DOCTOR
ENGINEER
MILLARD FILLMORE
DIESEL MECHANIC
CHURCH USHER
TOP BANANA
GARBAGE COLLECTOR
NATHAN HALE
REGIONAL DIRECTOR
COAL MINER
ORTHOPEDIC SURGEON
ANGIE DICKINSON
CHESS CHAMPION
APPLIANCE REPAIRMAN
ROBERT KENNEDY
ASSISTANT DIRECTOR
PHYSICAL THERAPIST
BABE RUTH
BABY SITTER
BALLET DANCER
SECRET AGENT
COMPUTER PROGRAMMER
HUMAN BEING
ARCHBISHOP OF CANTERBURY
SALES CLERK
MICHAEL CAINE
THE PARISH PRIEST
LAW STUDENT
CHANCELLOR
ISAAC NEWTON
BOOKER T WASHINGTON
INDIRA GANDHI
BEN FRANKLIN
MARTIN LUTHER KING
NAPOLEON BONAPARTE
CARL SANDBURG
EDGAR ALLEN POE
THOMAS JEFFERSON
CAKE DECORATOR
DEFENSIVE TACKLE
UNINVITED GUEST
ANGLO- SAXON
UNDERWRITER
WINSTON CHURCHILL
DIRECTOR OF MARKETING
CARRIE NATION
ENGLISH TEACHER
NIGHT WATCHMAN
ALEXANDER GRAHAM BELL
CONVENTION DELEGATE
NEXT DOOR NEIGHBOR
LADYBIRD JOHNSON
MEDICAL STUDENT
VINCE LOMBARDI
TALENT SCOUT
NIKITA KRUSCHEV
JIMMY CONNERS
WILLIAM THE CONQUEROR
NEWSPAPER COLUMNIST
PUBLISHED AUTHOR
JULIUS CAESAR
SMOOTH TALKER
HAIR STYLIST
THEODORE ROOSEVELT
CIVILIAN
THE SHAH OF IRAN
SERGEANT YORK
REAL ESTATE BROKER
TOMMY DORSEY
CAMP COUNSELOR
SALVADOR DALI
ELIGIBLE BACHELOR
JILTED SUITOR
BILLIE JEAN KING
SYSTEMS ANALYST
POCAHONTAS
INNOCENT BYSTANDER
THOMAS EDISON
CLASS CLOWN
RALPH WALDO EMERSON
MATA HARI
HIGH SCHOOL DROPOUT
ADJUTANT GENERAL
ELEVATOR OPERATOR
FRANK LLOYD WRIGHT
EXPECTANT MOTHER
JOHN GLENN
ALBERT SCHWEITZER
JACK-OF- ALL-TRADES
MORTICIAN
ALEXANDER HAMILTON
CONSTANT COMPANION
ARISTOTLE ONASSIS
ESCAPED CONVICT
ANN LANDERS
RIGHT-HAND MAN
AARON BURR
MARIE ANTOINETTE
ANTIQUE COLLECTOR
ANIMAL TAMER
ARNOLD PALMER
HEAD UMPIRE
THE LAST MAN ON EARTH
DANIEL BOONE
BARRY GOLDWATER
APPRENTICE
ICE-CREAM VENDOR
JOHNNY COME LATELY
FERDINAND MAGELLAN
TICKET TAKER
BRUCE SPRINGSTEEN
JACKIE COOPER
UNDERMINER
PAPERHANGER
BLACKSMITH
MARQUIS DE SADE
MECHANICAL ENGINEER
CESAR CHAVEZ
HEAD WAITER
EUROPEAN IMMIGRANT
MENACHEM BEGIN
SEVENTH-DAY ADVENTIST
NAILBITER
ANDREW JACKSON
DISK JOCKEY
KEEPER OF THE FLAME
EVANGELIST
DALE CARNEGIE
WILLIAM SHAKESPEARE
GIFTED CHILD
SAM HOUSTON
GROVER CLEVELAND
JASON ROBARDS
PHILANDERER
CAMERAMAN
WILLIAM RANDOLPH HEARST
SNAKE CHARMER
MEREDITH BAXTER BIRNEY
CERTIFIED PUBLIC ACCOUNTANT
BUS DRIVER
LEONARD BERNSTEIN
NAVIGATOR
MAO TSE- TUNG
CZAR NICHOLAS
PERSONNEL DIRECTOR
CONFUCIUS
KAREEM ABDUL- JABBAR
ANDY WARHOL
HIRED HAND
WILT CHAMBERLAIN
ELECTED OFFICIAL
CLASSMATE
STATE SENATOR
MINNESOTA FATS
PUPPETEER
JAMES MADISON
OBJECTIVE OBSERVER
WYATT EARP
EUCLID
DANNY THOMAS
REMBRANDT
POLITICAL POLLSTER
SAINT FRANCIS OF ASSISI
LAWRENCE OLIVIER
JESSE JAMES
HARRY TRUMAN
TAX COLLECTOR
MUHAMMAD ALI
COMMITTEE CHAIRMAN
DWIGHT DAVID EISENHOWER
NOVELIST
SIR WALTER RALEIGH
CITY PLANNER
GALILEO
CLAIMS ADJUSTER
GOLD KEYCHAIN
PORKPIE HAT
CRANBERRY SAUCE
PLUTONIUM
BOTTLED WATER
TURNTABLE
BEAMED CEILING
HANGNAIL
STUDHORSE
HAIRPIN
PIGGY BANK
CANTALOUPE
JUMPING JACK
BAKING SODA
NEW ENGLAND CLAM CHOWDER
LIQUOR CABINET
APPLE CIDER
PUNCTUATION MARK
DANDELION
PHONOGRAPH RECORD
ORGANIC COMPOUND
SPLIT PEA SOUP
BIRD FEEDER
CHOCOLATE CHIP COOKIE
MOSQUITO
BUTTERCUP
WEDDING RING
POLLING BOOTH
ENGLISH MUFFIN
SOUP LADLE
INCLEMENT WEATHER
BLACK OLIVE
VEGETABLE OIL
CONTRACTION
TIMEPIECE
COCONUT
HEDGE CLIPPER
HORSESHOE
CHRISTMAS TREE
HOMEMADE BREAD
ROLLER SKATE
INTEGRATED CIRCUIT
PATCHWORK
SKYSCRAPER
THERMOMETER
TOMATO SAUCE
MUSICAL NOTE
POTATO SKIN
SALAMANDER
FISHING LURE
PRINTING PRESS
MEAT CLEAVER
TELEVISION ANTENNA
LOUNGE CHAIR
GREEN PEPPER
DUMBWAITER
SNOWMOBILE
WINDSHIELD WIPER
MIGRAINE HEADACHE
HANDMADE QUILT
SALT SHAKER
TOOTHACHE
BROKEN SPOKE
ACHILLES HEEL
DEPLETION ALLOWANCE
CORKSCREW
PACK ANIMAL
CHINESE FOOD
SAUSAGE PATTY
REVOLVING DOOR
CASHIER'S CHECK
CAN OPENER
JACKET POCKET
HAIRPIN
BLOCK AND TACKLE
BAKED POTATO
PENCIL SHARPENER
CALCULATOR
AFFIDAVIT
EXTENDED WARRANTY
HORS D'OEUVRE
UNSALTED PEANUT
WINDMILL
SHOOTING STAR
MICROWAVE OVEN
TUXEDO
COMMON SENSE
LONG DISTANCE PHONE CALL
VIOLIN CASE
LEAST COMMON DENOMINATOR
HARVEY WALLBANGER
HANG GLIDER
ESCALATOR
CORN ON THE COB
MONOCLE
RUBBER BAND
INGROWN TOENAIL
LACERATED CONTUSION
HUMMINGBIRD
LULLABY
FUEL INJECTOR
AIRCRAFT CARRIER
SHOE POLISH
MERRY-GO- ROUND
UNSOLICITED RESPONSE
CHESTNUT
SOUP OF THE DAY
SAUERKRAUT
ELECTRIC BLANKET
WATERMELON
HUMPBACK WHALE
CHURCH STEEPLE
INCOME TAX RETURN
CUBIC METER
TORN LIGAMENT
SUGAR CUBE
BACK INVENTORY
SUBMARINE
SMOKED OYSTER
THUMBTACK
MORNING NEWSPAPER
GRASSHOPPER
AREA CODE
TOOTHPICK
CORN POPPER
DRIVER'S LICENSE
MANNEQUIN
WASHING MACHINE
PEN AND PENCIL SET
HARPSICHORD
PLASTER CAST
CHINESE ALGEBRA
KITCHEN TABLE
CUMMERBUND
CIGARETTE LIGHTER
RADIO TRANSMITTER
CRUDE OIL
SOUR NOTE
MEATBALL
FISHING POLE
DOLLAR BILL
ALLIGATOR
HANDLEBAR MOUSTACHE
WINDOW PANE
SCRATCH PAD
BABY CARRIAGE
LIBRARY CARD
EIGHTEEN WHEELER
ENCHILADA
BAROMETER
PORTRAIT
OBITUARY
WALKING CANE
FRIED RICE
COLLECTOR'S ITEM
CORRUGATED ALUMINUM
SUNDAY FUNNIES
SILVER DOLLAR
THE GRAND CANYON
MADISON SQUARE GARDEN
THE LONDON BRIDGE
EMPIRE STATE BUILDING
THE EIFFEL TOWER
GREAT WALL OF CHINA
THE ALAMO
THE LIBERTY BELL
LINCOLN MEMORIAL
THE BERLIN WALL
HOOVER DAM
GOLDEN GATE BRIDGE
THE TAJ MAHAL
THE SWISS ALPS
GRANT'S TOMB
PIKE'S PEAK
THE OK CORRAL
THE GRAND OLE OPRY
THE PETRIFIED FOREST
NOTRE DAME CATHEDRAL
CAPE CANAVERAL
DON'T ROCK THE BOAT
ON THE UP AND UP
THE DEVIL MADE ME DO IT
THERE'S PLENTY FOR EVERYBODY
DON'T FORGET TO READ THE FINE PRINT
IT'S THE NEXT BEST THING TO BEING THERE
DON'T BE A BACK SEAT DRIVER
TIME IS MONEY
TOO MANY COOKS SPOIL THE BROTH
MANY ARE CALLED BUT FEW ARE CHOSEN
PRIDE GOETH BEFORE THE FALL
IT COMES AND GOES
IT'S ONLY THE TIP OF THE ICEBERG
FOR THE MAN WHO HAS EVERYTHING
THERE'S NO SUCH THING AS A FREE LUNCH
IT'S FOR A GOOD CAUSE
DON'T START SOMETHING YOU CAN'T FINISH
IT'S THE LAW OF THE LAND
LET SLEEPING DOGS LIE
TAKING IT EASY
DON'T BITE THE HAND THAT FEEDS YOU
LOOK BOTH WAYS BEFORE CROSSING
DON'T SPEND IT ALL IN ONE PLACE
OUT TO LUNCH
TAKE TWO ASPIRIN AND CALL ME IN THE MORNING
PERISH THE THOUGHT
YOU CAN'T SAY I DIDN'T WARN YOU
GOOD TABLE MANNERS
EVERY LITTLE BIT COUNTS
MAKING A MOUNTAIN OUT OF A MOLEHILL
THE PROOF IS IN THE PUDDING
SOME GUYS HAVE ALL THE LUCK
DON'T JUMP THE GUN
THE MEANING IS LOST IN THE TRANSLATION
IT'S JUST WATER UNDER THE BRIDGE
NOW THAT THE SHOE IS ON THE OTHER FOOT
OVERLY EXCITED
CLOSED FOR REMODELING
RIPE FOR THE PICKING
JUST WHEN YOU THOUGHT YOU'D HEARD EVERYTHING
FROM THE CRADLE TO THE GRAVE
PLAYING FOR KEEPS
MY BACK'S AGAINST THE WALL
TURN THE OTHER CHEEK
HITTING BELOW THE BELT
I'M HOLDING MY OWN
UNDER THE WEATHER
NOT ON YOUR LIFE
THERE'S SOMETHING FOR EVERYBODY
NEVER SAY NEVER
SAVE IT FOR A RAINY DAY
WITHIN A BLINK OF AN EYE
DON'T LOOK BACK
THERE'S A SUCKER BORN EVERY MINUTE
NEVER AT A LOSS FOR WORDS
LET THE GOOD TIMES ROLL
ON COMMON GROUND
TOO LITTLE TOO LATE
THIRD RATE ROMANCE
TAKEN FOR GRANTED
NOT TOO BAD UNDER THE CONDITIONS
HOPE TO SEE YOU SOON
EARN WHILE YOU LEARN
HELPFUL HINT
WINNER AND STILL CHAMPION
NOTHING BUT THE FACTS
ALL OR NOTHING
EVERY MAN FOR HIMSELF
SOMETHING FOR NOTHING
LOVE IT OR LEAVE IT
A DIAMOND IN THE ROUGH
BLOWING HOT AND COLD
OPENING UP A CAN OF WORMS
TWIDDLING YOUR THUMBS
HONESTY IS THE BEST POLICY
BURSTING AT THE SEAMS
SIGN ON THE DOTTED LINE
FLICK OF THE WRIST
A NEW BROOM SWEEPS CLEAN
WISH YOU WERE HERE
GETTING DOWN TO BRASS TACKS
NEAT AS A PIN
HIGH JINKS
THE SOONER THE BETTER
EVERYTHING BUT THE KITCHEN SINK
TAKE THE BULL BY THE HORNS
DOUBLE OR NOTHING
CHARITY BEGINS AT HOME
TAKE A BREAK
TAKE IT AS IT COMES
TOO MUCH TOO SOON
SEEING IS BELIEVING
SOMETHING HAS TO BE DONE ABOUT IT
BLOOD IS THICKER THAN WATER
BELIEVE IT OR NOT
EVERY DOG HAS ITS DAY
SEVEN COME ELEVEN
SOME THINGS ARE BETTER LEFT UNSAID
MAKE ME AN OFFER
CLOSE COVER BEFORE STRIKING
KEEP YOUR GUARD UP
NO LAUGHING MATTER
SOME PEOPLE NEVER LEARN
IT JUST DOESN'T ADD UP
BEHIND THE EIGHT BALL
DON'T COUNT ON IT
BY THE GRACE OF GOD
LEAVE IT BE
ON CLOUD NINE
UNDER THE TABLE
DON'T TAKE IT FOR GRANTED
MAYBE SO AND MAYBE NOT
AT THE CROSSROADS
TAKE IT TO THE LIMIT
OVER-THE- COUNTER
IN THE DOGHOUSE
MY TWO CENTS WORTH
OVER THE HILL
BRINGING UP THE REAR
THE STRAW THAT BROKE THE CAMEL'S BACK
COMING OF AGE
THE MORE THE MERRIER
THE LAST PLACE YOU'D THINK OF
HAPPY DAYS ARE HERE AGAIN
THE WHOLE NINE YARDS
GO TO THE HEAD OF THE CLASS
IN THE TWINKLING OF AN EYE
RETURN TO SENDER
I'VE HAD IT UP TO HERE
THE LONG AND SHORT OF IT
THE BOTTOM OF THE BARREL
HOLD THE PHONE
ON THE RAZOR'S EDGE
LET THE CHIPS FALL WHERE THEY MAY
THE WRONG SIDE OF THE TRACKS
STOP THE PRESSES
THE WORM HAS TURNED
NO USE CRYING OVER SPILLED MILK
CASH AND CARRY
CRIME DOESN'T PAY
BOY MEETS GIRL
NOTHING BUT THE BEST
THE GOLDEN RULE
ONE GOOD TURN DESERVES ANOTHER
KEEP A STIFF UPPER LIP
HE WHO LAUGHS LAST
ON THE RIGHT TRACK
SECOND TO NONE
IN THE RIGHT FRAME OF MIND
DON'T TAKE ANY WOODEN NICKELS
SO BE IT
LET'S MAKE A DAY OF IT
LOOK IT UP
THE BEST AND THE BRIGHTEST
IT'S OPEN FOR DISCUSSION
THE JOKE'S ON YOU
THE BUCK STOPS HERE
STANDING ROOM ONLY
RIGHT BETWEEN THE EYES
GONE BUT NOT FORGOTTEN
THE TIME IS NOW
THE CREAM ALWAYS RISES TO THE TOP
MY CUP RUNNETH OVER
THERE'S NO DOUBT ABOUT IT
YOU CAN BANK ON IT
OVER AND OUT
YOU CAN TAKE MY WORD ON IT
LIFE IS FOR THE LIVING
LEND ME AN EAR
LONG LIVE THE KING
THERE'S NOTHING TO IT
I CAN'T GET NO RELIEF
THE AGONY AND THE ECSTASY
PAUL REVERE'S RIDE
MAKE THE MOST OF IT
TALK IS CHEAP
SQUEAKY CLEAN
THERE'S NO EXCUSE FOR IT
ON THE BUTTON
DON'T LEAVE WITHOUT SAYING GOODBYE
YOU GO YOUR WAY AND I'LL GO MINE
ONE HAND WASHES THE OTHER
IT'S BIGGER THAN THE BOTH OF US
I'LL MEET YOU HALFWAY
DON'T CALL US WE'LL CALL YOU
DON'T BITE OFF MORE THAN YOU CAN CHEW
LOOK ME IN THE EYE AND SAY THAT
GOING FOR BROKE
BANANA SPLITS
CEILING FANS
BLUEPRINTS
TENNIS SHOES
CLING PEACHES
FINGERNAIL CLIPPERS
CHAPPED LIPS
HORSE AND BUGGY
PAIRS OF SHOES
BACON AND EGGS
MACARONI AND CHEESE
BREAD AND BUTTER
BEER AND PRETZELS
APPLES AND ORANGES
NEEDLES AND PINS
ANIMAL VEGETABLE OR MINERAL
CAT AND MOUSE
CHICKEN AND DUMPLINGS
BOWS AND ARROWS
CHEESE AND CRACKERS
HASH BROWN POTATOES
HAMMER AND NAIL
STARS AND STRIPES
PEACHES AND CREAM
CLOAK AND DAGGER
ARM AND HAMMER
PORK AND BEANS
THE EXODUS
WHITE CHRISTMAS
LIEUTENANT COLONEL
EXECUTIVE VICE- PRESIDENT
SECRETARY OF DEFENSE
SPEAKER OF THE HOUSE
BRIGADIER GENERAL
CHIEF-OF- POLICE
NATIONAL VELVET
COMMANDER- IN-CHIEF
SURGEON GENERAL
SECRETARY OF THE INTERIOR
POSTMASTER GENERAL
SERGEANT- AT-ARMS
UNCHAINED MELODY
SENATE MAJORITY WHIP
GONE WITH THE WIND
DISTRICT ATTORNEY
PRIME MINISTER
THE DAYS OF WINE AND ROSES
LOVE LETTERS IN THE SAND
NONE BUT THE BRAVE
RETURN OF THE JEDI
THE GOOD THE BAD AND THE UGLY
MOON RIVER
SOMEWHERE OVER THE RAINBOW
HEAVYWEIGHT CHAMPION
DUCHESS OF WINDSOR
WHERE EAGLES DARE
THE AFRICAN QUEEN
DIAL M FOR MURDER
THE EMPIRE STRIKES BACK
THE NAKED AND THE DEAD
BEETHOVEN'S NINTH
INSPECTOR GENERAL
THE DIRTY DOZEN
THE STING
A CLOCKWORK ORANGE
MISSION IMPOSSIBLE
THE GHOST AND MRS MUIR
MAN OF LA MANCHA
APOCALYPSE NOW
BRIDGE ON THE RIVER KWAI
THE SANDS OF IWO JIMA
THE HIGH AND THE MIGHTY
SEND IN THE CLOWNS
I DID IT MY WAY
LOVE STORY
BREAKFAST AT TIFFANY'S
THE LEGEND OF SLEEPY HOLLOW
TWINKLE TWINKLE LITTLE STAR
IF I WERE A RICH MAN
PSYCHO
A NIGHT AT THE OPERA
ATTORNEY GENERAL
BEN HUR
THE GUNS OF NAVARONE
BEAUTY AND THE BEAST
THE OLD MAN AND THE SEA
SESAME STREET
NEVER ON SUNDAY
THE GREAT GATSBY
THE SUN ALSO RISES
THE BLACKBOARD JUNGLE
OF MICE AND MEN
JINGLE BELLS
THE RISE AND FALL OF THE ROMAN EMPIRE
TOOTSIE
THE LAST DAYS OF POMPEII
MAJOR GENERAL
GENTLEMEN PREFER BLONDES
THE POSTMAN ALWAYS RINGS TWICE
THE FRENCH CONNECTION
IN COLD BLOOD
WAR AND PEACE
ANNIE HALL
THE THREE LITTLE PIGS
THE GRAPES OF WRATH
THE RED PONY
DOCTOR ZHIVAGO
THE THREE FACES OF EVE
PRIDE AND PREJUDICE
SPARTACUS
MARY POPPINS
I WANT TO HOLD YOUR HAND
FANTASIA
SNOW WHITE
SATURDAY NIGHT LIVE
CRIME AND PUNISHMENT
BONNIE AND CLYDE
PLEASE DON'T EAT THE DAISIES
HEARTBREAK HOTEL
THE LAST OF THE MOHICANS
PORGY AND BESS
THE FRONT PAGE
LOVE ME TENDER
WIDE WORLD OF SPORTS
GOODBYE MISTER CHIPS
THE ELEPHANT MAN
THE ILIAD
THE CALL OF THE WILD
SATURDAY NIGHT FEVER
FIDDLER ON THE ROOF
TENNESSEE WALTZ
PLANET OF THE APES
BLUE CROSS AND BLUE SHIELD
LION'S CLUB
COMMUNIST PARTY
UNITED NATIONS
BOY SCOUTS OF AMERICA
LITTLE LEAGUE BASEBALL
THE WRITER'S GUILD
DAUGHTERS OF THE AMERICAN REVOLUTION
UNIFIED SCHOOL DISTRICT
CIVIL LIBERTIES UNION
SCREEN ACTOR'S GUILD
NATIONAL FOOTBALL LEAGUE
THE ELK'S CLUB
AMERICAN AUTOMOBILE ASSOCIATION
RED CROSS
COMMON CAUSE
CHURCH CHOIR
GREEN BAY PACKERS
PRESIDENT'S CABINET
CHURCH OF LATTER-DAY SAINTS
NATIONAL SECURITY COUNCIL
FIRE DEPARTMENT
NATIONAL HOCKEY LEAGUE
DEMOCRATIC PARTY
PITTSBURGH PIRATES
TEXTILE WORKERS' UNION
DAIRYMEN'S ASSOCIATION
SECURITIES EXCHANGE COMMISSION
FRATERNAL ORDER OF POLICE
BETTER BUSINESS BUREAU
CONTINENTAL CONGRESS
CANADIAN MOUNTED POLICE
TEXAS RANGERS
KIWANIS CLUB
BIG BROTHERS OF AMERICA
MUSCULAR DYSTROPHY ASSOCIATION
AMERICAN LEGION
WEIGHT WATCHERS
YOUNG MEN'S CHRISTIAN ASSOCIATION
AMERICAN AIRLINES
KNIGHTS OF COLUMBUS
REPUBLICAN NATIONAL COMMITTEE
THREE DAY WEEKEND
ROSE BOWL PARADE
KENTUCKY DERBY
DINNER AT THE WHITE HOUSE
THE WORLD SERIES
GRADUATION DAY
LODGE MEETING
ELECTION DAY
STANLEY CUP PLAYOFFS
CORONATION
GROUND HOG'S DAY
THE IRISH SWEEPSTAKES
RETIREMENT PARTY
POLICEMAN'S BALL
HOMECOMING
MARDI GRAS
NEW YEAR'S EVE PARTY
TULIP FESTIVAL
ANTIQUE SHOW
INDIAN POW-WOW
SPRING VACATION
WEDDING DAY
MORTGAGE BURNING PARTY
CORPORATE MERGER
BIRTHDAY
THE OLYMPIC GAMES
COMING OUT PARTY
CAMPAIGN FUND DRIVE
LINCOLN'S BIRTHDAY
BEAUTY PAGEANT
SENIOR PROM
WIMBLEDON TENNIS TOURNAMENT
GRAND OPENING
TWO-FOR-ONE SALE
SHIP LAUNCHING
SILVER ANNIVERSARY
TOTAL ECLIPSE OF THE SUN
FIRST DATE
STATE OF THE UNION ADDRESS
MOVIE PREMIERE
BABY SHOWER
EASTER SUNDAY
THE SUPERBOWL
FIRST COMMUNION
SUNDAY SERVICES
BOSTON TEA PARTY
GOING OUT OF BUSINESS SALE
HOLLOWEEN
FAMILY REUNION
LINCOLN AND DOUGLAS DEBATE
STATE FAIR
KENTUCKY DERBY
THE CIVIL WAR
FIRST SNOWFALL
ACADEMY AWARDS
PAYDAY
THE SEASON OPENER
HANUKKAH
THE FIRST DAY OF SCHOOL
CHRISTMAS EVE
THE FIRST DAY OF SPRING
SURRENDER AT APPOMATAX
SERMON ON THE MOUNT
BABY'S FIRST TOOTH
HIGH SCHOOL REUNION
THE FRENCH REVOLUTION
FOURTH OF JULY PICNIC
THE LAST SUPPER
THE RETURN OF HALLEY'S COMET
FRATERNITY RUSH PARTY
VALENTINE'S DAY
YOM KIPPUR
THE PEACE CORPS
CHRISTENING
NORMANDY INVASION
MOON LANDING
BARN RAISING
BASTILLE DAY
WOODSTOCK
BOSTON MARATHON
CAR AUCTION
MILITARY DISCHARGE
BACHELOR PARTY
MISS UNIVERSE PAGEANT
RELIGIOUS RETREAT
SPANISH INQUISITION
PASSOVER
WATERGATE
INDIAN RAIN DANCE
WORLD CUP SOCCER MATCH
HAWAIIAN LUAU
LOUISIANA PURCHASE
THE AMERICA'S CUP RACE
VERSAILLES TREATY
FRENCH AND INDIAN WAR
TURN OF THE CENTURY
SPANISH- AMERICAN WAR
ARMED FORCES DAY
ARMISTICE DAY
MEMORIAL DAY
CHINESE NEW YEAR
REPORT CARD DAY
FIRST DAY ON THE JOB
`;

let wofJuniorAnswers02=
`
PLACE|ACAPULCO MEXICO
PLACE|ALCATRAZ
PLACE|AMAZON RIVER
PLACE|AMUSEMENT PARK
PLACE|ANTARCTICA
PLACE|APARTMENT HOUSE
PLACE|ARCTIC CIRCLE
PLACE|ATLANTIC OCEAN
PLACE|AUDITORIUM
PLACE|BASEBALL HALL OF FAME
PLACE|BEVERLY HILLS
PLACE|BOARDING SCHOOL
PLACE|BOWLING ALLEY
PLACE|CAIRO EGYPT
PLACE|CALGARY CANADA
PLACE|CAPE CANAVERAL
PLACE|CAPE HATTERAS
PLACE|CEMETERY
PLACE|CLASSROOM
PLACE|COBBLESTONE STREET
PLACE|DALLAS TEXAS
PLACE|DAMASCUS SYRIA
PLACE|DAY-CARE CENTER
PLACE|DEAD SEA
PLACE|DEAD-END STREET
PLACE|DEATH VALLEY
PLACE|DENTIST'S OFFICE
PLACE|DISNEYLAND
PLACE|DOWN ESCALATOR
PLACE|DRIVE-IN THEATER
PLACE|DRIVE-IN WINDOW
PLACE|DUBLIN IRELAND
PLACE|DUDE RANCH
PLACE|ELEMENTARY SCHOOL
PLACE|EMPIRE STATE BUILDING
PLACE|ENGLISH CHANNEL
PLACE|EPCOT CENTER
PLACE|FAST-FOOD RESTAURANT
PLACE|FIREHOUSE
PLACE|FLEA MARKET
PLACE|GAS STATION
PLACE|GOLDEN GATE BRIDGE
PLACE|GULF OF MEXICO
PLACE|GYMNASIUM
PLACE|HACKENSACK NEW JERSEY
PLACE|HALIFAX NOVA SCOTIA
PLACE|HARTFORD CONNECTICUT
PLACE|HAWAIIAN ISLANDS
PLACE|HELSINKI FINLAND
PLACE|HIROSHIMA JAPAN
PLACE|HOOVER DAM
PLACE|HOSPITAL EMERGENCY ROOM
PLACE|INFIRMARY
PLACE|JUPITER
PLACE|KODIAK ISLAND
PLACE|LAS VEGAS NEVADA
PLACE|LAUNDROMAT
PLACE|LEANING TOWER OF PISA
PLACE|LEXINGTON KENTUCKY
PLACE|LIBRARY OF CONGRESS
PLACE|LINE OF SCRIMMAGE
PLACE|LONDON ENGLAND
PLACE|LOS ANGELES CALIFORNIA
PLACE|MERCURY
PLACE|MEXICO CITY
PLACE|MIAMI FLORIDA
PLACE|MILKY WAY GALAXY
PLACE|MISSISSIPPI RIVER
PLACE|MORGUE
PLACE|MOUNT EVEREST
PLACE|MOUNT RUSHMORE
PLACE|MOUNT VESUVIUS
PLACE|NEPTUNE
PLACE|NEW YORK CITY
PLACE|NEW ZEALAND
PLACE|NIAGARA FALLS
PLACE|NORFOLK VIRGINIA
PLACE|NORTH AMERICA
PLACE|OBSERVATION DECK
PLACE|OPERA HOUSE
PLACE|OREGON TRAIL
PLACE|ORPHANAGE
PLACE|OSHKOSH WISCONSIN
PLACE|OUTER SPACE
PLACE|PACIFIC OCEAN
PLACE|PALM SPRINGS CALIFORNIA
PLACE|PANAMA CANAL
PLACE|PARIS FRANCE
PLACE|PAWNSHOP
PLACE|PHILIPPINE ISLANDS
PLACE|PRINCETON UNIVERSITY
PLACE|PUBLIC LIBRARY
PLACE|PUERTO RICO
PLACE|RALEIGH NORTH CAROLINA
PLACE|ROCKY MOUNTAINS
PLACE|ROLLER SKATING RINK
PLACE|SACRAMENTO CALIFORNIA
PLACE|SAINT LAWRENCE SEAWAY
PLACE|SAN DIEGO ZOO
PLACE|SAUDI ARABIA
PLACE|SCHOOL CAFETERIA
PLACE|SLEEP-AWAY CAMP
PLACE|SOUNDPROOF ROOM
PLACE|SOUTH AMERICA
PLACE|SPACE MOUNTAIN
PLACE|STATUE OF LIBERTY
PLACE|SUPERMARKET
PLACE|SWITZERLAND
PLACE|THE BIG DIPPER
PLACE|THE GRAND CANYON
PLACE|THE GREAT LAKES
PLACE|THE KREMLIN
PLACE|THE PRINCIPAL'S OFFICE
PLACE|THE WASHINGTON MONUMENT
PLACE|THE WHITE HOUSE
PLACE|UNITED STATES OF AMERICA
PLACE|VIETNAM
PLACE|WASHINGTON D C
PLACE|WORLD TRADE CENTER
PLACE|YANKEE STADIUM
PLACE|YELLOWSTONE NATIONAL PARK
PLACE|YUGOSLAVIA
PLACE|ZIMBABWE RHODESIA
PLACE|ZION NATIONAL PARK
PERSON|A GOOD SPORT
PERSON|ABNER DOUBLEDAY
PERSON|ABRAHAM LINCOLN
PERSON|AIRLINE PASSENGER
PERSON|ALBERT EINSTEIN
PERSON|ALEXANDER HAMILTON
PERSON|AMBASSADOR
PERSON|ANIMATOR
PERSON|ASTRONAUT
PERSON|ATTORNEY AT LAW
PERSON|AUCTIONEER
PERSON|BABE RUTH
PERSON|BABY-SITTER
PERSON|BALLET DANCER
PERSON|BILL COSBY
PERSON|BILLY JOEL
PERSON|BOZO THE CLOWN
PERSON|BOZO THE CLOWN
PERSON|BRAIN SURGEON
PERSON|BRUCE SPRINGSTEEN
PERSON|BULLFIGHTER
PERSON|BURGLAR
PERSON|CANNIBAL
PERSON|CAPTAIN KANGAROO
PERSON|CHAUFFEUR
PERSON|CHRISTOPHER COLUMBUS
PERSON|CHUCK NORRIS
PERSON|COLLEGE PROFESSOR
PERSON|COUCH POTATO
PERSON|DAN AYKROYD
PERSON|DAN MARINO
PERSON|DANIEL BOONE
PERSON|DARRYL STRAWBERRY
PERSON|DAVID COPPERFIELD
PERSON|DAVID LETTERMAN
PERSON|DAVY CROCKETT
PERSON|DENTAL HYGIENIST
PERSON|DEPUTY SHERIFF
PERSON|DISC JOCKEY
PERSON|DOG CATCHER
PERSON|DON JOHNSON
PERSON|DRY CLEANER
PERSON|EAGER BEAVER
PERSON|EDDIE MURPHY
PERSON|ELVIS PRESLEY
PERSON|EXPLORER
PERSON|EYEWITNESS
PERSON|FAMILY DOCTOR
PERSON|FIRST-PRIZE WINNER
PERSON|FORTUNE TELLER
PERSON|FRANCIS SCOTT KEY
PERSON|GENERAL OF THE ARMY
PERSON|GEORGE WASHINGTON
PERSON|GLASS BLOWER
PERSON|GOVERNOR
PERSON|GUIDANCE COUNSELOR
PERSON|HALF BROTHER
PERSON|HANS CHRISTIAN ANDERSEN
PERSON|HEAVYWEIGHT BOXER
PERSON|HIT-AND-RUN DRIVER
PERSON|HITCH-HIKER
PERSON|HOWARD COSELL
PERSON|HYPNOTIST
PERSON|INDIAN CHIEF
PERSON|JACKIE ROBINSON
PERSON|JERRY LEWIS
PERSON|JOHN FITZGERALD KENNEDY
PERSON|JOHN RITTER
PERSON|JOHNNY APPLESEED
PERSON|JUGGLER
PERSON|LITTERBUG
PERSON|LONG DISTANCE OPERATOR
PERSON|LOUIS PASTEUR
PERSON|MAGICIAN
PERSON|MARILYN MONROE
PERSON|MARTIN LUTHER KING
PERSON|MICHAEL J FOX
PERSON|MICHAEL JACKSON
PERSON|MICKEY MANTLE
PERSON|MIGRANT WORKER
PERSON|MOTHER IN LAW
PERSON|MOUNTAIN CLIMBER
PERSON|OFFENSIVE TACKLE
PERSON|OPRAH WINFREY
PERSON|OUTFIELDER
PERSON|PARATROOPER
PERSON|PEE-WEE HERMAN
PERSON|PHIL DONAHUE
PERSON|PICKPOCKET
PERSON|PINCH HITTER
PERSON|PLATOON SERGEANT
PERSON|PLUMBER
PERSON|PONY EXPRESS RIDER
PERSON|PRINCE
PERSON|PRISONER OF WAR
PERSON|PRIVATE DETECTIVE
PERSON|PROOF- READER
PERSON|QUEEN ELIZABETH
PERSON|QUEEN ISABELLA
PERSON|REGISTERED NURSE
PERSON|RONALD REAGAN
PERSON|SCUBA DIVER
PERSON|SECOND COUSIN
PERSON|SECRET AGENT
PERSON|SENIOR CITIZEN
PERSON|SILENT PARTNER
PERSON|SLEEPWALKER
PERSON|SOCIAL STUDIES TEACHER
PERSON|STAMP COLLECTOR
PERSON|STEVEN SPIELBERG
PERSON|STORE MANAGER
PERSON|SUGAR RAY LEONARD
PERSON|SYLVESTER STALLONE
PERSON|TAXICAB DRIVER
PERSON|TAXPAYER
PERSON|TENNIS INSTRUCTOR
PERSON|THE SCHOOL CUSTODIAN
PERSON|THIRD BASE UMPIRE
PERSON|TINA TURNER
PERSON|TOM CRUISE
PERSON|TRAVELING SALESMAN
PERSON|TROUBLE- MAKER
PERSON|VANNA WHITE
PERSON|VOLUNTEER
PERSON|WEIGHT LIFTER
PERSON|WIDE RECEIVER
PERSON|WILLIAM SHATNER
PERSON|WILLIE MAYS
PERSON|WITCH DOCTOR
PERSON|YOGI BERRA
THING|A HOME COMPUTER
THING|A PAIR OF GLOVES
THING|A RUBBER DUCK
THING|ABACUS
THING|ABSENCE NOTE
THING|ACCORDION
THING|ADHESIVE TAPE
THING|AIR-TO-AIR MISSILE
THING|AIRCRAFT CARRIER
THING|AIRPLANE PROPELLER
THING|ALARM CLOCK
THING|ALLIGATOR
THING|AMERICAN FLAG
THING|ANTIFREEZE
THING|AQUALUNG
THING|AQUARIUM
THING|ARITHMETIC BOOK
THING|ASPARAGUS
THING|AUTOGRAPH BOOK
THING|BABY CARRIAGE
THING|BABY'S FIRST TOOTH
THING|BACKGAMMON
THING|BAKED POTATO
THING|BAKER'S DOZEN
THING|BAKING POWDER
THING|BALLPOINT PEN
THING|BARBECUE GRILL
THING|BARBIE DOLL
THING|BASE HIT
THING|BASEBALL BAT
THING|BASEBALL DIAMOND
THING|BASKETBALL
THING|BATHING SUIT
THING|BEDTIME STORY
THING|BILL OF RIGHTS
THING|BINOCULARS
THING|BIRTH CERTIFICATE
THING|BLACK AND BLUE MARK
THING|BLACK WIDOW SPIDER
THING|BLOOD VESSEL
THING|BOBBY PIN
THING|BOOBY PRIZE
THING|BOOMERANG
THING|BOOSTER SHOT
THING|BROCCOLI
THING|BUBBLE BATH
THING|BUBBLE GUM
THING|BULLETIN BOARD
THING|BULLETPROOF VEST
THING|BUMPER STICKER
THING|BUTTERFLY
THING|BUTTONHOLE
THING|CABBAGE PATCH DOLL
THING|CABIN CRUISER
THING|CACTUS PLANT
THING|CAESAR SALAD
THING|CALAMINE LOTION
THING|CAN OPENER
THING|CANTALOUPE
THING|CARBON DIOXIDE GAS
THING|CARNIVAL
THING|CASH REGISTER
THING|CATERPILLAR
THING|CEMENT MIXER
THING|CHALKBOARD
THING|CHARLEY HORSE
THING|CHECKING ACCOUNT
THING|CHECKOUT LINE
THING|CHICKEN POX
THING|CHIMPANZEE
THING|CHOCOLATE PUDDING
THING|CHRISTMAS STOCKING
THING|CITIZEN'S BAND RADIO
THING|CLAM CHOWDER
THING|COCA-COLA
THING|COCKROACH
THING|COLORING BOOK
THING|COMIC BOOK
THING|COMPACT DISC
THING|COMPOUND WORD
THING|CONTACT LENS
THING|COONSKIN CAP
THING|CORDLESS TELEPHONE
THING|CORN ON THE COB
THING|CORVETTE
THING|COSTUME JEWELRY
THING|COTTAGE CHEESE
THING|COTTON CANDY
THING|COUNTERFEIT MONEY
THING|COUNTRY AND WESTERN MUSIC
THING|COVERED WAGON
THING|CRACKER JACK
THING|CRANBERRY SAUCE
THING|CRASH HELMET
THING|CREDIT APPLICATION
THING|CREDIT CARD
THING|CREPE PAPER
THING|CROSSWORD PUZZLE
THING|DADDY LONGLEGS
THING|DAILY NEWSPAPER
THING|DART BOARD
THING|DENTAL FLOSS
THING|DEPOSIT SLIP
THING|DIACRITICAL MARK
THING|DICTIONARY
THING|DIESEL ENGINE
THING|DIGITAL WATCH
THING|DOG BISCUIT
THING|DOG COLLAR
THING|DOGGIE BAG
THING|DOUBLE HEADER
THING|DRAWBRIDGE
THING|DRIP-DRY SHIRT
THING|DRIVER'S LICENSE
THING|DUFFEL BAG
THING|EGG ROLL
THING|EJECTION SEAT
THING|ELECTRIC CHAIR
THING|ELECTRIC GUITAR
THING|ELECTRIC TRAIN SET
THING|ELECTRON MICROSCOPE
THING|ENGAGEMENT RING
THING|EQUAL SIGN
THING|ESCALATOR
THING|EVENING STAR
THING|EXTENSION CORD
THING|EYE SHADOW
THING|FERRIS WHEEL
THING|FISHING ROD
THING|FLAT TIRE
THING|FLUORESCENT LIGHT
THING|FLUORIDATED WATER
THING|FLYING FISH
THING|FOOD PROCESSOR
THING|FOOTBALL HELMET
THING|FORKLIFT TRUCK
THING|FORTUNE COOKIE
THING|FOUR-LEAF CLOVER
THING|FRENCH TOAST
THING|FRIED RICE
THING|FUNNY BONE
THING|GEIGER COUNTER
THING|GERMAN SHEPHERD DOG
THING|GLASS BOTTOM BOAT
THING|GLOVE COMPARTMENT
THING|GLOWWORM
THING|GRAND SLAM HOME RUN
THING|GRANDFATHER CLOCK
THING|GRANOLA BAR
THING|GRASSHOPPER
THING|GUIDE DOG
THING|GUINEA PIG
THING|HALF-DOLLAR
THING|HAM AND CHEESE SANDWICH
THING|HAMBURGER
THING|HAMMERHEAD SHARK
THING|HAWAIIAN SHIRT
THING|HELICOPTER
THING|HERMIT CRAB
THING|HEXAGON
THING|HIGH SCHOOL DIPLOMA
THING|HOCKEY PUCK
THING|HOLOGRAM
THING|HOME PLATE
THING|HOMEMADE APPLE PIE
THING|HOMEWORK ASSIGNMENT
THING|HOT BUTTERED POPCORN
THING|HOT DOG
THING|HOT FUDGE SUNDAE
THING|HURRICANE
THING|INSURANCE POLICY
THING|IRONING BOARD
THING|JACK-IN- THE-BOX
THING|JACK-O- LANTERN
THING|JAPANESE BEETLE
THING|JELLY DOUGHNUT
THING|JELLYFISH
THING|JIGSAW PUZZLE
THING|JUMP ROPE
THING|JUMPING JACK
THING|KANGAROO
THING|KENTUCKY FRIED CHICKEN
THING|KITCHEN TABLE
THING|KNITTING NEEDLES
THING|KOALA BEAR
THING|LAUNCHING PAD
THING|LAWN MOWER
THING|LEAD PENCIL
THING|LEAKY FAUCET
THING|LEMONADE STAND
THING|LIBERTY BELL
THING|LICENSE PLATE
THING|LICORICE CANDY
THING|LIE- DETECTOR TEST
THING|LIFE PRESERVER
THING|LIGHTNING BUG
THING|LIGHTNING ROD
THING|LOOSE-LEAF NOTEBOOK
THING|LOTTERY TICKET
THING|LOW-CALORIE DIET
THING|LUCKY CHARM
THING|LUNAR ROVER
THING|MACARONI AND CHEESE CASSEROLE
THING|MAGAZINE
THING|MAGNIFYING GLASS
THING|MEXICAN SOMBRERO
THING|MICROWAVE OVEN
THING|MILK OF MAGNESIA
THING|MODEL AIRPLANE
THING|MODEL RAILROAD
THING|MONEY ORDER
THING|MORNING GLORY
THING|MORSE CODE
THING|MOUSETRAP
THING|MOVIE FILM PROJECTOR
THING|MULTIPLE CHOICE QUIZ
THING|MUSTACHE COMB
THING|NATIONAL ANTHEM
THING|NEW YEAR'S RESOLUTION
THING|NUCLEAR SUBMARINE
THING|OCTOPUS
THING|OPTICAL ILLUSION
THING|ORANGE JUICE
THING|ORANGUTAN
THING|OUTBOARD MOTOR
THING|OVERTIME PAY
THING|PAJAMA BOTTOMS
THING|PARACHUTE
THING|PEANUT BUTTER AND JELLY SANDWICH
THING|PEN AND PENCIL SET
THING|PENCIL SHARPENER
THING|PEPPERONI PIZZA
THING|PERMISSION SLIP
THING|PHOTOCOPY MACHINE
THING|PICK-UP TRUCK
THING|PIGGY BANK
THING|PIN CUSHION
THING|PINBALL MACHINE
THING|PINEAPPLE UPSIDE-DOWN CAKE
THING|PING PONG TABLE
THING|PLASTER OF PARIS
THING|PLAY DOH
THING|POCKET CALCULATOR
THING|POISON IVY
THING|POLAR BEAR
THING|POLAROID CAMERA
THING|POPCORN
THING|POTBELLIED STOVE
THING|PRACTICAL JOKE
THING|PRAYING MANTIS
THING|PREPOSITION
THING|PUMPKIN PIE
THING|PUNCTUATION MARK
THING|PUSSY WILLOW
THING|QUARTZ WATCH
THING|QUESTION MARK
THING|QUICKSAND
THING|RAILROAD TIMETABLE
THING|REAR-VIEW MIRROR
THING|REPORT CARD
THING|RICE PUDDING
THING|RINGTOSS
THING|ROCK AND ROLL MUSIC
THING|ROCKING HORSE
THING|ROLLER COASTER
THING|ROMAN NUMERAL
THING|RUBBER BAND
THING|SABER- TOOTHED TIGER
THING|SAINT BERNARD DOG
THING|SALTWATER TAFFY
THING|SCHOOL BUS
THING|SCIENCE EXPERIMENT
THING|SCREWDRIVER
THING|SELF- CLEANING OVEN
THING|SEVEN- LAYER CAKE
THING|SHOCK ABSORBER
THING|SHOULDER HOLSTER
THING|SIX-INCH RULER
THING|SKATEBOARD
THING|SLIDING GLASS DOOR
THING|SNAPPING TURTLE
THING|SPACE SHUTTLE
THING|SPIDER WEB
THING|STATION WAGON
THING|STEAM ENGINE
THING|STEAM SHOVEL
THING|STEPPING- STONE
THING|STEREO SYSTEM
THING|STOMACH ACHE
THING|STRAWBERRY ICE CREAM
THING|SUBMARINE PERISCOPE
THING|SUBWAY TRAIN
THING|SURFBOARD
THING|SWEATSHIRT
THING|SWEET POTATO
THING|SWIMMING POOL
THING|SYNTHESIZER
THING|TABLE OF CONTENTS
THING|TALCUM POWDER
THING|TAPE MEASURE
THING|TEDDY BEAR
THING|TEE SHIRT
THING|TELEPHONE DIRECTORY
THING|TELESCOPE
THING|TELEVISION ANTENNA
THING|TELEVISION COMMERCIAL
THING|TELEVISION SET
THING|TEN-SPEED BICYCLE
THING|TENNIS RACKET
THING|THE ACE OF SPADES
THING|THE DISNEY CHANNEL
THING|THE FREEZING POINT
THING|THE MAYFLOWER
THING|THERMOMETER
THING|THERMOS BOTTLE
THING|THIRD- DEGREE BURN
THING|TOASTED MARSHMALLOW
THING|TOBOGGAN
THING|TOMAHAWK
THING|TOMATO JUICE
THING|TOOTSIE ROLL
THING|TOPIC SENTENCE
THING|TOTEM POLE
THING|TOUCHDOWN
THING|TRAFFIC SIGNAL
THING|TRAVELER'S CHECK
THING|TREASURY BOND
THING|TREE HOUSE
THING|TRICERATOPS
THING|TUNA FISH SANDWICH
THING|TURKEY DRUMSTICK
THING|TWO-WAY MIRROR
THING|TYPEWRITER
THING|UMBRELLA
THING|VACUUM CLEANER
THING|VIDEO CASSETTE RECORDER
THING|WASHING MACHINE
THING|WASTEBASKET
THING|WATCHDOG
THING|WATER FOUNTAIN
THING|WATERBED
THING|WATERMELON
THING|WEDDING RING
THING|WEEPING WILLOW TREE
THING|WHIPPED CREAM CAKE
THING|WHOLE NUMBER
THING|WISDOM TOOTH
THING|WORD PROCESSOR
THING|WRISTWATCH
THING|X-RAY MACHINE
THING|XYLOPHONE
THING|ZIP CODE
FICTIONAL CHARACTER|ABOMINABLE SNOWMAN
FICTIONAL CHARACTER|BEETLE BAILEY
FICTIONAL CHARACTER|BETTY BOOP
FICTIONAL CHARACTER|BUGS BUNNY
FICTIONAL CHARACTER|CAPTAIN HOOK
FICTIONAL CHARACTER|CAPTAIN POWER
FICTIONAL CHARACTER|CASPER THE FRIENDLY GHOST
FICTIONAL CHARACTER|CHARLIE BROWN
FICTIONAL CHARACTER|COOKIE MONSTER
FICTIONAL CHARACTER|COUNT DRACULA
FICTIONAL CHARACTER|DARTH VADER
FICTIONAL CHARACTER|DENNIS THE MENACE
FICTIONAL CHARACTER|DENNIS THE MENACE
FICTIONAL CHARACTER|DONALD DUCK
FICTIONAL CHARACTER|EASTER BUNNY
FICTIONAL CHARACTER|EBENEZER SCROOGE
FICTIONAL CHARACTER|ELMER FUDD
FICTIONAL CHARACTER|FATHER TIME
FICTIONAL CHARACTER|FRED FLINTSTONE
FICTIONAL CHARACTER|GARFIELD
FICTIONAL CHARACTER|HEATHCLIFF
FICTIONAL CHARACTER|HERCULES
FICTIONAL CHARACTER|INDIANA JONES
FICTIONAL CHARACTER|JACK FROST
FICTIONAL CHARACTER|KERMIT THE FROG
FICTIONAL CHARACTER|KING KONG
FICTIONAL CHARACTER|LUKE SKYWALKER
FICTIONAL CHARACTER|MARMADUKE
FICTIONAL CHARACTER|MICKEY MOUSE
FICTIONAL CHARACTER|MISS PIGGY
FICTIONAL CHARACTER|MOTHER GOOSE
FICTIONAL CHARACTER|MR POTATO HEAD
FICTIONAL CHARACTER|OPTIMUS PRIME
FICTIONAL CHARACTER|PAPA SMURF
FICTIONAL CHARACTER|PAUL BUNYAN
FICTIONAL CHARACTER|PERRY MASON
FICTIONAL CHARACTER|PETER RABBIT
FICTIONAL CHARACTER|POPEYE THE SAILOR MAN
FICTIONAL CHARACTER|PORKY PIG
FICTIONAL CHARACTER|PUNKY BREWSTER
FICTIONAL CHARACTER|RAINBOW BRITE
FICTIONAL CHARACTER|ROAD RUNNER
FICTIONAL CHARACTER|ROBIN HOOD
FICTIONAL CHARACTER|RONALD MCDONALD
FICTIONAL CHARACTER|SANTA CLAUS
FICTIONAL CHARACTER|SHERLOCK HOLMES
FICTIONAL CHARACTER|SMOKEY THE BEAR
FICTIONAL CHARACTER|SNOW WHITE
FICTIONAL CHARACTER|SPEEDY GONZALEZ
FICTIONAL CHARACTER|SPIDERMAN
FICTIONAL CHARACTER|STRAWBERRY SHORTCAKE
FICTIONAL CHARACTER|SUPERMAN
FICTIONAL CHARACTER|SYLVESTER THE CAT
FICTIONAL CHARACTER|TARZAN KING OF THE JUNGLE
FICTIONAL CHARACTER|THE INCREDIBLE HULK
FICTIONAL CHARACTER|THE LONE RANGER
FICTIONAL CHARACTER|THE PINK PANTHER
FICTIONAL CHARACTER|TOM SAWYER
FICTIONAL CHARACTER|TONY THE TIGER
FICTIONAL CHARACTER|TOOTH FAIRY
FICTIONAL CHARACTER|WICKED WITCH OF THE EAST
FICTIONAL CHARACTER|WONDER WOMAN
FICTIONAL CHARACTER|WOODY WOODPECKER
FICTIONAL CHARACTER|YOSEMITE SAM
PHRASE|A CHANGE OF PACE
PHRASE|A DIME A DOZEN
PHRASE|A DROP IN THE BUCKET
PHRASE|A FORK IN THE ROAD
PHRASE|A FROG IN MY THROAT
PHRASE|A HOLE IN ONE
PHRASE|A WEALTH OF INFORMATION
PHRASE|ABOUT FACE
PHRASE|ADAM'S APPLE
PHRASE|ALL ABOARD
PHRASE|AROUND THE CLOCK
PHRASE|BACK-SEAT DRIVER
PHRASE|BE MY VALENTINE
PHRASE|BEHIND THE EIGHT BALL
PHRASE|BET YOU CAN'T EAT JUST ONE
PHRASE|BOMBS AWAY
PHRASE|BREAKA PROMISE
PHRASE|BUCKLE UP FOR SAFETY
PHRASE|BURN A HOLE IN ONE'S POCKET
PHRASE|BY TRIAL AND ERROR
PHRASE|CATCH A COLD
PHRASE|CLEAN UP YOUR ROOM
PHRASE|CLOSE CAPTIONED
PHRASE|CROSS AT THE GREEN
PHRASE|DO NOT DISTURB
PHRASE|DON'T COUNT ON IT
PHRASE|DOWN TO EARTH
PHRASE|DRIVE A HARD BARGAIN
PHRASE|E T PHONE HOME
PHRASE|EASY COME EASY GO
PHRASE|ENTER AT YOUR OWN RISK
PHRASE|FINDERS KEEPERS LOSERS WEEPERS
PHRASE|FINGER LICKING GOOD
PHRASE|FIT AS A FIDDLE
PHRASE|FLY OFF THE HANDLE
PHRASE|FOLLOW THE LEADER
PHRASE|FREEZE IN YOUR TRACKS
PHRASE|GENERATION GAP
PHRASE|GET READY GET SET GO
PHRASE|GO FLY A KITE
PHRASE|GOOD GRIEF CHARLIE BROWN
PHRASE|HANG IN THERE
PHRASE|HANG TEN
PHRASE|HAPPY BIRTHDAY
PHRASE|HAPPY HANUKKAH
PHRASE|HAPPY NEW YEAR
PHRASE|HAVE A NICE DAY
PHRASE|HAVE A SCREW LOOSE
PHRASE|HAVE THE LAST LAUGH
PHRASE|HE'S PULLING YOUR LEG
PHRASE|HEADS OR TAILS
PHRASE|HEIGH-HO HEIGH-HO
PHRASE|HELP WANTED
PHRASE|HIDE AND SEEK
PHRASE|HOCUS- POCUS
PHRASE|HONESTY IS THE BEST POLICY
PHRASE|HOW'S IT GOING
PHRASE|HUGS AND KISSES
PHRASE|I CANNOT TELL A LIE
PHRASE|I HEARD IT THROUGH THE GRAPEVINE
PHRASE|I LOVE YOU
PHRASE|I'LL DO IT TOMORROW
PHRASE|IN THE DOGHOUSE
PHRASE|IN THE LAP OF LUXURY
PHRASE|IT WAS A CLOSE CALL
PHRASE|IT WAS AN ACCIDENT
PHRASE|IT'S A SMALL WORLD
PHRASE|IT'S RAINING CATS AND DOGS
PHRASE|KEEP A STIFF UPPER LIP
PHRASE|KEEP ONE'S PROMISE
PHRASE|LET YOUR HAIR DOWN
PHRASE|LIKE A FISH OUT OF WATER
PHRASE|LOOK IT UP
PHRASE|LOSE ONE'S TEMPER
PHRASE|MAKE AN EXCEPTION
PHRASE|MAKE UP YOUR MIND
PHRASE|MAY THE FORCE BE WITH YOU
PHRASE|MEDAL OF HONOR
PHRASE|MEET FACE TO FACE
PHRASE|MERRY CHRISTMAS
PHRASE|MY TWO CENTS WORTH
PHRASE|NO PROBLEM
PHRASE|NO TRESPASSING
PHRASE|NO VACANCY
PHRASE|NUTTY AS A FRUITCAKE
PHRASE|ODDS AND EVENS
PHRASE|ON TOP OF THE WORLD
PHRASE|ONLY YOU CAN PREVENT FOREST FIRES
PHRASE|OUT OF BREATH
PHRASE|PIG OUT
PHRASE|PITCH A TENT
PHRASE|PLAY FAIR AND SQUARE
PHRASE|PLAY THE PIANO
PHRASE|PUT THE FROSTING ON THE CAKE
PHRASE|RACK YOUR BRAINS
PHRASE|SET A GOOD EXAMPLE
PHRASE|SHAME ON YOU
PHRASE|SIMON SAYS
PHRASE|SNAP CRACKLE AND POP
PHRASE|SO FAR SO GOOD
PHRASE|STAND ON ONE'S OWN TWO FEET
PHRASE|STICK-IN- THE-MUD
PHRASE|STOP DROP AND ROLL
PHRASE|STOP LOOK AND LISTEN
PHRASE|STRAIGHT FROM THE HORSE'S MOUTH
PHRASE|SURF'S UP
PHRASE|TAKE A COFFEE BREAK
PHRASE|THE EYE OF THE HURRICANE
PHRASE|THERE'S NOTHING TO IT
PHRASE|THINK IT OVER
PHRASE|THIS IS NO LAUGHING MATTER
PHRASE|THROW ONE'S WEIGHT AROUND
PHRASE|TO THE ENDS OF THE EARTH
PHRASE|TOPSY-TURVY
PHRASE|TRICK OR TREAT
PHRASE|TURN GREEN WITH ENVY
PHRASE|WEAR A LONG FACE
PHRASE|WHAT TIME IS IT
PHRASE|WHAT YOU SEE IS WHAT YOU GET
PHRASE|WHAT'S UP DOC
PHRASE|WITH LIBERTY AND JUSTICE FOR ALL
PHRASE|YOU SHOULD KNOW BETTER
THINGS|ANIMAL CRACKERS
THINGS|BACON AND EGGS
THINGS|BASEBALL CARDS
THINGS|BOW AND ARROW
THINGS|BREAD AND BUTTER
THINGS|BUNK BEDS
THINGS|CANDY CANES
THINGS|CHEERIOS
THINGS|CHICKEN AND DUMPLINGS
THINGS|CHICKEN MCNUGGETS
THINGS|CHINESE CHECKERS
THINGS|CHOCOLATE CHIP COOKIES
THINGS|COMPUTER GAMES
THINGS|CORN FLAKES
THINGS|CREAM AND SUGAR
THINGS|DINOSAURS
THINGS|EUCALYPTUS LEAVES
THINGS|FALSE TEETH
THINGS|FRENCH FRIES
THINGS|GARBAGE PAIL KIDS CARDS
THINGS|GIRL SCOUT COOKIES
THINGS|GOLF CLUBS
THINGS|HAMMER AND NAILS
THINGS|HANDCUFFS
THINGS|HORSE AND BUGGY
THINGS|HORSESHOES
THINGS|HOT WHEELS
THINGS|JELLYBEANS
THINGS|KLEENEX TISSUES
THINGS|LOBSTER TAILS
THINGS|MILK AND COOKIES
THINGS|NINA PINTA AND SANTA MARIA
THINGS|PENCILS
THINGS|PEPPERMINT LIFE SAVERS
THINGS|PISTACHIO NUTS
THINGS|PLAYING CARDS
THINGS|POLO SHIRTS
THINGS|PORK AND BEANS
THINGS|POTATO CHIPS
THINGS|QUOTATION MARKS
THINGS|RED BLOOD CELLS
THINGS|REMOTE CONTROL CARS
THINGS|ROMAN CANDLES
THINGS|SALT AND PEPPER
THINGS|SALTED PRETZELS
THINGS|SALTINE CRACKERS
THINGS|SCRAMBLED EGGS
THINGS|SMOKE SIGNALS
THINGS|SNOWBALLS
THINGS|SPAGHETTI AND MEATBALLS
THINGS|SPRING AND MATTRESS
THINGS|SUNFLOWER SEEDS
THINGS|SUNGLASSES
THINGS|TROPICAL FISH
THINGS|VENETIAN BLINDS
THINGS|VIDEO GAMES
THINGS|VITAMIN PILLS
THINGS|WAFFLES AND ICE CREAM
TITLE|A BOY NAMED CHARLIE BROWN
TITLE|ALICE IN WONDERLAND
TITLE|AN AMERICAN TAIL
TITLE|BACK TO THE FUTURE
TITLE|BEAUTY AND THE BEAST
TITLE|CINDERELLA
TITLE|CROCODILE DUNDEE
TITLE|DR JEKYLL AND MR HYDE
TITLE|FAMILY TIES
TITLE|FRAGGLE ROCK
TITLE|FROM RUSSIA WITH LOVE
TITLE|FROSTY THE SNOWMAN
TITLE|GOD BLESS AMERICA
TITLE|GREMLINS
TITLE|GUINNESS BOOK OF WORLD RECORDS
TITLE|GULLIVER'S TRAVELS
TITLE|HANSEL AND GRETEL
TITLE|HEAD OF THE CLASS
TITLE|HEY THERE IT'S YOGI BEAR
TITLE|HICKORY DICKORY DOCK
TITLE|HOT CROSS BUNS
TITLE|HOWARD THE DUCK
TITLE|KNIGHT RIDER
TITLE|LADY AND THE TRAMP
TITLE|LITTLE TOMMY TUCKER
TITLE|MARY MARY QUITE CONTRARY
TITLE|MARY POPPINS
TITLE|MASTERS OF THE UNIVERSE
TITLE|MONOPOLY
TITLE|MURDER SHE WROTE
TITLE|MY THREE SONS
TITLE|OLD MOTHER HUBBARD
TITLE|OVER THE TOP
TITLE|PERFECT STRANGERS
TITLE|PETER PETER PUMPKIN EATER
TITLE|PIN THE TAIL ON THE DONKEY
TITLE|PINOCCHIO
TITLE|PLANET OF THE APES
TITLE|POP GOES THE WEASEL
TITLE|RAMBO
TITLE|RETURN OF THE JEDI
TITLE|RING AROUND THE ROSIE
TITLE|RIP VAN WINKLE
TITLE|ROBINSON CRUSOE
TITLE|RUDOLPH THE RED-NOSED REINDEER
TITLE|SCRABBLE
TITLE|SESAME STREET
TITLE|SLEEPING BEAUTY
TITLE|SUPER MARIO BROTHERS
TITLE|THE BAD NEWS BEARS
TITLE|THE BRADY BUNCH
TITLE|THE EMPEROR'S NEW CLOTHES
TITLE|THE FACTS OF LIFE
TITLE|THE FARMER IN THE DELL
TITLE|THE GOONIES
TITLE|THE KARATE KID
TITLE|THE MUPPETS TAKE MANHATTAN
TITLE|THE NUTCRACKER SUITE
TITLE|THE SOUND OF MUSIC
TITLE|THE STAR- SPANGLED BANNER
TITLE|THE THREE LITTLE PIGS
TITLE|THE WIZARD OF OZ
TITLE|TREASURE ISLAND
TITLE|TWINKLE TWINKLE LITTLE STAR
TITLE|WHEEL OF FORTUNE
TITLE|WHO KILLED COCK ROBIN
TITLE|WINNIE THE POOH
TITLE|WYNKEN BLYNKEN AND NOD
TITLE|YANKEE DOODLE DANDY
PEOPLE|ALGONQUIN INDIANS
PEOPLE|BOARD OF HEALTH
PEOPLE|BOY SCOUTS OF AMERICA
PEOPLE|BRIDE AND GROOM
PEOPLE|COAST GUARD
PEOPLE|CONTINENTAL CONGRESS
PEOPLE|CURLY MOE AND LARRY
PEOPLE|DURAN DURAN
PEOPLE|FAMILY CIRCLE
PEOPLE|IDENTICAL TWINS
PEOPLE|LITTLE LEAGUE BASEBALL TEAM
PEOPLE|MIAMI DOLPHINS
PEOPLE|MIDGET FOOTBALL TEAM
PEOPLE|MOTLEY CRUE
PEOPLE|NATIONAL FOOTBALL LEAGUE
PEOPLE|NATIONAL GUARD
PEOPLE|NEW YORK METS
PEOPLE|QUINTUPLETS
PEOPLE|SHAWNEE INDIANS
PEOPLE|SIAMESE TWINS
PEOPLE|SWAT TEAM
PEOPLE|SYMPHONY ORCHESTRA
PEOPLE|THE ALLMAN BROTHERS
PEOPLE|THE BEACH BOYS
PEOPLE|THE BEATLES
PEOPLE|THE FAT BOYS
PEOPLE|THE THREE WISE MEN
PEOPLE|WASHINGTON REDSKINS
PEOPLE|WORLD WRESTLING FEDERATION
EVENT|ASH WEDNESDAY
EVENT|ASSEMBLY PROGRAM
EVENT|BAR MITZVAH
EVENT|BIRTHDAY PARTY
EVENT|BREAK DANCING CONTEST
EVENT|CHRISTENING
EVENT|CHRISTMAS EVE
EVENT|CHRISTMAS VACATION
EVENT|CIVIL WAR
EVENT|COLLEGE GRADUATION
EVENT|COLUMBUS DAY
EVENT|COURT MARTIAL
EVENT|DRESS REHEARSAL
EVENT|EARTHQUAKE
EVENT|EASTER EGG HUNT
EVENT|EASTER SUNDAY
EVENT|FIRE PREVENTION WEEK
EVENT|FIRST ANNIVERSARY
EVENT|FOURTH OF JULY
EVENT|GARAGE SALE
EVENT|HALLOWEEN
EVENT|HIGH SCHOOL PROM
EVENT|HOLY COMMUNION
EVENT|LEAP YEAR
EVENT|MASQUERADE PARTY
EVENT|MEMORIAL DAY
EVENT|MISS AMERICA PAGEANT
EVENT|MONDAY NIGHT FOOTBALL
EVENT|MOTHER'S DAY
EVENT|NIGHT OF THE FULL MOON
EVENT|OPEN- HEART SURGERY
EVENT|ORANGE BOWL PARADE
EVENT|PAJAMA PARTY
EVENT|PRESIDENTS DAY
EVENT|ROCK CONCERT
EVENT|SHOOTING STAR
EVENT|SOCCER GAME
EVENT|SOLAR ECLIPSE
EVENT|SPACE WALK
EVENT|SPRING BREAK
EVENT|SUMMER VACATION
EVENT|SUPER BOWL GAME
EVENT|SURPRISE PARTY
EVENT|SWEET SIXTEEN PARTY
EVENT|THE FIRST DAY OF SCHOOL
EVENT|THE WORLD SERIES
EVENT|THREE-RING CIRCUS
EVENT|TRACK AND FIELD DAY
EVENT|TREASURE HUNT
EVENT|VALENTINE'S DAY
EVENT|VETERANS DAY
EVENT|WEDDING CEREMONY
EVENT|WORLD CUP SOCCER MATCH
FICTIONAL CHARACTERS|BATMAN AND ROBIN
FICTIONAL CHARACTERS|BERENSTAIN BEARS
FICTIONAL CHARACTERS|BERT AND ERNIE
FICTIONAL CHARACTERS|CARE BEARS
FICTIONAL CHARACTERS|GUMBY AND POKEY
FICTIONAL CHARACTERS|KNIGHTS OF THE ROUND TABLE
FICTIONAL CHARACTERS|RAGGEDY ANN AND ANDY
FICTIONAL CHARACTERS|SNOOPY AND WOODSTOCK
FICTIONAL CHARACTERS|THE A TEAM
FICTIONAL CHARACTERS|THE CALIFORNIA RAISINS
FICTIONAL CHARACTERS|THE CHIPMUNKS
FICTIONAL CHARACTERS|THE FLINTSTONE KIDS
FICTIONAL CHARACTERS|THE LITTLE RASCALS
FICTIONAL CHARACTERS|THE WUZZLES
FICTIONAL CHARACTERS|TOM AND JERRY
`;

let wofFamilyAnswers02 = 
`
PLACE|ALLIGATOR ALLEY
PLACE|AMAZON JUNGLE
PLACE|ANTIOCH
PLACE|APPLE ORCHARD
PLACE|ART GALLERY
PLACE|AUTO BODY SHOP
PLACE|BADEN BADEN WEST GERMANY
PLACE|BATON ROUGE LOUISIANA
PLACE|CARTHAGE
PLACE|CENTRAL PARK
PLACE|CHERNOBYL
PLACE|CHESAPEAKE BAY
PLACE|CHILD CARE CENTER
PLACE|CLUB MED
PLACE|COLLEGE CAMPUS
PLACE|DAIRY FARM
PLACE|DEAD SEA
PLACE|DEATH VALLEY
PLACE|DES MOINES IOWA
PLACE|DRESSING ROOM
PLACE|DUBROVNIK YUGOSLAVIA
PLACE|DUDE RANCH
PLACE|EUREKA CALIFORNIA
PLACE|FARMERS MARKET
PLACE|FIJI ISLANDS
PLACE|FRANKFURT GERMANY
PLACE|FRATERNITY HOUSE
PLACE|FRONT PORCH
PLACE|FUNERAL HOME
PLACE|GOBI DESERT
PLACE|GRAND FORKS NORTH DAKOTA
PLACE|GRAND TETON NATIONAL PARK
PLACE|GREENWICH CONNECTICUT
PLACE|GUAYAQUIL ECUADOR
PLACE|HEATHROW AIRPORT
PLACE|HOME TEAM DUGOUT
PLACE|HOSPITAL RECOVERY ROOM
PLACE|INFANT NURSERY
PLACE|JEFFERSON CITY MISSOURI
PLACE|JERUSALEM
PLACE|JOHNSON SPACE CENTER
PLACE|KALAMAZOO MICHIGAN
PLACE|KOWLOON
PLACE|KUALA LUMPUR
PLACE|LA BREA TAR PITS
PLACE|LIBRARY OF CONGRESS
PLACE|LIBRARY REFERENCE ROOM
PLACE|LINCOLN MEMORIAL
PLACE|LONG ISLAND SOUND
PLACE|MAPLE LEAF GARDEN
PLACE|MATERNITY WARD
PLACE|MAUI HAWAII
PLACE|MECCA
PLACE|MEDICAL SCHOOL
PLACE|MINIATURE GOLF COURSE
PLACE|MINNEAPOLIS MINNESOTA
PLACE|MOBILE HOME PARK
PLACE|MONTERREY MEXICO
PLACE|MOUNT FUJI
PLACE|MOUNT RAINIER NATIONAL PARK
PLACE|MOVIE STUDIO BACK LOT
PLACE|MYKONOS
PLACE|NON-SMOKING SECTION
PLACE|NOTRE DAME CATHEDRAL
PLACE|NURSING HOME
PLACE|OCALA NATIONAL FOREST
PLACE|OPERATING ROOM
PLACE|ORCHESTRA PIT
PLACE|PAN- AMERICAN HIGHWAY
PLACE|PARADISE ISLAND
PLACE|PEOPLE'S REPUBLIC OF CHINA
PLACE|RACKETBALL COURT
PLACE|RALEIGH NORTH CAROLINA
PLACE|RED SQUARE
PLACE|REFRESHMENT STAND
PLACE|SAINT ANDREWS GOLF COURSE
PLACE|SAINT AUGUSTINE FLORIDA
PLACE|SAN JOSE COSTA RICA
PLACE|SANTA FE TRAIL
PLACE|SAN DIEGO ZOO
PLACE|SCHENECTADY NEW YORK
PLACE|SCHOOL CAFETERIA
PLACE|SCHOOL GYMNASIUM
PLACE|SHEA STADIUM
PLACE|SHOPPING CENTER PARKING LOT
PLACE|SIOUX FALLS SOUTH DAKOTA
PLACE|SPORTS COMPLEX
PLACE|STADIUM BLEACHERS
PLACE|STADIUM PRESSBOX
PLACE|STRAIT OF BOSPORUS
PLACE|STRATFORD ON AVON
PLACE|SUBWAY STATION
PLACE|SWEETWATER TEXAS
PLACE|SYRIA
PLACE|TEXARKANA
PLACE|THE FORBIDDEN CITY
PLACE|THE GALAPAGOS ISLANDS
PLACE|TIEN AN MEN SQUARE
PLACE|TOY DEPARTMENT
PLACE|VANCOUVER BRITISH COLUMBIA
PLACE|VENICE ITALY
PLACE|WALLA WALLA WASHINGTON
PLACE|WILMINGTON DELAWARE
PLACE|WINNIPEG MANITOBA CANADA
PLACE|YANGTZE RIVER
PLACE|YUKON NORTHWEST TERRITORY
PERSON|AEROBICS INSTRUCTOR
PERSON|ALEXANDER DUMAS
PERSON|ALEXANDER HAIG
PERSON|AN EQUAL- OPPORTUNITY EMPLOYER
PERSON|ANDREW JOHNSON
PERSON|ANDRE AGASSI
PERSON|ANIMAL TRAINER
PERSON|ARISTOCRAT
PERSON|ARMCHAIR QUARTERBACK
PERSON|ARMY BRAT
PERSON|ARSENIO HALL
PERSON|ASTRONOMER
PERSON|BENJAMIN HARRISON
PERSON|BLUES SINGER
PERSON|BOXING REFEREE
PERSON|BROOKS ROBINSON
PERSON|CAPTAIN JAMES COOK
PERSON|CARL YASTRZEMSKI
PERSON|CATHERINE DE MEDICI
PERSON|CATTLE RANCHER
PERSON|CHARLEMAGNE
PERSON|CHRISTOPHER COLUMBUS
PERSON|CONGRESSMAN
PERSON|CORBIN BERNSEN
PERSON|CRUSADER
PERSON|DANIEL WEBSTER
PERSON|DAVID GLASGOW FARRAGUT
PERSON|DEER HUNTER
PERSON|DENTAL SURGEON
PERSON|DIAN FOSSEY
PERSON|DONALD TRUMP
PERSON|DRESSMAKER
PERSON|DRUG COUNSELOR
PERSON|DR RUTH WESTHEIMER
PERSON|EGYPTIAN PHARAOH
PERSON|ELIAS HOWE
PERSON|ELIZABETH DOLE
PERSON|EL GRECO
PERSON|EMPEROR CLAUDIUS
PERSON|ERIC THE RED
PERSON|EURIPIDES
PERSON|EXPLORER
PERSON|FIRE INSPECTOR
PERSON|FRANKLIN DELANO ROOSEVELT
PERSON|GARRISON KEILLOR
PERSON|GENGHIS KHAN
PERSON|GEORGE HERMAN BABE RUTH
PERSON|GEORGE WASHINGTON
PERSON|GIAN CARLO MENOTTI
PERSON|GOSSIP COLUMNIST
PERSON|GREG LOUGANIS
PERSON|GROVER CLEVELAND ALEXANDER
PERSON|GUITAR PLAYER
PERSON|HANNIBAL
PERSON|HARRIET BEECHER STOWE
PERSON|HELEN OF TROY
PERSON|HENNY YOUNGMAN
PERSON|HENRY DAVID THOREAU
PERSON|HERSCHEL WALKER
PERSON|HIGH SCHOOL CHEERLEADER
PERSON|HISTORIAN
PERSON|HISTORY TEACHER
PERSON|HOME PLATE UMPIRE
PERSON|HOME RUN HITTER
PERSON|HONUS WAGNER
PERSON|HOTEL BUSBOY
PERSON|HUMORIST
PERSON|HYPNOTIST
PERSON|IVAN THE GREAT
PERSON|IVAN THE TERRIBLE
PERSON|JACQUES COUSTEAU
PERSON|JAMESA GARFIELD
PERSON|JAMES BUCHANAN
PERSON|JAMES WHISTLER
PERSON|JAZZ MUSICIAN
PERSON|JET SKIER
PERSON|JOAN OF ARC
PERSON|JOCKEY
PERSON|JOHN ADAMS
PERSON|JOHN PAUL JONES
PERSON|JOHN TYLER
PERSON|JON BON JOVI
PERSON|KONRAD ADENAUER
PERSON|KUBLAI KHAN
PERSON|LEONARDO DA VINCI
PERSON|LIGHTHOUSE KEEPER
PERSON|LUMBERJACK
PERSON|MAJOR LEAGUE BASEBALL PLAYER
PERSON|MANAGING EDITOR
PERSON|MANUEL NORIEGA
PERSON|MARATHON RUNNER
PERSON|MARIA VON TRAPP
PERSON|MARINE DRILL SERGEANT
PERSON|MARINE SERGEANT
PERSON|MARIO ANDRETTI
PERSON|MARTIN LUTHER
PERSON|MARY QUEEN OF SCOTS
PERSON|MARY TODD LINCOLN
PERSON|MATH TUTOR
PERSON|MATS WILANDER
PERSON|MAX VON SYDOW
PERSON|MAYNARD FERGUSON
PERSON|MEADOWLARK LEMON
PERSON|MERCHANT
PERSON|MERIWETHER LEWIS
PERSON|MISSISSIPPI RIVERBOAT GAMBLER
PERSON|MOISHE DAYAN
PERSON|MONDAY MORNING QUARTERBACK
PERSON|MOTORCYCLE COP
PERSON|MUSIC COMPOSER
PERSON|NATHANIEL HAWTHORNE
PERSON|NAVAL OFFICER
PERSON|NAVY ADMIRAL
PERSON|NEWS ANCHORMAN
PERSON|OFFENSIVE LINEMAN
PERSON|OLIVER CROMWELL
PERSON|ONCOLOGIST
PERSON|OPTICIAN
PERSON|OPTOMETRIST
PERSON|ORGAN DONOR
PERSON|PIANO PLAYER
PERSON|PIERRE SALINGER
PERSON|PIONEER
PERSON|PITCHING COACH
PERSON|PLAY BY PLAY ANNOUNCER
PERSON|PLUMBER'S APPRENTICE
PERSON|PRIVATE DETECTIVE
PERSON|PROFESSOR OF PHILOSOPHY
PERSON|PTOLEMY
PERSON|PULITZER PRIZE WINNER
PERSON|PYTHAGORAS
PERSON|QUEEN ISABELLA OF SPAIN
PERSON|QUEEN OF THE NILE
PERSON|RADIOLOGIST
PERSON|RALPH LAUREN
PERSON|ROBERTO CLEMENTE
PERSON|ROBIN GIVENS
PERSON|ROCK AND ROLL SINGER
PERSON|ROGER BACON
PERSON|ROGERS HORNSBY
PERSON|ROGER WILLIAMS
PERSON|ROYAL CANADIAN MOUNTIE
PERSON|ROY CAMPANELLA
PERSON|RUPERT MURDOCH
PERSON|RUTHERFORDB HAYES
PERSON|SACAJAWEA
PERSON|SALMAN RUSHDIE
PERSON|SAMUEL F B MORSE
PERSON|SANDY KOUFAX
PERSON|SANITATION WORKER
PERSON|SAXOPHONE PLAYER
PERSON|SCULPTOR
PERSON|SECRETARY OF STATE
PERSON|SENATE PAGE
PERSON|SHOE SALESMAN
PERSON|SPORTS COMMENTATOR
PERSON|STEPHEN DOUGLAS
PERSON|STEPHEN FOSTER
PERSON|STOOL PIGEON
PERSON|SUNDAY DRIVER
PERSON|TATTLETALE
PERSON|TED KOPPEL
PERSON|THE ARCHBISHOP OF CANTERBURY
PERSON|THIRD BASE COACH
PERSON|TREE SURGEON
PERSON|TUGBOAT CAPTAIN
PERSON|UNDERCOVER POLICEMAN
PERSON|VASCO DA GAMA
PERSON|WALT WHITMAN
PERSON|WASHINGTON IRVING
PERSON|WASHING MACHINE REPAIRMAN
PERSON|WEST POINT CADET
PERSON|WHISTLER'S MOTHER
PERSON|WILBUR WRIGHT
PERSON|WILLIAM CULLEN BRYANT
PERSON|WILLIAM MCKINLEY
PERSON|WILLIAM TECUMSEH SHERMAN
PERSON|WOLFMAN JACK
PERSON|WYNTON MARSALIS
PERSON|YASIR ARAFAT
THING|ADRENALIN
THING|ALCOHOLIC BEVERAGE
THING|ALKALINE BATTERY
THING|ANALOG QUARTZ WATCH
THING|APPLE CORE
THING|APPLE ORCHARD
THING|ARABIAN STALLION
THING|AREA RUG
THING|ASSEMBLY LINE
THING|ATTACHE CASE
THING|A SIX-MONTH C D
THING|A SWORN AFFIDAVIT
THING|BABY POWDER
THING|BATHROOM SINK
THING|BAYONET
THING|BIORHYTHM
THING|BIRTHDAY PRESENT
THING|BIRTH CERTIFICATE
THING|CARROT CAKE
THING|CHARLEY HORSE
THING|COLUMBIAN COFFEE
THING|COMPACT CAR
THING|CONDENSED MILK
THING|COPPERHEAD SNAKE
THING|CORDUROY JACKET
THING|CORMORANT
THING|CORNUCOPIA
THING|CORRECTED COPY
THING|COUNTERFEIT COIN
THING|CRABAPPLE TREE
THING|CRIMINAL LAW
THING|CRITICAL THINKING
THING|CROCKPOT
THING|CROQUET SET
THING|CROWBAR
THING|CUBAN CIGAR
THING|CUBIC ZIRCONIA EARRINGS
THING|CY YOUNG AWARD
THING|DESKTOP COPIER
THING|DIAPER SERVICE
THING|DOCTOR'S SCALE
THING|DRAWER ORGANIZER
THING|ELECTRONIC KEYBOARD
THING|ELECTRONIC SCOREBOARD
THING|EMPEROR MOTH
THING|FACSIMILE MACHINE
THING|FACTORY WARRANTY
THING|FEATURE LENGTH FILM
THING|FISH CROQUETTE
THING|FOLDING STEP STOOL
THING|FOLDING UMBRELLA
THING|FOOL'S GOLD
THING|FROZEN YOGURT
THING|FUNGO BAT
THING|GARBAGE DUMPSTER
THING|GAZEBO
THING|GLAZED DONUT
THING|GOLF CART
THING|GOOSE FEATHER PILLOW
THING|GRANNY SMITH APPLE
THING|HAND GRENADE
THING|HEARING DISORDER
THING|HOME ADDRESS
THING|HOME MORTGAGE
THING|HUMIDIFIER
THING|HURRICANE
THING|HYDROGEN PEROXIDE
THING|HYGROMETER
THING|ICEBERG
THING|ICEBOX
THING|ICHTHYOLOGY
THING|JEWELRY BOX
THING|KEY LIME PIE
THING|LASER BEAM SURGERY
THING|LAWN SPRINKLER
THING|LIBERTY BELL
THING|LIFE INSURANCE POLICY
THING|MATERNITY DRESS
THING|MEDIUM- RANGE MISSILE
THING|MILK CONTAINER
THING|MURIATIC ACID
THING|NOBEL PEACE PRIZE
THING|NUCLEAR REACTOR
THING|OPOSSUM
THING|OPTICAL ILLUSION
THING|ORANGE JUICE
THING|ORDINAL NUMBER
THING|ORGAN BANK
THING|PERSIAN RUG
THING|PHOTO ALBUM
THING|WATER PITCHER
THING|POCKET KNIFE
THING|POISONOUS SNAKE
THING|POLKA- DOT BIKINI
THING|POPCORN POPPER
THING|PRAIRIE DOG
THING|PSEUDONYM
THING|PULSE RATE
THING|QUARTZ ALARM CLOCK
THING|QUICKSAND
THING|RADAR DETECTOR
THING|REFERENCE BOOK
THING|ROAST PORK FRIED RICE
THING|ROSETTA STONE
THING|RUBBING ALCOHOL
THING|RUM FACTORY
THING|SAMOVAR
THING|SANDY BEACH
THING|SAPPHIRE BRACELET
THING|SATELLITE DISH
THING|SATYR
THING|SAUNA BATH
THING|SAVINGS ACCOUNT
THING|SAWDUST
THING|SAWHORSE
THING|SAXOPHONE
THING|SHOESTRING CATCH
THING|SLEEPING BAG
THING|SOLAR- POWERED CALCULATOR
THING|SOMERSAULT
THING|STEAK SAUCE
THING|STEALTH BOMBER
THING|STEAM- SPRAY- DRY IRON
THING|SWIVEL CHAIR
THING|SWORD SCABBARD
THING|TACKLE BOX
THING|THE OTTOMAN EMPIRE
THING|THE SPHINX
THING|TOUCHDOWN RUN
THING|TOW TRUCK
THING|TRACK HURDLE
THING|TWIST-OFF CAP
THING|UNDERWATER CAMERA
THING|UPRIGHT FREEZER
THING|VACUUM BOTTLE
THING|VAMPIRE BAT
THING|VAULTING HORSE
THING|VISITING TEAM DUGOUT
THING|VOGUE MAGAZINE
THING|WESTERN OMELET
THING|WIDE-ANGLE BINOCULARS
FICTIONAL CHARACTER|ARCHIE BUNKER
FICTIONAL CHARACTER|B L STRYKER
FICTIONAL CHARACTER|BABAR THE ELEPHANT
FICTIONAL CHARACTER|BARNABY JONES
FICTIONAL CHARACTER|BARNEY MILLER
FICTIONAL CHARACTER|BECKY THATCHER
FICTIONAL CHARACTER|BOSTON BLACKIE
FICTIONAL CHARACTER|BUCK ROGERS
FICTIONAL CHARACTER|CALAMITY JANE
FICTIONAL CHARACTER|CAPTAIN KANGAROO
FICTIONAL CHARACTER|CLUBBER LANG
FICTIONAL CHARACTER|DADDY WARBUCKS
FICTIONAL CHARACTER|DAISY MILLER
FICTIONAL CHARACTER|DOCTOR KILDARE
FICTIONAL CHARACTER|DAGWOOD BUMSTEAD
FICTIONAL CHARACTER|DON QUIXOTE
FICTIONAL CHARACTER|ELIZA DOOLITTLE
FICTIONAL CHARACTER|FLASH GORDON
FICTIONAL CHARACTER|FLETCHER CHRISTIAN
FICTIONAL CHARACTER|FOGHORN LEGHORN
FICTIONAL CHARACTER|HAGAR THE HORRIBLE
FICTIONAL CHARACTER|HOPALONG CASSIDY
FICTIONAL CHARACTER|INSPECTOR GADGET
FICTIONAL CHARACTER|INSPECTOR JACQUES CLOUSEAU
FICTIONAL CHARACTER|JACOB MARLEY
FICTIONAL CHARACTER|JEAN VALJEAN
FICTIONAL CHARACTER|JOE PALOOKA
FICTIONAL CHARACTER|JOE THE BARTENDER
FICTIONAL CHARACTER|LEX LUTHOR
FICTIONAL CHARACTER|LITTLE ORPHAN ANNIE
FICTIONAL CHARACTER|LUCY RICARDO
FICTIONAL CHARACTER|MANDRAKE THE MAGICIAN
FICTIONAL CHARACTER|MARCUS WELBY
FICTIONAL CHARACTER|MARMADUKE
FICTIONAL CHARACTER|MISS JANE MARPLE
FICTIONAL CHARACTER|MISS MONEYPENNY
FICTIONAL CHARACTER|MR BELVEDERE
FICTIONAL CHARACTER|OLD KING COLE
FICTIONAL CHARACTER|PERCY DOVETONSILS
FICTIONAL CHARACTER|POSEIDON
FICTIONAL CHARACTER|PRINCE VALIANT
FICTIONAL CHARACTER|PROFESSOR HENRY HIGGINS
FICTIONAL CHARACTER|PROFESSOR MORIARTY
FICTIONAL CHARACTER|PUNKY BREWSTER
FICTIONAL CHARACTER|QUASIMODO
FICTIONAL CHARACTER|RALPH KRAMDEN
FICTIONAL CHARACTER|REMINGTON STEELE
FICTIONAL CHARACTER|ROCKY BALBOA
FICTIONAL CHARACTER|ROGER RABBIT
FICTIONAL CHARACTER|SERGEANT JOE FRIDAY
FICTIONAL CHARACTER|SLAP MAXWELL
FICTIONAL CHARACTER|SUZIE WONG
FICTIONAL CHARACTER|THE GRINCH
FICTIONAL CHARACTER|THE JOLLY GREEN GIANT
FICTIONAL CHARACTER|THE LONE RANGER
FICTIONAL CHARACTER|TRAPPER JOHN
FICTIONAL CHARACTER|TUGBOAT ANNIE
PHRASE|A BLAST FROM THE PAST
PHRASE|A BREATH OF FRESH AIR
PHRASE|A CHEATER NEVER WINS
PHRASE|A CHIP OFF THE OLD BLOCK
PHRASE|A CLEAN BILL OF HEALTH
PHRASE|A COWARD DIES A THOUSAND TIMES
PHRASE|A DIRTY LOW-DOWN TRICK
PHRASE|A LARGER THAN LIFE ROLE
PHRASE|A LONG BOMB FOR A TOUCHDOWN
PHRASE|A LUCKY DAY
PHRASE|A LUST FOR LIFE
PHRASE|A PENNY SAVED IS A PENNY EARNED
PHRASE|A SNAKE IN THE GRASS
PHRASE|A STANDING ROOM ONLY AUDIENCE
PHRASE|A TRIED AND TRUE METHOD
PHRASE|A WASTE OF TIME AND ENERGY
PHRASE|A WATERED- DOWN VERSION
PHRASE|ADVANCE AND BE RECOGNIZED
PHRASE|ADVICE TO THE LOVELORN
PHRASE|ALL WORK GUARANTEED
PHRASE|AN ACCIDENT WAITING TO HAPPEN
PHRASE|SITTING ON TOP OF THE WORLD
PHRASE|A DEATH- DEFYING STUNT
PHRASE|A GENTLEMAN'S AGREEMENT
PHRASE|A HOMETOWN CROWD
PHRASE|A SNEAKING SUSPICION
PHRASE|A SYMPATHETIC EAR
PHRASE|A TOURNAMENT OF CHAMPIONS
PHRASE|BACKFIELD IN MOTION
PHRASE|BAPTISM UNDER FIRE
PHRASE|BASEBALL RHUBARB
PHRASE|BEAUTY IS IN THE EYE OF THE BEHOLDER
PHRASE|BEAUTY IS SKIN DEEP
PHRASE|BEING LED DOWN THE GARDEN PATH
PHRASE|BLIND AS A BAT
PHRASE|BLONDES HAVE MORE FUN
PHRASE|BROTHER CAN YOU SPARE A DIME
PHRASE|BUY THREE AND GET ONE FREE
PHRASE|CAT GOT YOUR TONGUE
PHRASE|CLEAN UP AFTER YOURSELF
PHRASE|CLEAN AS A WHISTLE
PHRASE|COLD HARD CASH
PHRASE|COME BACK TO REALITY
PHRASE|COURT IS ADJOURNED
PHRASE|CRYING CROCODILE TEARS
PHRASE|DON'T BET YOUR LIFE ON IT
PHRASE|DON'T CRY OVER SPILT MILK
PHRASE|DON'T MAKE A MONKEY OUT OF ME
PHRASE|DOUBLE YOUR PLEASURE
PHRASE|DOWN AND OUT
PHRASE|DOWN FOR THE COUNT
PHRASE|DOWN IN THE MOUTH
PHRASE|DOWN IN THE DUMPS
PHRASE|DRESS FOR SUCCESS
PHRASE|EATING ON THE RUN
PHRASE|FAMOUS LAST WORDS
PHRASE|FIGHT FIRE WITH FIRE
PHRASE|FIRST AND GOAL TO GO
PHRASE|FLOATING A LOAN
PHRASE|FOOTLOOSE AND FANCY FREE
PHRASE|FOREVER YOUNG IN HEART
PHRASE|FOR BETTER OR FOR WORSE
PHRASE|FOURTH DOWN AND INCHES
PHRASE|GETTING AHEAD IN THE WORLD
PHRASE|GETTING BOGGED DOWN
PHRASE|GETTING PAID BACK IN SPADES
PHRASE|GIVE ME YOUR ATTENTION PLEASE
PHRASE|GO HOME AND SLEEP ON IT
PHRASE|GO OUT IN A BLAZE OF GLORY
PHRASE|GO WITH THE FLOW
PHRASE|GOING BUST
PHRASE|GOING OUT OF BUSINESS SALE
PHRASE|GRABBING A BITE TO EAT
PHRASE|GROUNDS FOR DIVORCE
PHRASE|HANG IN THERE
PHRASE|HE WHO LAUGHS LAST LAUGHS BEST
PHRASE|HEAVEN HELP US
PHRASE|HOME IS WHERE THE HEART IS
PHRASE|I CANNOT TELL A LIE
PHRASE|I TOLD YOU SO
PHRASE|INTO EVERY LIFE SOME RAIN MUST FALL
PHRASE|IN A STATE OF PANIC
PHRASE|IN OVER MY HEAD
PHRASE|IT SENT CHILLS DOWN MY SPINE
PHRASE|IT'S A PLEASURE TO KNOW YOU
PHRASE|IT'S A LIVING
PHRASE|I'M READY FOR ANYTHING
PHRASE|I'VE GOT GOOD NEWS AND BAD NEWS
PHRASE|JUST TAKE IT NICE AND EASY
PHRASE|KEEP YOUR EYES PEELED
PHRASE|KNOCK ON WOOD
PHRASE|LAST BUT NOT LEAST
PHRASE|LEARN FROM YOUR MISTAKES
PHRASE|LEARN TO PLAY THE GAME
PHRASE|LET'S GO METS
PHRASE|LIVE AND LET LIVE
PHRASE|LIVING BEYOND YOUR MEANS
PHRASE|MARRYING ON THE REBOUND
PHRASE|MEALS ON WHEELS
PHRASE|MONEY IS THE ROOT OF ALL EVIL
PHRASE|MONEY CAN'T BUY HAPPINESS
PHRASE|NECESSITY IS THE MOTHER OF INVENTION
PHRASE|NEVER A DULL MOMENT
PHRASE|NEVER LOOK BACK
PHRASE|NICE GUYS FINISH LAST
PHRASE|NO PLACE TO GO BUT UP
PHRASE|NOT WORTH A PLUG NICKEL
PHRASE|NOTHING VENTURED NOTHING GAINED
PHRASE|OLD ENOUGH TO KNOW BETTER
PHRASE|ONE OF LIFE'S LITTLE BLESSINGS
PHRASE|ONE PICTURE IS WORTH A THOUSAND WORDS
PHRASE|ONLY TIME WILL TELL
PHRASE|OPEN DOOR TRADE POLICY
PHRASE|OPPORTUNITY KNOCKS
PHRASE|ORDEAL BY FIRE
PHRASE|ORDER IN THE COURT
PHRASE|OVERCOMING ADVERSITY
PHRASE|PASS BY THE SKIN OF YOUR TEETH
PHRASE|PASS WITH FLYING COLORS
PHRASE|PAY IN ADVANCE
PHRASE|PHONY AS A TWO-DOLLAR BILL
PHRASE|PLAYING IT BY EAR
PHRASE|PLAYING POSSUM
PHRASE|PLAYING THE DEVIL'S ADVOCATE
PHRASE|POSITIVE FEEDBACK
PHRASE|PUT UP OR SHUT UP
PHRASE|PUTTING YOUR CARDS ON THE TABLE
PHRASE|READY WILLING AND ABLE
PHRASE|ROTTEN TO THE CORE
PHRASE|RUNNING FOR COVER
PHRASE|RUNNING ON EMPTY
PHRASE|SEALED WITH A KISS
PHRASE|SEVENTH- INNING STRETCH
PHRASE|SICK AS A DOG
PHRASE|SOME FOOD FOR THOUGHT
PHRASE|SOMETHING SMELLS FISHY HERE
PHRASE|STAND UP AND BE COUNTED
PHRASE|STAND UP FOR YOUR RIGHTS
PHRASE|STAND AT ATTENTION
PHRASE|STAND BY YOUR MAN
PHRASE|STARTING FROM SCRATCH
PHRASE|START WITH A CLEAN SLATE
PHRASE|STILL WATERS RUN DEEP
PHRASE|STUCK IN A RUT
PHRASE|SURVIVAL OF THE FITTEST
PHRASE|TAKE IT ONE DAY AT A TIME
PHRASE|TAKE A DEEP BREATH
PHRASE|TALKING THROUGH YOUR HAT
PHRASE|TELL IT TO THE MARINES
PHRASE|THAT WASA CLOSE CALL
PHRASE|THAT'S SO FUNNY I FORGOT TO LAUGH
PHRASE|THAT'S A TALL ORDER
PHRASE|THAT'S MUSIC TO MY EARS
PHRASE|THE AGONY OF DEFEAT
PHRASE|THE APPLE OF HIS EYE
PHRASE|THE BRAVE ONLY DIE ONCE
PHRASE|THE CHECK IS IN THE MAIL
PHRASE|THE END JUSTIFIES THE MEANS
PHRASE|THE FLESH IS WEAK
PHRASE|THE STAR OF THE SHOW
PHRASE|THE VOICE OF DOOM
PHRASE|THE GREEN GRASS OF HOME
PHRASE|THE LOVE OF MY LIFE
PHRASE|THE ORDER OF THE DAY
PHRASE|THE PERFECT COUPLE
PHRASE|THE VOICE OF AN ANGEL
PHRASE|THE WHOLE WORLD IS A STAGE
PHRASE|THIS WON'T HURT A BIT
PHRASE|THREE STRIKES AND YOU'RE OUT
PHRASE|TIME HEALS ALL WOUNDS
PHRASE|TOO CLOSE TO CALL
PHRASE|TRUTH IS STRANGER THAN FICTION
PHRASE|WAKE UP AND SMELL THE COFFEE
PHRASE|WHEN I TALK YOU JUMP
PHRASE|YOU ARE WHAT YOU EAT
PHRASE|YOU CAN'T CHEAT AN HONEST MAN
PHRASE|YOU DESERVE A BREAK TODAY
PHRASE|YOU GOTTA BELIEVE
TITLE|A BELL FOR ADANO
TITLE|A MAN FOR ALL SEASONS
TITLE|A TALE OF TWO CITIES
TITLE|ALL MY CHILDREN
TITLE|ALL QUIET ON THE WESTERN FRONT
TITLE|ALL IN THE FAMILY
TITLE|ALL'S WELL THAT ENDS WELL
TITLE|AMERICAN GRAFFITI
TITLE|ANNIE GET YOUR GUN
TITLE|ANTONY AND CLEOPATRA
TITLE|AROUND THE WORLD IN EIGHTY DAYS
TITLE|ARROWSMITH
TITLE|ARSENIC AND OLD LACE
TITLE|AS YOU LIKE IT
TITLE|A CURRENT AFFAIR
TITLE|A STREETCAR NAMED DESIRE
TITLE|BANG THE DRUM SLOWLY
TITLE|BAREFOOT IN THE PARK
TITLE|BORN YESTERDAY
TITLE|CACTUS FLOWER
TITLE|CAPTAINS COURAGEOUS
TITLE|CAROUSEL
TITLE|CASABLANCA
TITLE|CASINO ROYALE
TITLE|CAT BALLOU
TITLE|CAT ON A HOT TIN ROOF
TITLE|CHARLOTTE'S WEB
TITLE|CRIME AND PUNISHMENT
TITLE|DAMN YANKEES
TITLE|DAVID COPPERFIELD
TITLE|DEAD POETS SOCIETY
TITLE|DON'T GO NEAR THE WATER
TITLE|DOONESBURY
TITLE|DR JEKYLL AND MR HYDE
TITLE|FAR FROM THE MADDING CROWD
TITLE|FROM HERE TO ETERNITY
TITLE|FROM RUSSIA WITH LOVE
TITLE|FULL METAL JACKET
TITLE|GUESS WHO'S COMING TO DINNER
TITLE|GULLIVER'S TRAVELS
TITLE|GUYS AND DOLLS
TITLE|HARVEY
TITLE|HELLO DOLLY
TITLE|HIGH PLAINS DRIFTER
TITLE|HOW THE CAMEL GOT ITS HUMP
TITLE|HOW THE RHINOCEROS GOT ITS SKIN
TITLE|HOW GREEN WAS MY VALLEY
TITLE|HOW THE WEST WAS WON
TITLE|HUCKLEBERRY FINN
TITLE|IN THE HEAT OF THE NIGHT
TITLE|INDIANA JONES AND THE LAST CRUSADE
TITLE|INHERIT THE WIND
TITLE|IRMA LA DOUCE
TITLE|ISLAND OF THE BLUE DOLPHINS
TITLE|IT'S A MAD MAD MAD MAD WORLD
TITLE|JONATHAN LIVINGSTON SEAGULL
TITLE|LADY AND THE TRAMP
TITLE|LAST TANGO IN PARIS
TITLE|LES MISERABLES
TITLE|LIFE WITH FATHER
TITLE|LONG DAY'S JOURNEY INTO NIGHT
TITLE|LOOK HOMEWARD ANGEL
TITLE|LOST HORIZON
TITLE|MARJORIE MORNINGSTAR
TITLE|MARRIED TO THE MOB
TITLE|MIDNIGHT COWBOY
TITLE|MURDERS IN THE RUE MORGUE
TITLE|MY FAIR LADY
TITLE|MY SISTER EILEEN
TITLE|NO TIME FOR SERGEANTS
TITLE|NOT NECESSARILY THE NEWS
TITLE|ON THE WATERFRONT
TITLE|PAJAMA GAME
TITLE|PAPER MOON
TITLE|PEYTON PLACE
TITLE|PHANTOM OF THE OPERA
TITLE|PLANET OF THE APES
TITLE|PORTNOY'S COMPLAINT
TITLE|ROMEO AND JULIET
TITLE|ROSEMARY'S BABY
TITLE|SANFORD AND SON
TITLE|SERGEANT YORK
TITLE|SHANE
TITLE|SHENANDOAH
TITLE|SHIP OF FOOLS
TITLE|SOYLENT GREEN
TITLE|STAGECOACH
TITLE|SWAN LAKE
TITLE|TAKE ME OUT TO THE BALL GAME
TITLE|TALES OF THE SOUTH PACIFIC
TITLE|TEAHOUSE OF THE AUGUST MOON
TITLE|THAT TOUCH OF MINK
TITLE|THE BELLS ARE RINGING
TITLE|THE BRIDGE ON THE RIVER KWAI
TITLE|THE CASK OF AMONTILLADO
TITLE|THE DIARY OF ANNE FRANK
TITLE|THE DAY OF THE JACKAL
TITLE|THE FALL OF THE HOUSE OF USHER
TITLE|THE FOUR HORSEMEN OF THE APOCALYPSE
TITLE|THE LIFE AND DEATH OF KING JOHN
TITLE|THE LION IN WINTER
TITLE|THE MARY TYLER MOORE SHOW
TITLE|THE MASQUE OF THE RED DEATH
TITLE|THE PIT AND THE PENDULUM
TITLE|THE PRINCE AND THE PAUPER
TITLE|THE RED BADGE OF COURAGE
TITLE|THE SOUND OF MUSIC
TITLE|THE SPY WHO CAME IN FROM THE COLD
TITLE|THE VICAR OF WAKEFIELD
TITLE|THE YOUNG AND THE RESTLESS
TITLE|THE SUBJECT WAS ROSES
TITLE|THE AGONY AND THE ECSTASY
TITLE|THE ARRANGEMENT
TITLE|THE BEST YEARS OF OUR LIVES
TITLE|THE BLACK CAT
TITLE|THE BRIDGE OF SAN LUIS REY
TITLE|THE BROTHERS KARAMAZOV
TITLE|THE CAINE MUTINY
TITLE|THE CAROL BURNETT SHOW
TITLE|THE COMEDY OF ERRORS
TITLE|THE CRUCIBLE
TITLE|THE DICK VAN DYKE SHOW
TITLE|THE GRADUATE
TITLE|THE GREATEST SHOW ON EARTH
TITLE|THE GREAT WHITE HOPE
TITLE|THE GREEN BERETS
TITLE|THE HOUSE OF THE SEVEN GABLES
TITLE|THE HUNCHBACK OF NOTRE DAME
TITLE|THE KEYS OF THE KINGDOM
TITLE|THE LIGHT THAT FAILED
TITLE|THE LONGEST DAY
TITLE|THE MERCHANT OF VENICE
TITLE|THE MIKADO
TITLE|THE MIRACLE OF THE BELLS
TITLE|THE MONKEY'S PAW
TITLE|THE ODESSA FILE
TITLE|THE OUTSIDERS
TITLE|THE PARENT TRAP
TITLE|THE PARTRIDGE FAMILY
TITLE|THE PATHFINDER
TITLE|THE PICTURE OF DORIAN GRAY
TITLE|THE POSEIDON ADVENTURE
TITLE|THE PRISONER OF ZENDA
TITLE|THE SAND PEBBLES
TITLE|THE SATANIC VERSES
TITLE|THE SECRET GARDEN
TITLE|THE SEVEN YEAR ITCH
TITLE|THE SHAGGY DOG
TITLE|THE SHOES OF THE FISHERMAN
TITLE|THE SONG OF BERNADETTE
TITLE|THE SWISS FAMILY ROBINSON
TITLE|THE TAMING OF THE SHREW
TITLE|THE THREE MUSKETEERS
TITLE|THE UNSINKABLE MOLLY BROWN
TITLE|THIRTY SOMETHING
TITLE|THOROUGHLY MODERN MILLIE
TITLE|THUNDERBALL
TITLE|TO KILLA MOCKINGBIRD
TITLE|TO SIR WITH LOVE
TITLE|TREASURE ISLAND
TITLE|TREASURE OF SIERRA MADRE
TITLE|TROILUS AND CRESSIDA
TITLE|TWO GENTLEMEN OF VERONA
TITLE|UPSTAIRS DOWNSTAIRS
TITLE|VALLEY OF THE DOLLS
TITLE|WEBSTER'S NEW WORLD LARGE PRINT DICTIONARY
TITLE|WHAT'S NEW PUSSYCAT
TITLE|WHO'S AFRAID OF VIRGINIA WOOLF
TITLE|WUTHERING HEIGHTS
TITLE|YANKEE DOODLE DANDY
TITLE|YOU CAN'T DO THAT ON TELEVISION
TITLE|YOU CAN'T TAKE IT WITH YOU
TITLE|YOU ONLY LIVE TWICE
TITLE|YOU'RE A GOOD MAN CHARLIE BROWN
PEOPLE|ACCOUNTING FIRM
PEOPLE|AIR RAID WARDENS
PEOPLE|AMERICAN LEAGUE ALL-STAR TEAM
PEOPLE|BOLSHOI BALLET
PEOPLE|BOSOM BUDDIES
PEOPLE|BOSTON POPS ORCHESTRA
PEOPLE|CANDY- STRIPER VOLUNTEERS
PEOPLE|CHAMBER OF COMMERCE
PEOPLE|CHILD STUDY TEAM
PEOPLE|CITY COUNCIL
PEOPLE|CUBAN EXILES
PEOPLE|FOREIGN INVESTORS
PEOPLE|GAME SHOW CONTESTANTS
PEOPLE|GRADUATING CLASS
PEOPLE|GREGG ALLMAN BAND
PEOPLE|HOUSE OF COMMONS
PEOPLE|INNOCENT BYSTANDERS
PEOPLE|KNIGHTS OF THE ROUND TABLE
PEOPLE|LITTLE LEAGUE CHAMPIONS
PEOPLE|LONDON BOBBIES
PEOPLE|LOTTERY WINNERS
PEOPLE|MARINE PATROL
PEOPLE|PHILISTINES
PEOPLE|POWER SQUADRON
PEOPLE|PYGMIES
PEOPLE|RADIO CITY MUSIC HALL ROCKETTES
PEOPLE|ROMULUS AND REMUS
PEOPLE|ROOKIE COPS
PEOPLE|SALVATION ARMY SANTAS
PEOPLE|SAMSON AND DELILAH
PEOPLE|SPYRO GYRA
PEOPLE|SUPREME COURT JUSTICES
PEOPLE|SWAT TEAM
PEOPLE|SYMPHONY ORCHESTRA
PEOPLE|TAXICAB DRIVERS
PEOPLE|TEAMSTERS UNION MEMBERS
PEOPLE|THE BLUE ANGELS
PEOPLE|THE DALLAS COWBOYS
PEOPLE|THE DIRTY DOZEN BRASS BAND
PEOPLE|THE FLORIDA STATE SEMINOLES
PEOPLE|THE LITTLE RASCALS
PEOPLE|THE MIAMI HEAT
PEOPLE|THE MONKEES
PEOPLE|THE OKLAHOMA SOONERS
PEOPLE|THE PRESIDENT'S CABINET
PEOPLE|VISIGOTHS
PEOPLE|WORLD CLASS WRESTLERS
EVENT|A ROYAL CORONATION
EVENT|AFTERNOON NAP
EVENT|AMERICAN KENNEL CLUB DOG SHOW
EVENT|BATTLE OF THE BULGE
EVENT|BAY OF PIGS INVASION
EVENT|BRIDAL SHOWER
EVENT|CANNES FILM FESTIVAL
EVENT|EXXON VALDEZ OIL SPILL
EVENT|FOOTBALL HALFTIME SHOW
EVENT|JANUARY WHITE SALE
EVENT|LOTTERY DRAWING
EVENT|MILITARY COURT MARTIAL
EVENT|MUSCULAR DYSTROPHY TELETHON
EVENT|NATIONAL SPELLING BEE CONTEST
EVENT|ORGAN TRANSPLANT SURGERY
EVENT|PIE-EATING CONTEST
EVENT|RIBBON- CUTTING CEREMONY
EVENT|SALZBURG MUSIC FESTIVAL
EVENT|SECRETARIES DAY
EVENT|SPRING BREAK
EVENT|SWEET SIXTEEN PARTY
EVENT|TAKING THE BAR EXAM
EVENT|THE ALLIED INVASION OF ANZIO
EVENT|THE DARK AGES
EVENT|THE AMERICAN REVOLUTION
EVENT|THE COLLEGE WORLD SERIES
EVENT|THE JUNIOR OLYMPICS
EVENT|THE ORANGE BOWL FESTIVAL
EVENT|THE SIEGE OF LENINGRAD
EVENT|THE SPANISH CIVIL WAR
EVENT|THE TROJAN WAR
EVENT|TOURNAMENT OF ROSES PARADE
EVENT|TUPPERWARE PARTY
EVENT|UNASSISTED DOUBLE-PLAY
EVENT|WEDDING ANNIVERSARY
SAME NAME|ADAM MAE AND JERRY WEST
SAME NAME|ADLAI AND ROBERT LOUIS STEVENSON
SAME NAME|AGNES AND CECIL B DE MILLE
SAME NAME|AMY AND WASHINGTON IRVING
SAME NAME|ANDREW AND GIG YOUNG
SAME NAME|ANDREW JACK AND LYNDON JOHNSON
SAME NAME|ANDY HANK AND JO BETH WILLIAMS
SAME NAME|ANTHONY AND DAN QUAYLE
SAME NAME|ANTHONY MIRIAM AND HARRY HOPKINS
SAME NAME|ARETHA AND BENJAMIN FRANKLIN
SAME NAME|ARNOLD AND LILY PALMER
SAME NAME|ARTHUR GLENN AND BARNEY MILLER
SAME NAME|ARTIE AND GEORGE BERNARD SHAW
SAME NAME|BARBARA AND JOHANN SEBASTIAN BACH
SAME NAME|BARRY ANNIE AND JOHN L SULLIVAN
SAME NAME|ARTHUR BENNY AND BUNKER HILL
SAME NAME|BETSY AND DIANA ROSS
SAME NAME|BILLY AND DEAN MARTIN
SAME NAME|BOB AND JOANNE WOODWARD
SAME NAME|BOOG AND DICK POWELL
SAME NAME|BROOKLYN LONDON AND LLOYD BRIDGES
SAME NAME|BUDDY AND RICHIE RICH
SAME NAME|BUTCH AND SHAWN CASSIDY
SAME NAME|BUTTERFLY AND STEVE MCQUEEN
SAME NAME|CAPE AND LITTLE BIG HORN
SAME NAME|CAROLE ALAN AND STEPHEN KING
SAME NAME|CHARLIE AND HELEN KELLER
SAME NAME|CHIC ALAN AND ROLAND YOUNG
SAME NAME|CHRISTINE AND RUBY KEELER
SAME NAME|CHRISTOPHER AND PHILIP MARLOWE
SAME NAME|CLIFTON AND JACK WEBB
SAME NAME|DANIEL PAT AND RICHARD BOONE
SAME NAME|DEBBIE AND R J REYNOLDS
SAME NAME|DICK AND RAMSEY CLARK
SAME NAME|DR BENJAMIN AND MR SPOCK
SAME NAME|DUCHESS OF AND CLARK KENT
SAME NAME|DUSTIN AND ABBIE HOFFMAN
SAME NAME|EDWARD G JACKIE AND MRS ROBINSON
SAME NAME|ELIZABETH AND EVE ARDEN
SAME NAME|ELMO AND ABRAHAM LINCOLN
SAME NAME|ERSKINE AND TAYLOR CALDWELL
SAME NAME|ESTHER TED AND BILLY DEE WILLIAMS
SAME NAME|EVANGELINE AND EDWIN BOOTH
SAME NAME|F LEE AND BEETLE BAILEY
SAME NAME|FAYE AND RALPH WALDO EMERSON
SAME NAME|FORREST AND SOPHIE TUCKER
SAME NAME|GARRY AND PIERRE TRUDEAU
SAME NAME|GENE AND THORTON WILDER
SAME NAME|GEORGE ARTHUR AND ROSE KENNEDY
SAME NAME|GEORGE AND T S ELIOT
SAME NAME|GEORGE BERNARD AND ROBERT SHAW
SAME NAME|GEORGE HENRY AND IRVING WALLACE
SAME NAME|GINGER BUCK AND BUDDY ROGERS
SAME NAME|GORGEOUS AND BOY GEORGE
SAME NAME|GROVER CLEVELAND AND BRANDY ALEXANDER
SAME NAME|GYPSY ROSE BRUCE AND ROBERT E LEE
SAME NAME|HARRISON GERALD AND MODEL T FORD
SAME NAME|HAROLD NANCY AND WOODROW WILSON
SAME NAME|HARRY AND JESSIE JAMES
SAME NAME|HAYLEY AND GENERAL MILLS
SAME NAME|HELEN GURLEY AND CHARLIE BROWN
SAME NAME|HUGH AND CHURCHILL DOWNS
SAME NAME|IAN AND RHONDA FLEMING
SAME NAME|INDIANA TOM AND GRACE JONES
SAME NAME|ISAAC AND BILL STERN
SAME NAME|JACKIE WALKER AND GORDON COOPER
SAME NAME|JACK JOHNNY AND KIT CARSON
SAME NAME|JACLYN KATE AND JOHN SMITH
SAME NAME|JAMES LES AND JIMMY BROWN
SAME NAME|JAMES AND CARROLL BAKER
SAME NAME|JAMES AND VAUGHAN MONROE
SAME NAME|JAY AND ELLIOTT GOULD
SAME NAME|JEANETTE ROSS AND OLD MACDONALD
SAME NAME|JERRY SHARI AND JOHN L LEWIS
SAME NAME|JIMMY JACK AND LINDA CARTER
SAME NAME|JODIE AND STEPHEN FOSTER
SAME NAME|JOHN CAMERON AND PATRICK SWAYZE
SAME NAME|JOSEPH AND CHARLIE MCCARTHY
SAME NAME|JOSEPH AND WILLIAM CONRAD
SAME NAME|JOE AND ROY CAMPANELLA
SAME NAME|JULIE AND MAXINE ANDREWS
SAME NAME|KAREN AND SCOTT CARPENTER
SAME NAME|KATE GLENDA AND STONEWALL JACKSON
SAME NAME|KIRK MIKE AND WILLIAM O DOUGLAS
SAME NAME|LARRY AND BIG BIRD
SAME NAME|LEONARD AND CARL BERNSTEIN
SAME NAME|LE VAR AND RICHARD BURTON
SAME NAME|LEVI AND PETER STRAUSS
SAME NAME|LILLIAN AND PHILIP ROTH
SAME NAME|LONI JACK AND MAXWELL ANDERSON
SAME NAME|LORETTA GIG AND CY YOUNG
SAME NAME|MARIA AND CHARLIE CALLAS
SAME NAME|MARLO TERRY AND ISIAH THOMAS
SAME NAME|MARNI AND RICHARD NIXON
SAME NAME|MARY AND RICHARD TODD
SAME NAME|MEL AND MONT BLANC
SAME NAME|MEL AND OUR MISS BROOKS
SAME NAME|MICHAEL J AND TWENTIETH CENTURY FOX
SAME NAME|MICHAEL SERGEANT AND DUKE OF YORK
SAME NAME|NEIL AND BASEBALL DIAMOND
SAME NAME|NEIL AND JACK ARMSTRONG
SAME NAME|NEVILLE AND WILT CHAMBERLAIN
SAME NAME|NIPSEY AND KURT RUSSELL
SAME NAME|NOLAN AND ROBERT RYAN
SAME NAME|NORMAN AND GEORGE LINCOLN ROCKWELL
SAME NAME|O J AND WALLIS WARFIELD SIMPSON
SAME NAME|OMAR AND BILL BRADLEY
SAME NAME|ORAL AND MR ROBERTS
SAME NAME|ORSON AND H G WELLES
SAME NAME|ROBERT PETER AND NATHANIEL BENCHLEY
SAME NAME|PETER AND EMIL JENNINGS
SAME NAME|QUICK DRAW TUG AND ALI MC GRAW
SAME NAME|RAYMOND AND AARON BURR
SAME NAME|REX AND GEORGE HARRISON
SAME NAME|RICHARD AND FORT DIX
SAME NAME|RICKY AND BABY FACE NELSON
SAME NAME|RINGO BRENDA AND KAY STARR
SAME NAME|ROBERT AND GEORGE BURNS
SAME NAME|ROCK AND HENRY HUDSON
SAME NAME|RUTHERFORD AND GABBY HAYES
SAME NAME|SALLY MARSHALL AND SOLDIER FIELD
SAME NAME|SARAH AND ROBERT VAUGHN
SAME NAME|SHELLEY AND JONATHAN WINTERS
SAME NAME|SIGOURNEY DENNIS AND PAT WEAVER
SAME NAME|SINCLAIR AND JERRY LEE LEWIS
SAME NAME|SIR WALTER AND GEORGE C SCOTT
SAME NAME|SANDRA DAY DONALD AND CARROLL O'CONNOR
SAME NAME|SPENCER AND DICK TRACY
SAME NAME|THELMA AND TEX RITTER
SAME NAME|THEODORE SANFORD AND BETTY WHITE
SAME NAME|THURGOOD AND E G MARSHALL
SAME NAME|TONY AND JOAN BENNETT
SAME NAME|VERONICA ARTHUR AND GREAT SALT LAKE
SAME NAME|VINCENT AND LEONTYNE PRICE
SAME NAME|WALDO AND CLAUDE PEPPER
SAME NAME|WALT GENE AND GRACE KELLY
SAME NAME|WHOOPI AND RUBE GOLDBERG
SAME NAME|WILLIAM AMANDA AND ROBERT BLAKE
SAME NAME|WOODY MARTY AND ETHAN ALLEN
THINGS|ASTEROIDS
THINGS|ATOMIC SUBMARINES
THINGS|BAR AND DUMBBELL SET
THINGS|CARPENTER ANTS
THINGS|CARVING KNIVES
THINGS|COMPUTER CHIPS
THINGS|DOMINOES
THINGS|ICE SKATES
THINGS|INDEX CARDS
THINGS|JOYSTICKS
THINGS|LIBRARY BOOKS
THINGS|LYMPH NODES
THINGS|MATH PROBLEMS
THINGS|METEORITES
THINGS|MEZZANINE SEATS
THINGS|MONTHLY BILLS
THINGS|MOSQUITOES
THINGS|NAUTILUS EQUIPMENT
THINGS|PARALLEL BARS
THINGS|RUFFLED CURTAINS
THINGS|SCIENCE EXPERIMENTS
THINGS|SOCIAL SECURITY BENEFITS
THINGS|STORM CLOUDS
THINGS|TAX REFUND CHECKS
THINGS|THIRD- DEGREE BURNS
THINGS|UNDERWATER GOGGLES
THINGS|VIDEO CASSETTE RECORDERS
THINGS|WANTED POSTERS
THINGS|WATER SKIS
THINGS|FOREIGN FILMS
THINGS|OLD NEWSPAPERS
THINGS|GARDEN WEEDS
THINGS|GUERNSEY COWS
`;